/* Generated by Nim Compiler v0.14.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Tinfocpu170477 Tinfocpu170477;
typedef struct Tinfoos170037 Tinfoos170037;
typedef struct Cell47905 Cell47905;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Gcheap50418 Gcheap50418;
typedef struct Gcstack50416 Gcstack50416;
typedef struct Memregion30086 Memregion30086;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30080 Llchunk30080;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Avlnode30084 Avlnode30084;
typedef struct Gcstat50414 Gcstat50414;
typedef struct Cellset47917 Cellset47917;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
typedef NU8 Tsystemcpu170454;
typedef NU8 Tsystemos170006;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, Globalmarkerproc56402) (void);
typedef NU8 Tendian170475;
struct Tinfocpu170477 {
NimStringDesc* Field0;
NI Field1;
Tendian170475 Field2;
NI Field3;
NI Field4;
};
typedef Tinfocpu170477 TY170511[18];
typedef NU8 Tinfoosprop170033Set;
struct Tinfoos170037 {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
NimStringDesc* Field3;
NimStringDesc* Field4;
NimStringDesc* Field5;
NimStringDesc* Field6;
NimStringDesc* Field7;
NimStringDesc* Field8;
NimStringDesc* Field9;
NimStringDesc* Field10;
NimStringDesc* Field11;
Tinfoosprop170033Set Field12;
};
typedef Tinfoos170037 TY170084[24];
struct  Cell47905  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47921  {
NI len;
NI cap;
Cell47905** d;
};
typedef Smallchunk30040* TY30101[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {
Trunkbuckets30012 data;
};
struct  Memregion30086  {
NI minlargeobj;
NI maxlargeobj;
TY30101 freesmallchunks;
Llchunk30080* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30084* root;
Avlnode30084* deleted;
Avlnode30084* last;
Avlnode30084* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat50414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47917  {
NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
struct  Gcheap50418  {
Gcstack50416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellseq47921 tempstack;
NI recgclock;
Memregion30086 region;
Gcstat50414 stat;
Cellset47917 marked;
Cellseq47921 additionalroots;
};
struct  Gcstack50416  {
Gcstack50416* prev;
Gcstack50416* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk30038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {
  Basechunk30038 Sup;
Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30080  {
NI size;
NI acc;
Llchunk30080* next;
};
struct  Bigchunk30042  {
  Basechunk30038 Sup;
Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
typedef NI TY30019[8];
struct  Trunk30010  {
Trunk30010* next;
NI key;
TY30019 bits;
};
typedef Avlnode30084* TY30091[2];
struct  Avlnode30084  {
TY30091 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47913  {
Pagedesc47913* next;
NI key;
TY30019 bits;
};
struct  Freecell30030  {
Freecell30030* next;
NI zerofield;
};
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, TMP84)();
N_NIMCALL(void, nimRegisterGlobalMarker)(Globalmarkerproc56402 markerproc0);
N_NIMCALL(Tsystemcpu170454, nametocpu_170633_4151366050)(NimStringDesc* name0);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a0, NimStringDesc* b0);
N_NIMCALL(Tsystemos170006, nametoos_170630_4151366050)(NimStringDesc* name0);
N_NIMCALL(void, settarget_170644_4151366050)(Tsystemos170006 o0, Tsystemcpu170454 c0);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p0);
static N_INLINE(Cell47905*, usrtocell_52040_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_53201_1689653243)(Cell47905* c0);
N_NOINLINE(void, addzct_52017_1689653243)(Cellseq47921* s0, Cell47905* c0);
STRING_LITERAL(TMP85, "i386", 4);
STRING_LITERAL(TMP86, "m68k", 4);
STRING_LITERAL(TMP87, "alpha", 5);
STRING_LITERAL(TMP88, "powerpc", 7);
STRING_LITERAL(TMP89, "powerpc64", 9);
STRING_LITERAL(TMP90, "powerpc64el", 11);
STRING_LITERAL(TMP91, "sparc", 5);
STRING_LITERAL(TMP92, "vm", 2);
STRING_LITERAL(TMP93, "ia64", 4);
STRING_LITERAL(TMP94, "amd64", 5);
STRING_LITERAL(TMP95, "mips", 4);
STRING_LITERAL(TMP96, "mipsel", 6);
STRING_LITERAL(TMP97, "arm", 3);
STRING_LITERAL(TMP98, "arm64", 5);
STRING_LITERAL(TMP99, "js", 2);
STRING_LITERAL(TMP100, "nimrodvm", 8);
STRING_LITERAL(TMP101, "avr", 3);
STRING_LITERAL(TMP102, "msp430", 6);
NIM_CONST TY170511 Cpu_170497_4151366050 = {{((NimStringDesc*) &TMP85),
((NI) 32),
((Tendian170475) 0),
((NI) 64),
((NI) 32)}
,
{((NimStringDesc*) &TMP86),
((NI) 32),
((Tendian170475) 1),
((NI) 64),
((NI) 32)}
,
{((NimStringDesc*) &TMP87),
((NI) 64),
((Tendian170475) 0),
((NI) 64),
((NI) 64)}
,
{((NimStringDesc*) &TMP88),
((NI) 32),
((Tendian170475) 1),
((NI) 64),
((NI) 32)}
,
{((NimStringDesc*) &TMP89),
((NI) 64),
((Tendian170475) 1),
((NI) 64),
((NI) 64)}
,
{((NimStringDesc*) &TMP90),
((NI) 64),
((Tendian170475) 0),
((NI) 64),
((NI) 64)}
,
{((NimStringDesc*) &TMP91),
((NI) 32),
((Tendian170475) 1),
((NI) 64),
((NI) 32)}
,
{((NimStringDesc*) &TMP92),
((NI) 32),
((Tendian170475) 0),
((NI) 64),
((NI) 32)}
,
{((NimStringDesc*) &TMP93),
((NI) 64),
((Tendian170475) 0),
((NI) 64),
((NI) 64)}
,
{((NimStringDesc*) &TMP94),
((NI) 64),
((Tendian170475) 0),
((NI) 64),
((NI) 64)}
,
{((NimStringDesc*) &TMP95),
((NI) 32),
((Tendian170475) 1),
((NI) 64),
((NI) 32)}
,
{((NimStringDesc*) &TMP96),
((NI) 32),
((Tendian170475) 0),
((NI) 64),
((NI) 32)}
,
{((NimStringDesc*) &TMP97),
((NI) 32),
((Tendian170475) 0),
((NI) 64),
((NI) 32)}
,
{((NimStringDesc*) &TMP98),
((NI) 64),
((Tendian170475) 0),
((NI) 64),
((NI) 64)}
,
{((NimStringDesc*) &TMP99),
((NI) 32),
((Tendian170475) 1),
((NI) 64),
((NI) 32)}
,
{((NimStringDesc*) &TMP100),
((NI) 32),
((Tendian170475) 1),
((NI) 64),
((NI) 32)}
,
{((NimStringDesc*) &TMP101),
((NI) 16),
((Tendian170475) 0),
((NI) 32),
((NI) 16)}
,
{((NimStringDesc*) &TMP102),
((NI) 16),
((Tendian170475) 0),
((NI) 32),
((NI) 16)}
}
;
STRING_LITERAL(TMP103, "DOS", 3);
STRING_LITERAL(TMP104, "..", 2);
STRING_LITERAL(TMP105, "$1.dll", 6);
STRING_LITERAL(TMP106, "/", 1);
STRING_LITERAL(TMP107, ".obj", 4);
STRING_LITERAL(TMP108, "\015\012", 2);
STRING_LITERAL(TMP109, ";", 1);
STRING_LITERAL(TMP110, "\\", 1);
STRING_LITERAL(TMP111, ".bat", 4);
STRING_LITERAL(TMP112, ".", 1);
STRING_LITERAL(TMP113, ".exe", 4);
STRING_LITERAL(TMP114, "Windows", 7);
STRING_LITERAL(TMP115, "OS2", 3);
STRING_LITERAL(TMP116, "Linux", 5);
STRING_LITERAL(TMP117, "lib$1.so", 8);
STRING_LITERAL(TMP118, ".o", 2);
STRING_LITERAL(TMP119, "\012", 1);
STRING_LITERAL(TMP120, ":", 1);
STRING_LITERAL(TMP121, ".sh", 3);
STRING_LITERAL(TMP122, "", 0);
STRING_LITERAL(TMP123, "MorphOS", 7);
STRING_LITERAL(TMP124, "SkyOS", 5);
STRING_LITERAL(TMP125, "Solaris", 7);
STRING_LITERAL(TMP126, "Irix", 4);
STRING_LITERAL(TMP127, "NetBSD", 6);
STRING_LITERAL(TMP128, "FreeBSD", 7);
STRING_LITERAL(TMP129, "OpenBSD", 7);
STRING_LITERAL(TMP130, "AIX", 3);
STRING_LITERAL(TMP131, "PalmOS", 6);
STRING_LITERAL(TMP132, "QNX", 3);
STRING_LITERAL(TMP133, "Amiga", 5);
STRING_LITERAL(TMP134, "$1.library", 10);
STRING_LITERAL(TMP135, "Atari", 5);
STRING_LITERAL(TMP136, ".tpp", 4);
STRING_LITERAL(TMP137, "Netware", 7);
STRING_LITERAL(TMP138, "$1.nlm", 6);
STRING_LITERAL(TMP139, ".nlm", 4);
STRING_LITERAL(TMP140, "MacOS", 5);
STRING_LITERAL(TMP141, "::", 2);
STRING_LITERAL(TMP142, "$1Lib", 5);
STRING_LITERAL(TMP143, "\015", 1);
STRING_LITERAL(TMP144, ",", 1);
STRING_LITERAL(TMP145, "MacOSX", 6);
STRING_LITERAL(TMP146, "lib$1.dylib", 11);
STRING_LITERAL(TMP147, "Haiku", 5);
STRING_LITERAL(TMP148, "VxWorks", 7);
STRING_LITERAL(TMP149, ".vxe", 4);
STRING_LITERAL(TMP150, "JS", 2);
STRING_LITERAL(TMP151, "NimrodVM", 8);
STRING_LITERAL(TMP152, "Standalone", 10);
NIM_CONST TY170084 Os_170070_4151366050 = {{((NimStringDesc*) &TMP103),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP105),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP107),
((NimStringDesc*) &TMP108),
((NimStringDesc*) &TMP109),
((NimStringDesc*) &TMP110),
((NimStringDesc*) &TMP111),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP113),
((NimStringDesc*) &TMP112),
2}
,
{((NimStringDesc*) &TMP114),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP105),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP107),
((NimStringDesc*) &TMP108),
((NimStringDesc*) &TMP109),
((NimStringDesc*) &TMP110),
((NimStringDesc*) &TMP111),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP113),
((NimStringDesc*) &TMP112),
2}
,
{((NimStringDesc*) &TMP115),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP105),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP107),
((NimStringDesc*) &TMP108),
((NimStringDesc*) &TMP109),
((NimStringDesc*) &TMP110),
((NimStringDesc*) &TMP111),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP113),
((NimStringDesc*) &TMP112),
2}
,
{((NimStringDesc*) &TMP116),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
5}
,
{((NimStringDesc*) &TMP123),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
5}
,
{((NimStringDesc*) &TMP124),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
5}
,
{((NimStringDesc*) &TMP125),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
5}
,
{((NimStringDesc*) &TMP126),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
5}
,
{((NimStringDesc*) &TMP127),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
5}
,
{((NimStringDesc*) &TMP128),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
5}
,
{((NimStringDesc*) &TMP129),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
5}
,
{((NimStringDesc*) &TMP130),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
5}
,
{((NimStringDesc*) &TMP131),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
1}
,
{((NimStringDesc*) &TMP132),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
5}
,
{((NimStringDesc*) &TMP133),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP134),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
1}
,
{((NimStringDesc*) &TMP135),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP105),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP136),
((NimStringDesc*) &TMP112),
1}
,
{((NimStringDesc*) &TMP137),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP138),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP108),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP139),
((NimStringDesc*) &TMP112),
2}
,
{((NimStringDesc*) &TMP140),
((NimStringDesc*) &TMP141),
((NimStringDesc*) &TMP142),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP143),
((NimStringDesc*) &TMP144),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
2}
,
{((NimStringDesc*) &TMP145),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP146),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
13}
,
{((NimStringDesc*) &TMP147),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
13}
,
{((NimStringDesc*) &TMP148),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP109),
((NimStringDesc*) &TMP110),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP149),
((NimStringDesc*) &TMP112),
13}
,
{((NimStringDesc*) &TMP150),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
0}
,
{((NimStringDesc*) &TMP151),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
0}
,
{((NimStringDesc*) &TMP152),
((NimStringDesc*) &TMP104),
((NimStringDesc*) &TMP117),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP118),
((NimStringDesc*) &TMP119),
((NimStringDesc*) &TMP120),
((NimStringDesc*) &TMP106),
((NimStringDesc*) &TMP121),
((NimStringDesc*) &TMP112),
((NimStringDesc*) &TMP122),
((NimStringDesc*) &TMP112),
0}
}
;
STRING_LITERAL(TMP153, "solaris", 7);
Tsystemcpu170454 targetcpu_170622_4151366050;
Tsystemcpu170454 hostcpu_170623_4151366050;
Tsystemos170006 targetos_170624_4151366050;
Tsystemos170006 hostos_170625_4151366050;
NI intsize_170636_4151366050;
NI floatsize_170637_4151366050;
NI ptrsize_170638_4151366050;
NimStringDesc* tnl_170639_4151366050;
extern TNimType NTI138; /* string */
extern Gcheap50418 gch_50458_1689653243;
N_NIMCALL(void, TMP84)() {
	nimGCvisit((void*)tnl_170639_4151366050, 0);
}

N_NIMCALL(Tsystemcpu170454, nametocpu_170633_4151366050)(NimStringDesc* name0) {
	Tsystemcpu170454 result0;
{	result0 = (Tsystemcpu170454)0;
	{
		Tsystemcpu170454 i_171414_4151366050;
		NI res_171419_4151366050;
		i_171414_4151366050 = (Tsystemcpu170454)0;
		res_171419_4151366050 = ((NI) 1);
		{
			while (1) {
				if (!(res_171419_4151366050 <= ((NI) 18))) goto LA3;
				i_171414_4151366050 = ((Tsystemcpu170454) (res_171419_4151366050));
				{
					NI LOC6;
					LOC6 = (NI)0;
					LOC6 = nsuCmpIgnoreStyle(name0, Cpu_170497_4151366050[(i_171414_4151366050)- 1].Field0);
					if (!(LOC6 == ((NI) 0))) goto LA7;
					result0 = i_171414_4151366050;
					goto BeforeRet;
				}
				LA7: ;
				res_171419_4151366050 += ((NI) 1);
			} LA3: ;
		}
	}
	result0 = ((Tsystemcpu170454) 0);
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(Tsystemos170006, nametoos_170630_4151366050)(NimStringDesc* name0) {
	Tsystemos170006 result0;
{	result0 = (Tsystemos170006)0;
	{
		Tsystemos170006 i_171214_4151366050;
		NI res_171219_4151366050;
		i_171214_4151366050 = (Tsystemos170006)0;
		res_171219_4151366050 = ((NI) 1);
		{
			while (1) {
				if (!(res_171219_4151366050 <= ((NI) 24))) goto LA3;
				i_171214_4151366050 = ((Tsystemos170006) (res_171219_4151366050));
				{
					NI LOC6;
					LOC6 = (NI)0;
					LOC6 = nsuCmpIgnoreStyle(name0, Os_170070_4151366050[(i_171214_4151366050)- 1].Field0);
					if (!(LOC6 == ((NI) 0))) goto LA7;
					result0 = i_171214_4151366050;
					goto BeforeRet;
				}
				LA7: ;
				res_171219_4151366050 += ((NI) 1);
			} LA3: ;
		}
	}
	result0 = ((Tsystemos170006) 0);
	}BeforeRet: ;
	return result0;
}

static N_INLINE(Cell47905*, usrtocell_52040_1689653243)(void* usr0) {
	Cell47905* result0;
	result0 = (Cell47905*)0;
	result0 = ((Cell47905*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell47905))))));
	return result0;
}

static N_INLINE(void, rtladdzct_53201_1689653243)(Cell47905* c0) {
	addzct_52017_1689653243((&gch_50458_1689653243.zct), c0);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p0) {
	Cell47905* c0;
	c0 = usrtocell_52040_1689653243(p0);
	{
		(*c0).refcount -= ((NI) 8);
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_53201_1689653243(c0);
	}
	LA3: ;
}

N_NIMCALL(void, settarget_170644_4151366050)(Tsystemos170006 o0, Tsystemcpu170454 c0) {
	NimStringDesc* LOC1;
	targetcpu_170622_4151366050 = c0;
	targetos_170624_4151366050 = o0;
	intsize_170636_4151366050 = (NI)(Cpu_170497_4151366050[(c0)- 1].Field1 / ((NI) 8));
	floatsize_170637_4151366050 = (NI)(Cpu_170497_4151366050[(c0)- 1].Field3 / ((NI) 8));
	ptrsize_170638_4151366050 = (NI)(Cpu_170497_4151366050[(c0)- 1].Field4 / ((NI) 8));
	LOC1 = (NimStringDesc*)0;
	LOC1 = tnl_170639_4151366050; tnl_170639_4151366050 = copyStringRC1(Os_170070_4151366050[(o0)- 1].Field5);
	if (LOC1) nimGCunrefNoCycle(LOC1);
}
NIM_EXTERNC N_NOINLINE(void, compiler_platformInit000)(void) {
nimRegisterGlobalMarker(TMP84);
	hostcpu_170623_4151366050 = nametocpu_170633_4151366050(((NimStringDesc*) &TMP94));
	hostos_170625_4151366050 = nametoos_170630_4151366050(((NimStringDesc*) &TMP153));
	settarget_170644_4151366050(hostos_170625_4151366050, hostcpu_170623_4151366050);
}

NIM_EXTERNC N_NOINLINE(void, compiler_platformDatInit000)(void) {
}

