/* Generated by Nim Compiler v0.14.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct TY400226 TY400226;
typedef struct TY400227 TY400227;
typedef struct Tsymseq264796 Tsymseq264796;
typedef struct Tsym264826 Tsym264826;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47905 Cell47905;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Gcheap50418 Gcheap50418;
typedef struct Gcstack50416 Gcstack50416;
typedef struct Memregion30086 Memregion30086;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30080 Llchunk30080;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Avlnode30084 Avlnode30084;
typedef struct Gcstat50414 Gcstat50414;
typedef struct Cellset47917 Cellset47917;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Tidobj194006 Tidobj194006;
typedef struct TNimObject TNimObject;
typedef struct Ttypeseq264828 Ttypeseq264828;
typedef struct Tscope264820 Tscope264820;
typedef struct TY264927 TY264927;
typedef struct Tstrtable264798 Tstrtable264798;
typedef struct Ttype264832 Ttype264832;
typedef struct Tident194012 Tident194012;
typedef struct Tlineinfo186336 Tlineinfo186336;
typedef struct Tnode264794 Tnode264794;
typedef struct Tloc264808 Tloc264808;
typedef struct Ropeobj173006 Ropeobj173006;
typedef struct Tlib264812 Tlib264812;
typedef struct NimStringDesc NimStringDesc;
typedef struct Tnodeseq264788 Tnodeseq264788;
typedef struct Intset241031 Intset241031;
typedef struct Trunk241027 Trunk241027;
typedef struct Trunkseq241029 Trunkseq241029;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
typedef struct Tinstantiation264816 Tinstantiation264816;
typedef struct Tlistentry141010 Tlistentry141010;
typedef struct TY264917 TY264917;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct TY400227 {
Tsymseq264796* Field0;
Tsym264826* Field1;
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, Globalmarkerproc56402) (void);
struct  Cell47905  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47921  {
NI len;
NI cap;
Cell47905** d;
};
typedef Smallchunk30040* TY30101[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {
Trunkbuckets30012 data;
};
struct  Memregion30086  {
NI minlargeobj;
NI maxlargeobj;
TY30101 freesmallchunks;
Llchunk30080* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30084* root;
Avlnode30084* deleted;
Avlnode30084* last;
Avlnode30084* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat50414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47917  {
NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
struct  Gcheap50418  {
Gcstack50416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellseq47921 tempstack;
NI recgclock;
Memregion30086 region;
Gcstat50414 stat;
Cellset47917 marked;
Cellseq47921 additionalroots;
};
typedef NU8 Methodresult400249;
struct  TNimObject  {
TNimType* m_type;
};
struct  Tidobj194006  {
  TNimObject Sup;
NI id;
};
typedef NU8 Tsymkind264435;
struct  Tstrtable264798  {
NI counter;
Tsymseq264796* data;
};
typedef NU8 Tmagic264525;
struct  Tlineinfo186336  {
NI16 line;
NI16 col;
NI32 fileindex;
};
typedef NU32 Tsymflag264184Set;
typedef NU32 Toption164009Set;
typedef NU8 Tlockind264800;
typedef NU8 Tstorageloc264804;
typedef NU16 Tlocflag264802Set;
struct  Tloc264808  {
Tlockind264800 k;
Tstorageloc264804 s;
Tlocflag264802Set flags;
Ttype264832* t;
Ropeobj173006* r;
Ropeobj173006* heaproot;
};
struct  Tsym264826  {
  Tidobj194006 Sup;
Tsymkind264435 kind;
union{
struct {Ttypeseq264828* typeinstcache;
Tscope264820* typscope;
} S1;
struct {TY264927* procinstcache;
Tsym264826* gcunsafetyreason;
} S2;
struct {TY264927* usedgenerics;
Tstrtable264798 tab;
} S3;
struct {Tsym264826* guard;
NI bitsize;
} S4;
} kindU;
Tmagic264525 magic;
Ttype264832* typ;
Tident194012* name;
Tlineinfo186336 info;
Tsym264826* owner;
Tsymflag264184Set flags;
Tnode264794* ast;
Toption164009Set options;
NI position;
NI offset;
Tloc264808 loc;
Tlib264812* annex;
Tnode264794* constraint;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Tident194012  {
  Tidobj194006 Sup;
NimStringDesc* s;
Tident194012* next;
NI h;
};
typedef NU8 Ttypecmpflag295625Set;
typedef NU8 Ttypekind264244;
typedef NU8 Tcallingconvention264002;
typedef NU32 Ttypeflag264431Set;
struct  Ttype264832  {
  Tidobj194006 Sup;
Ttypekind264244 kind;
Tcallingconvention264002 callconv;
Ttypeflag264431Set flags;
Ttypeseq264828* sons;
Tnode264794* n;
Tsym264826* owner;
Tsym264826* sym;
Tsym264826* destructor;
Tsym264826* deepcopy;
Tsym264826* assignment;
NI64 size;
NI16 align;
NI16 locklevel;
Tloc264808 loc;
};
typedef NU64 Ttypekind264244Set;
typedef NU16 Tnodeflag264427Set;
typedef NU8 Tnodekind264020;
struct  Tnode264794  {
Ttype264832* typ;
Tlineinfo186336 info;
Tnodeflag264427Set flags;
Tnodekind264020 kind;
union{
struct {NI64 intval;
} S1;
struct {NF floatval;
} S2;
struct {NimStringDesc* strval;
} S3;
struct {Tsym264826* sym;
} S4;
struct {Tident194012* ident;
} S5;
struct {Tnodeseq264788* sons;
} S6;
} kindU;
NimStringDesc* comment;
};
typedef NU8 Tsymflag264184;
typedef NU16 Tmsgkind186002;
typedef NimStringDesc* TY188153[2];
typedef Tsym264826* TY315315[1];
struct  Intset241031  {
NI counter;
NI max;
Trunk241027* head;
Trunkseq241029* data;
};
struct  Gcstack50416  {
Gcstack50416* prev;
Gcstack50416* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk30038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {
  Basechunk30038 Sup;
Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30080  {
NI size;
NI acc;
Llchunk30080* next;
};
struct  Bigchunk30042  {
  Basechunk30038 Sup;
Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
typedef NI TY30019[8];
struct  Trunk30010  {
Trunk30010* next;
NI key;
TY30019 bits;
};
typedef Avlnode30084* TY30091[2];
struct  Avlnode30084  {
TY30091 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47913  {
Pagedesc47913* next;
NI key;
TY30019 bits;
};
struct  Tscope264820  {
NI depthlevel;
Tstrtable264798 symbols;
Tscope264820* parent;
};
struct  Ropeobj173006  {
  TNimObject Sup;
Ropeobj173006* left;
Ropeobj173006* right;
NI length;
NimStringDesc* data;
};
struct  Tlistentry141010  {
  TNimObject Sup;
Tlistentry141010* prev;
Tlistentry141010* next;
};
typedef NU8 Tlibkind264810;
struct  Tlib264812  {
  Tlistentry141010 Sup;
Tlibkind264810 kind;
NIM_BOOL generated;
NIM_BOOL isoverriden;
Ropeobj173006* name;
Tnode264794* path;
};
struct  Trunk241027  {
Trunk241027* next;
NI key;
TY30019 bits;
};
struct  Freecell30030  {
Freecell30030* next;
NI zerofield;
};
struct  Tinstantiation264816  {
Tsym264826* sym;
Ttypeseq264828* concretetypes;
TY264917* usedby;
NI compilesid;
};
struct Tsymseq264796 {
  TGenericSeq Sup;
  Tsym264826* data[SEQ_DECL_SIZE];
};
struct TY400226 {
  TGenericSeq Sup;
  TY400227 data[SEQ_DECL_SIZE];
};
struct Ttypeseq264828 {
  TGenericSeq Sup;
  Ttype264832* data[SEQ_DECL_SIZE];
};
struct TY264927 {
  TGenericSeq Sup;
  Tinstantiation264816* data[SEQ_DECL_SIZE];
};
struct Tnodeseq264788 {
  TGenericSeq Sup;
  Tnode264794* data[SEQ_DECL_SIZE];
};
struct Trunkseq241029 {
  TGenericSeq Sup;
  Trunk241027* data[SEQ_DECL_SIZE];
};
struct TY264917 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, TMP1108)(void* p, NI op);
N_NIMCALL(void, TMP1109)();
N_NIMCALL(void, nimRegisterGlobalMarker)(Globalmarkerproc56402 markerproc0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p0);
static N_INLINE(Cell47905*, usrtocell_52040_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_53201_1689653243)(Cell47905* c0);
N_NOINLINE(void, addzct_52017_1689653243)(Cellseq47921* s0, Cell47905* c0);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ0, NI len0);
N_NIMCALL(Methodresult400249, samemethodbucket_400253_3853300031)(Tsym264826* a0, Tsym264826* b0);
N_NIMCALL(NI, sonslen_267327_850551059)(Ttype264832* n0);
N_NIMCALL(NIM_BOOL, sametypeornil_295839_3876443242)(Ttype264832* a0, Ttype264832* b0, Ttypecmpflag295625Set flags0);
N_NIMCALL(Ttype264832*, skiptypes_268113_850551059)(Ttype264832* t0, Ttypekind264244Set kinds0);
N_NIMCALL(Ttype264832*, lastson_267377_850551059)(Ttype264832* n0);
N_NIMCALL(NIM_BOOL, sametype_295829_3876443242)(Ttype264832* a0, Ttype264832* b0, Ttypecmpflag295625Set flags0);
N_NIMCALL(NI, inheritancediff_297642_3876443242)(Ttype264832* a0, Ttype264832* b0);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq0, NI elemsize0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
N_NIMCALL(void, attachdispatcher_400362_3853300031)(Tsym264826* s0, Tnode264794* dispatcher0);
static N_INLINE(NI, len_265080_850551059)(Tnode264794* n0);
N_NIMCALL(void, add_265135_850551059)(Tnode264794* father0, Tnode264794* son0);
N_NIMCALL(Tnode264794*, lastson_267364_850551059)(Tnode264794* n0);
N_NIMCALL(void, fixupdispatcher_400466_3853300031)(Tsym264826* meth0, Tsym264826* disp0);
N_NIMCALL(NI, sonslen_267351_850551059)(Tnode264794* n0);
N_NIMCALL(Tnode264794*, copytree_268822_850551059)(Tnode264794* src0);
N_NIMCALL(void, message_191095_155036129)(Tlineinfo186336 info0, Tmsgkind186002 msg0, NimStringDesc* arg0);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr0, NimStringDesc** a0, NI a0Len0);
N_NIMCALL(NimStringDesc*, HEX24_267069_850551059)(NI16 x0);
N_NIMCALL(void, checkmethodeffects_372842_422813333)(Tsym264826* disp0, Tsym264826* branch0);
N_NIMCALL(void, localerror_191085_155036129)(Tlineinfo186336 info0, NimStringDesc* arg0);
N_NIMCALL(void*, newSeq)(TNimType* typ0, NI len0);
N_NIMCALL(Tsym264826*, createdispatcher_400397_3853300031)(Tsym264826* s0);
N_NIMCALL(Tsym264826*, copysym_267601_850551059)(Tsym264826* s0, NIM_BOOL keepid0);
N_NIMCALL(Ttype264832*, copytype_267470_850551059)(Ttype264832* t0, Tsym264826* owner0, NIM_BOOL keepid0);
N_NIMCALL(void, addson_266807_850551059)(Tnode264794* father0, Tnode264794* son0);
N_NIMCALL(Tnode264794*, newsymnode_266234_850551059)(Tsym264826* sym0);
N_NIMCALL(void, genericSeqAssign)(void* dest0, void* src_86004_1689653243, TNimType* mt0);
N_NIMCALL(void, internalerror_191100_155036129)(Tlineinfo186336 info0, NimStringDesc* errmsg0);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
N_NIMCALL(NimStringDesc*, HEX24_187431_155036129)(Tlineinfo186336 info0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
N_NIMCALL(Tnode264794*, genconv_400005_3853300031)(Tnode264794* n0, Ttype264832* d0, NIM_BOOL downcast0);
N_NIMCALL(Tnode264794*, newnodeit_266801_850551059)(Tnodekind264020 kind0, Tlineinfo186336 info0, Ttype264832* typ0);
N_NIMCALL(Tnode264794*, newnode_265401_850551059)(Tnodekind264020 kind0);
N_NIMCALL(void, initintset_241885_2627731572)(Intset241031* Result);
N_NOINLINE(void, chckNil)(void* p0);
N_NIMCALL(NIM_BOOL, relevantcol_400896_3853300031)(Tsymseq264796* methods0, NI col0);
N_NIMCALL(void, incl_241832_2627731572)(Intset241031* s0, NI key0);
N_NIMCALL(void, sortbucket_400970_3853300031)(Tsymseq264796** a0, Intset241031* relevantcols0);
N_NIMCALL(NI, cmpsignatures_400934_3853300031)(Tsym264826* a0, Tsym264826* b0, Intset241031* relevantcols0);
N_NIMCALL(NIM_BOOL, contains_241811_2627731572)(Intset241031* s0, NI key0);
N_NIMCALL(Tsym264826*, gendispatcher_401010_3853300031)(Tsymseq264796* methods0, Intset241031* relevantcols0);
N_NIMCALL(Tnode264794*, newnodei_266248_850551059)(Tnodekind264020 kind0, Tlineinfo186336 info0);
N_NIMCALL(Tsym264826*, getsyssym_309041_3937434831)(NimStringDesc* name0);
N_NIMCALL(Ttype264832*, getsystype_309153_3937434831)(Ttypekind264244 kind0);
STRING_LITERAL(TMP3609, "method has lock level $1, but another method has $2", 51);
STRING_LITERAL(TMP3617, "method is not a base", 20);
STRING_LITERAL(TMP3618, "no method dispatcher found", 26);
STRING_LITERAL(TMP3619, "invalid declaration order; cannot attach \'", 42);
STRING_LITERAL(TMP3620, "\' to method defined here: ", 26);
STRING_LITERAL(TMP3621, "", 0);
STRING_LITERAL(TMP3622, "cgmeth.genConv: no upcast allowed", 33);
STRING_LITERAL(TMP3623, "cgmeth.genConv: no downcast allowed", 35);
STRING_LITERAL(TMP4663, "and", 3);
STRING_LITERAL(TMP4664, "of", 2);
TY400226* gmethods_400246_3853300031;
TNimType NTI400227; /* tuple[methods: TSymSeq, dispatcher: PSym] */
extern TNimType NTI264796; /* TSymSeq */
extern TNimType NTI264792; /* PSym */
TNimType NTI400226; /* seq[tuple[methods: TSymSeq, dispatcher: PSym]] */
extern Gcheap50418 gch_50458_1689653243;
extern Tnode264794* emptynode_265801_850551059;
N_NIMCALL(void, TMP1108)(void* p, NI op) {
	TY400226* a;
	NI LOC1;
	a = (TY400226*)p;
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field0, op);
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}
N_NIMCALL(void, TMP1109)() {
	nimGCvisit((void*)gmethods_400246_3853300031, 0);
}

static N_INLINE(Cell47905*, usrtocell_52040_1689653243)(void* usr0) {
	Cell47905* result0;
	result0 = (Cell47905*)0;
	result0 = ((Cell47905*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell47905))))));
	return result0;
}

static N_INLINE(void, rtladdzct_53201_1689653243)(Cell47905* c0) {
	addzct_52017_1689653243((&gch_50458_1689653243.zct), c0);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p0) {
	Cell47905* c0;
	c0 = usrtocell_52040_1689653243(p0);
	{
		(*c0).refcount -= ((NI) 8);
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_53201_1689653243(c0);
	}
	LA3: ;
}

N_NIMCALL(Methodresult400249, samemethodbucket_400253_3853300031)(Tsym264826* a0, Tsym264826* b0) {
	Methodresult400249 result0;
{	result0 = (Methodresult400249)0;
	{
		if (!!(((*(*a0).name).Sup.id == (*(*b0).name).Sup.id))) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	{
		NI LOC7;
		NI LOC8;
		LOC7 = (NI)0;
		LOC7 = sonslen_267327_850551059((*a0).typ);
		LOC8 = (NI)0;
		LOC8 = sonslen_267327_850551059((*b0).typ);
		if (!!((LOC7 == LOC8))) goto LA9;
		goto BeforeRet;
	}
	LA9: ;
	{
		NIM_BOOL LOC13;
		LOC13 = (NIM_BOOL)0;
		LOC13 = sametypeornil_295839_3876443242((*(*a0).typ).sons->data[((NI) 0)], (*(*b0).typ).sons->data[((NI) 0)], 0);
		if (!!(LOC13)) goto LA14;
		goto BeforeRet;
	}
	LA14: ;
	{
		NI i_400276_3853300031;
		NI HEX3Atmp_400355_3853300031;
		NI LOC17;
		NI res_400358_3853300031;
		i_400276_3853300031 = (NI)0;
		HEX3Atmp_400355_3853300031 = (NI)0;
		LOC17 = (NI)0;
		LOC17 = sonslen_267327_850551059((*a0).typ);
		HEX3Atmp_400355_3853300031 = (NI)(LOC17 - ((NI) 1));
		res_400358_3853300031 = ((NI) 1);
		{
			while (1) {
				Ttype264832* aa0;
				Ttype264832* bb0;
				if (!(res_400358_3853300031 <= HEX3Atmp_400355_3853300031)) goto LA19;
				i_400276_3853300031 = res_400358_3853300031;
				aa0 = (*(*a0).typ).sons->data[i_400276_3853300031];
				bb0 = (*(*b0).typ).sons->data[i_400276_3853300031];
				{
					while (1) {
						aa0 = skiptypes_268113_850551059(aa0, 2048);
						bb0 = skiptypes_268113_850551059(bb0, 2048);
						{
							NIM_BOOL LOC24;
							LOC24 = (NIM_BOOL)0;
							LOC24 = ((*aa0).kind == (*bb0).kind);
							if (!(LOC24)) goto LA25;
							LOC24 = ((14680064 &((NU64)1<<((NU)((*aa0).kind)&63U)))!=0);
							LA25: ;
							if (!LOC24) goto LA26;
							aa0 = lastson_267377_850551059(aa0);
							bb0 = lastson_267377_850551059(bb0);
						}
						goto LA22;
						LA26: ;
						{
							goto LA20;
						}
						LA22: ;
					}
				} LA20: ;
				{
					NIM_BOOL LOC31;
					LOC31 = (NIM_BOOL)0;
					LOC31 = sametype_295829_3876443242(aa0, bb0, 0);
					if (!LOC31) goto LA32;
					{
						NIM_BOOL LOC36;
						LOC36 = (NIM_BOOL)0;
						LOC36 = ((*aa0).kind == ((Ttypekind264244) 17));
						if (!(LOC36)) goto LA37;
						LOC36 = !((result0 == ((Methodresult400249) 1)));
						LA37: ;
						if (!LOC36) goto LA38;
						result0 = ((Methodresult400249) 2);
					}
					LA38: ;
				}
				goto LA29;
				LA32: ;
				{
					NIM_BOOL LOC41;
					NI diff0;
					LOC41 = (NIM_BOOL)0;
					LOC41 = ((*aa0).kind == ((Ttypekind264244) 17));
					if (!(LOC41)) goto LA42;
					LOC41 = ((*bb0).kind == ((Ttypekind264244) 17));
					LA42: ;
					if (!LOC41) goto LA43;
					diff0 = inheritancediff_297642_3876443242(bb0, aa0);
					{
						if (!(diff0 < ((NI) 0))) goto LA47;
						{
							if (!!((result0 == ((Methodresult400249) 1)))) goto LA51;
							result0 = ((Methodresult400249) 2);
						}
						LA51: ;
					}
					goto LA45;
					LA47: ;
					{
						if (!!((diff0 == ((NI) IL64(9223372036854775807))))) goto LA54;
						result0 = ((Methodresult400249) 1);
					}
					goto LA45;
					LA54: ;
					LA45: ;
				}
				goto LA29;
				LA43: ;
				{
					result0 = ((Methodresult400249) 0);
					goto BeforeRet;
				}
				LA29: ;
				res_400358_3853300031 += ((NI) 1);
			} LA19: ;
		}
	}
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	{
		Cell47905* c0;
		if (!!((src0 == NIM_NIL))) goto LA3;
		c0 = usrtocell_52040_1689653243(src0);
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	{
		Cell47905* c0;
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		c0 = usrtocell_52040_1689653243((*dest0));
		{
			(*c0).refcount -= ((NI) 8);
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			rtladdzct_53201_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	(*dest0) = src0;
}

static N_INLINE(NI, len_265080_850551059)(Tnode264794* n0) {
	NI result0;
	result0 = (NI)0;
	{
		if (!(*n0).kindU.S6.sons == 0) goto LA3;
		result0 = ((NI) 0);
	}
	goto LA1;
	LA3: ;
	{
		result0 = ((*n0).kindU.S6.sons ? (*n0).kindU.S6.sons->Sup.len : 0);
	}
	LA1: ;
	return result0;
}

N_NIMCALL(void, attachdispatcher_400362_3853300031)(Tsym264826* s0, Tnode264794* dispatcher0) {
	NI L0;
	NI LOC1;
	Tnode264794* x0;
	LOC1 = (NI)0;
	LOC1 = len_265080_850551059((*s0).ast);
	L0 = (NI)(LOC1 - ((NI) 1));
	x0 = (*(*s0).ast).kindU.S6.sons->data[L0];
	{
		NIM_BOOL LOC4;
		LOC4 = (NIM_BOOL)0;
		LOC4 = ((*x0).kind == ((Tnodekind264020) 3));
		if (!(LOC4)) goto LA5;
		LOC4 = (((*(*x0).kindU.S4.sym).flags &(1U<<((NU)(((Tsymflag264184) 25))&31U)))!=0);
		LA5: ;
		if (!LOC4) goto LA6;
		asgnRefNoCycle((void**) (&(*(*s0).ast).kindU.S6.sons->data[L0]), dispatcher0);
	}
	goto LA2;
	LA6: ;
	{
		add_265135_850551059((*s0).ast, dispatcher0);
	}
	LA2: ;
}

N_NIMCALL(void, fixupdispatcher_400466_3853300031)(Tsym264826* meth0, Tsym264826* disp0) {
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NI LOC5;
		NI LOC7;
		LOC3 = (NIM_BOOL)0;
		LOC4 = (NIM_BOOL)0;
		LOC5 = (NI)0;
		LOC5 = sonslen_267351_850551059((*disp0).ast);
		LOC4 = (((NI) 7) < LOC5);
		if (!(LOC4)) goto LA6;
		LOC7 = (NI)0;
		LOC7 = sonslen_267351_850551059((*meth0).ast);
		LOC4 = (((NI) 7) < LOC7);
		LA6: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA8;
		LOC3 = ((*(*disp0).ast).kindU.S6.sons->data[((NI) 7)] == emptynode_265801_850551059);
		LA8: ;
		if (!LOC3) goto LA9;
		asgnRefNoCycle((void**) (&(*(*disp0).ast).kindU.S6.sons->data[((NI) 7)]), copytree_268822_850551059((*(*meth0).ast).kindU.S6.sons->data[((NI) 7)]));
	}
	LA9: ;
	{
		if (!((*(*disp0).typ).locklevel == ((NI16) -1))) goto LA13;
		(*(*disp0).typ).locklevel = (*(*meth0).typ).locklevel;
	}
	goto LA11;
	LA13: ;
	{
		NIM_BOOL LOC16;
		TY188153 LOC20;
		NimStringDesc* LOC21;
		LOC16 = (NIM_BOOL)0;
		LOC16 = !(((*(*meth0).typ).locklevel == ((NI16) -1)));
		if (!(LOC16)) goto LA17;
		LOC16 = !(((*(*meth0).typ).locklevel == (*(*disp0).typ).locklevel));
		LA17: ;
		if (!LOC16) goto LA18;
		memset((void*)LOC20, 0, sizeof(LOC20));
		LOC20[0] = HEX24_267069_850551059((*(*meth0).typ).locklevel);
		LOC20[1] = HEX24_267069_850551059((*(*disp0).typ).locklevel);
		LOC21 = (NimStringDesc*)0;
		LOC21 = nsuFormatOpenArray(((NimStringDesc*) &TMP3609), LOC20, 2);
		message_191095_155036129((*meth0).info, ((Tmsgkind186002) 265), LOC21);
		{
			if (!((*(*disp0).typ).locklevel < (*(*meth0).typ).locklevel)) goto LA24;
			(*(*disp0).typ).locklevel = (*(*meth0).typ).locklevel;
		}
		LA24: ;
	}
	goto LA11;
	LA18: ;
	LA11: ;
}

N_NIMCALL(Tsym264826*, createdispatcher_400397_3853300031)(Tsym264826* s0) {
	Tsym264826* result0;
	Tsym264826* disp0;
	Tnode264794* LOC15;
	Tnode264794* LOC16;
{	result0 = (Tsym264826*)0;
	disp0 = copysym_267601_850551059(s0, NIM_FALSE);
	(*disp0).flags |= ((NU32)1)<<((((Tsymflag264184) 25))%(sizeof(NU32)*8));
	(*disp0).flags &= ~(((NU32)1) << ((((Tsymflag264184) 1)) % (sizeof(NU32)*8)));
	asgnRefNoCycle((void**) (&(*disp0).typ), copytype_267470_850551059((*disp0).typ, (*(*disp0).typ).owner, NIM_FALSE));
	{
		if (!((*(*disp0).typ).callconv == ((Tcallingconvention264002) 5))) goto LA3;
		(*(*disp0).typ).callconv = ((Tcallingconvention264002) 0);
	}
	LA3: ;
	asgnRefNoCycle((void**) (&(*disp0).ast), copytree_268822_850551059((*s0).ast));
	asgnRefNoCycle((void**) (&(*(*disp0).ast).kindU.S6.sons->data[((NI) 6)]), emptynode_265801_850551059);
	asgnRefNoCycle((void**) (&(*disp0).loc.r), NIM_NIL);
	{
		if (!!(((*(*s0).typ).sons->data[((NI) 0)] == NIM_NIL))) goto LA7;
		{
			NI LOC11;
			LOC11 = (NI)0;
			LOC11 = sonslen_267351_850551059((*disp0).ast);
			if (!(((NI) 7) < LOC11)) goto LA12;
			asgnRefNoCycle((void**) (&(*(*(*disp0).ast).kindU.S6.sons->data[((NI) 7)]).kindU.S4.sym), copysym_267601_850551059((*(*(*s0).ast).kindU.S6.sons->data[((NI) 7)]).kindU.S4.sym, NIM_FALSE));
		}
		goto LA9;
		LA12: ;
		{
			addson_266807_850551059((*disp0).ast, emptynode_265801_850551059);
		}
		LA9: ;
	}
	LA7: ;
	LOC15 = (Tnode264794*)0;
	LOC15 = newsymnode_266234_850551059(disp0);
	attachdispatcher_400362_3853300031(s0, LOC15);
	LOC16 = (Tnode264794*)0;
	LOC16 = newsymnode_266234_850551059(disp0);
	attachdispatcher_400362_3853300031(disp0, LOC16);
	result0 = disp0;
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	memcpy(((NCSTRING) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((NCSTRING) ((*src0).data)), (NI)((*src0).Sup.len + ((NI) 1)));
	(*dest0).Sup.len += (*src0).Sup.len;
}

N_NIMCALL(void, methoddef_400628_3853300031)(Tsym264826* s0, NIM_BOOL fromcache0) {
	NI L0;
	Tsym264826* witness0;
	TY400227 LOC19;
	TY315315 LOC20;
{	L0 = (gmethods_400246_3853300031 ? gmethods_400246_3853300031->Sup.len : 0);
	witness0 = (Tsym264826*)0;
	{
		NI i_400653_3853300031;
		NI HEX3Atmp_400889_3853300031;
		NI res_400892_3853300031;
		i_400653_3853300031 = (NI)0;
		HEX3Atmp_400889_3853300031 = (NI)0;
		HEX3Atmp_400889_3853300031 = (NI)(L0 - ((NI) 1));
		res_400892_3853300031 = ((NI) 0);
		{
			while (1) {
				Tsym264826* disp0;
				Methodresult400249 LOC4;
				if (!(res_400892_3853300031 <= HEX3Atmp_400889_3853300031)) goto LA3;
				i_400653_3853300031 = res_400892_3853300031;
				disp0 = gmethods_400246_3853300031->data[i_400653_3853300031].Field1;
				LOC4 = (Methodresult400249)0;
				LOC4 = samemethodbucket_400253_3853300031(disp0, s0);
				switch (LOC4) {
				case ((Methodresult400249) 2):
				{
					Tnode264794* LOC6;
					gmethods_400246_3853300031->data[i_400653_3853300031].Field0 = (Tsymseq264796*) incrSeqV2(&(gmethods_400246_3853300031->data[i_400653_3853300031].Field0)->Sup, sizeof(Tsym264826*));
					asgnRefNoCycle((void**) (&gmethods_400246_3853300031->data[i_400653_3853300031].Field0->data[gmethods_400246_3853300031->data[i_400653_3853300031].Field0->Sup.len]), s0);
					++gmethods_400246_3853300031->data[i_400653_3853300031].Field0->Sup.len;
					LOC6 = (Tnode264794*)0;
					LOC6 = lastson_267364_850551059((*disp0).ast);
					attachdispatcher_400362_3853300031(s0, LOC6);
					fixupdispatcher_400466_3853300031(s0, disp0);
					checkmethodeffects_372842_422813333(disp0, s0);
					{
						NIM_BOOL LOC9;
						LOC9 = (NIM_BOOL)0;
						LOC9 = (((*s0).flags &(1U<<((NU)(((Tsymflag264184) 18))&31U)))!=0);
						if (!(LOC9)) goto LA10;
						LOC9 = !((gmethods_400246_3853300031->data[i_400653_3853300031].Field0->data[((NI) 0)] == s0));
						LA10: ;
						if (!LOC9) goto LA11;
						localerror_191085_155036129((*s0).info, ((NimStringDesc*) &TMP3617));
					}
					LA11: ;
					goto BeforeRet;
				}
				break;
				case ((Methodresult400249) 0):
				{
				}
				break;
				case ((Methodresult400249) 1):
				{
					{
						if (!witness0 == 0) goto LA17;
						witness0 = gmethods_400246_3853300031->data[i_400653_3853300031].Field0->data[((NI) 0)];
					}
					LA17: ;
				}
				break;
				}
				res_400892_3853300031 += ((NI) 1);
			} LA3: ;
		}
	}
	memset((void*)(&LOC19), 0, sizeof(LOC19));
	LOC19.Field0 = (Tsymseq264796*) newSeq((&NTI264796), 1);
	memset((void*)LOC20, 0, sizeof(LOC20));
	LOC20[0] = s0;
	asgnRefNoCycle((void**) (&LOC19.Field0->data[0]), LOC20[0]);
	LOC19.Field1 = createdispatcher_400397_3853300031(s0);
	gmethods_400246_3853300031 = (TY400226*) incrSeqV2(&(gmethods_400246_3853300031)->Sup, sizeof(TY400227));
	genericSeqAssign((&gmethods_400246_3853300031->data[gmethods_400246_3853300031->Sup.len].Field0), LOC19.Field0, (&NTI264796));
	asgnRefNoCycle((void**) (&gmethods_400246_3853300031->data[gmethods_400246_3853300031->Sup.len].Field1), LOC19.Field1);
	++gmethods_400246_3853300031->Sup.len;
	{
		if (!fromcache0) goto LA23;
		internalerror_191100_155036129((*s0).info, ((NimStringDesc*) &TMP3618));
	}
	LA23: ;
	{
		NimStringDesc* LOC29;
		NimStringDesc* LOC30;
		if (!!((witness0 == NIM_NIL))) goto LA27;
		LOC29 = (NimStringDesc*)0;
		LOC30 = (NimStringDesc*)0;
		LOC30 = HEX24_187431_155036129((*witness0).info);
		LOC29 = rawNewString((*(*s0).name).s->Sup.len + LOC30->Sup.len + 68);
appendString(LOC29, ((NimStringDesc*) &TMP3619));
appendString(LOC29, (*(*s0).name).s);
appendString(LOC29, ((NimStringDesc*) &TMP3620));
appendString(LOC29, LOC30);
		localerror_191085_155036129((*s0).info, LOC29);
	}
	goto LA25;
	LA27: ;
	{
		if (!!((((*s0).flags &(1U<<((NU)(((Tsymflag264184) 18))&31U)))!=0))) goto LA32;
		message_191095_155036129((*s0).info, ((Tmsgkind186002) 252), ((NimStringDesc*) &TMP3621));
	}
	goto LA25;
	LA32: ;
	LA25: ;
	}BeforeRet: ;
}

N_NIMCALL(Tnode264794*, genconv_400005_3853300031)(Tnode264794* n0, Ttype264832* d0, NIM_BOOL downcast0) {
	Tnode264794* result0;
	Ttype264832* dest0;
	Ttype264832* source0;
	result0 = (Tnode264794*)0;
	dest0 = skiptypes_268113_850551059(d0, IL64(211106247256320));
	source0 = skiptypes_268113_850551059((*n0).typ, IL64(211106247256320));
	{
		NIM_BOOL LOC3;
		NI diff0;
		LOC3 = (NIM_BOOL)0;
		LOC3 = ((*source0).kind == ((Ttypekind264244) 17));
		if (!(LOC3)) goto LA4;
		LOC3 = ((*dest0).kind == ((Ttypekind264244) 17));
		LA4: ;
		if (!LOC3) goto LA5;
		diff0 = inheritancediff_297642_3876443242(dest0, source0);
		{
			if (!(diff0 == ((NI) IL64(9223372036854775807)))) goto LA9;
			result0 = n0;
		}
		goto LA7;
		LA9: ;
		{
			if (!(diff0 < ((NI) 0))) goto LA12;
			result0 = newnodeit_266801_850551059(((Tnodekind264020) 67), (*n0).info, d0);
			addson_266807_850551059(result0, n0);
			{
				if (!downcast0) goto LA16;
				internalerror_191100_155036129((*n0).info, ((NimStringDesc*) &TMP3622));
			}
			LA16: ;
		}
		goto LA7;
		LA12: ;
		{
			if (!(((NI) 0) < diff0)) goto LA19;
			result0 = newnodeit_266801_850551059(((Tnodekind264020) 66), (*n0).info, d0);
			addson_266807_850551059(result0, n0);
			{
				if (!!(downcast0)) goto LA23;
				internalerror_191100_155036129((*n0).info, ((NimStringDesc*) &TMP3623));
			}
			LA23: ;
		}
		goto LA7;
		LA19: ;
		{
			result0 = n0;
		}
		LA7: ;
	}
	goto LA1;
	LA5: ;
	{
		result0 = n0;
	}
	LA1: ;
	return result0;
}

N_NIMCALL(Tnode264794*, methodcall_400036_3853300031)(Tnode264794* n0) {
	Tnode264794* result0;
	Tsym264826* disp0;
	Tnode264794* LOC1;
	result0 = (Tnode264794*)0;
	result0 = n0;
	LOC1 = (Tnode264794*)0;
	LOC1 = lastson_267364_850551059((*(*(*result0).kindU.S6.sons->data[((NI) 0)]).kindU.S4.sym).ast);
	disp0 = (*LOC1).kindU.S4.sym;
	asgnRefNoCycle((void**) (&(*(*result0).kindU.S6.sons->data[((NI) 0)]).kindU.S4.sym), disp0);
	{
		NI i_400214_3853300031;
		NI HEX3Atmp_400219_3853300031;
		NI LOC3;
		NI res_400222_3853300031;
		i_400214_3853300031 = (NI)0;
		HEX3Atmp_400219_3853300031 = (NI)0;
		LOC3 = (NI)0;
		LOC3 = sonslen_267351_850551059(result0);
		HEX3Atmp_400219_3853300031 = (NI)(LOC3 - ((NI) 1));
		res_400222_3853300031 = ((NI) 1);
		{
			while (1) {
				if (!(res_400222_3853300031 <= HEX3Atmp_400219_3853300031)) goto LA5;
				i_400214_3853300031 = res_400222_3853300031;
				asgnRefNoCycle((void**) (&(*result0).kindU.S6.sons->data[i_400214_3853300031]), genconv_400005_3853300031((*result0).kindU.S6.sons->data[i_400214_3853300031], (*(*disp0).typ).sons->data[i_400214_3853300031], NIM_TRUE));
				res_400222_3853300031 += ((NI) 1);
			} LA5: ;
		}
	}
	return result0;
}

N_NIMCALL(NIM_BOOL, relevantcol_400896_3853300031)(Tsymseq264796* methods0, NI col0) {
	NIM_BOOL result0;
	Ttype264832* t0;
{	result0 = (NIM_BOOL)0;
	t0 = skiptypes_268113_850551059((*(*methods0->data[((NI) 0)]).typ).sons->data[col0], IL64(211106247215360));
	{
		if (!((*t0).kind == ((Ttypekind264244) 17))) goto LA3;
		{
			NI i_400923_3853300031;
			NI HEX3Atmp_400927_3853300031;
			NI res_400930_3853300031;
			i_400923_3853300031 = (NI)0;
			HEX3Atmp_400927_3853300031 = (NI)0;
			HEX3Atmp_400927_3853300031 = (methods0 ? (methods0->Sup.len-1) : -1);
			res_400930_3853300031 = ((NI) 1);
			{
				while (1) {
					Ttype264832* t20;
					if (!(res_400930_3853300031 <= HEX3Atmp_400927_3853300031)) goto LA7;
					i_400923_3853300031 = res_400930_3853300031;
					t20 = skiptypes_268113_850551059((*(*methods0->data[i_400923_3853300031]).typ).sons->data[col0], IL64(211106247215360));
					{
						NIM_BOOL LOC10;
						LOC10 = (NIM_BOOL)0;
						LOC10 = sametype_295829_3876443242(t20, t0, 0);
						if (!!(LOC10)) goto LA11;
						result0 = NIM_TRUE;
						goto BeforeRet;
					}
					LA11: ;
					res_400930_3853300031 += ((NI) 1);
				} LA7: ;
			}
		}
	}
	LA3: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, cmpsignatures_400934_3853300031)(Tsym264826* a0, Tsym264826* b0, Intset241031* relevantcols0) {
	NI result0;
{	result0 = (NI)0;
	{
		NI col_400952_3853300031;
		NI HEX3Atmp_400963_3853300031;
		NI LOC2;
		NI res_400966_3853300031;
		col_400952_3853300031 = (NI)0;
		HEX3Atmp_400963_3853300031 = (NI)0;
		LOC2 = (NI)0;
		LOC2 = sonslen_267327_850551059((*a0).typ);
		HEX3Atmp_400963_3853300031 = (NI)(LOC2 - ((NI) 1));
		res_400966_3853300031 = ((NI) 1);
		{
			while (1) {
				if (!(res_400966_3853300031 <= HEX3Atmp_400963_3853300031)) goto LA4;
				col_400952_3853300031 = res_400966_3853300031;
				{
					NIM_BOOL LOC7;
					Ttype264832* aa0;
					Ttype264832* bb0;
					NI d0;
					LOC7 = (NIM_BOOL)0;
					LOC7 = contains_241811_2627731572(relevantcols0, col_400952_3853300031);
					if (!LOC7) goto LA8;
					aa0 = skiptypes_268113_850551059((*(*a0).typ).sons->data[col_400952_3853300031], IL64(211106247215360));
					bb0 = skiptypes_268113_850551059((*(*b0).typ).sons->data[col_400952_3853300031], IL64(211106247215360));
					d0 = inheritancediff_297642_3876443242(aa0, bb0);
					{
						if (!!((d0 == ((NI) IL64(9223372036854775807))))) goto LA12;
						result0 = d0;
						goto BeforeRet;
					}
					LA12: ;
				}
				LA8: ;
				res_400966_3853300031 += ((NI) 1);
			} LA4: ;
		}
	}
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, sortbucket_400970_3853300031)(Tsymseq264796** a0, Intset241031* relevantcols0) {
	NI n0;
	NI h0;
	n0 = ((*a0) ? (*a0)->Sup.len : 0);
	h0 = ((NI) 1);
	{
		while (1) {
			h0 = (NI)((NI)(((NI) 3) * h0) + ((NI) 1));
			{
				if (!(n0 < h0)) goto LA5;
				goto LA1;
			}
			LA5: ;
		}
	} LA1: ;
	{
		while (1) {
			h0 = (NI)(h0 / ((NI) 3));
			{
				NI i_400996_3853300031;
				NI HEX3Atmp_401003_3853300031;
				NI res_401006_3853300031;
				i_400996_3853300031 = (NI)0;
				HEX3Atmp_401003_3853300031 = (NI)0;
				HEX3Atmp_401003_3853300031 = (NI)(n0 - ((NI) 1));
				res_401006_3853300031 = h0;
				{
					while (1) {
						Tsym264826* v0;
						NI j0;
						if (!(res_401006_3853300031 <= HEX3Atmp_401003_3853300031)) goto LA11;
						i_400996_3853300031 = res_401006_3853300031;
						v0 = (*a0)->data[i_400996_3853300031];
						j0 = i_400996_3853300031;
						{
							while (1) {
								NI LOC14;
								LOC14 = (NI)0;
								LOC14 = cmpsignatures_400934_3853300031((*a0)->data[(NI)(j0 - h0)], v0, relevantcols0);
								if (!(((NI) 0) <= LOC14)) goto LA13;
								asgnRefNoCycle((void**) (&(*a0)->data[j0]), (*a0)->data[(NI)(j0 - h0)]);
								j0 = (NI)(j0 - h0);
								{
									if (!(j0 < h0)) goto LA17;
									goto LA12;
								}
								LA17: ;
							} LA13: ;
						} LA12: ;
						asgnRefNoCycle((void**) (&(*a0)->data[j0]), v0);
						res_401006_3853300031 += ((NI) 1);
					} LA11: ;
				}
			}
			{
				if (!(h0 == ((NI) 1))) goto LA21;
				goto LA7;
			}
			LA21: ;
		}
	} LA7: ;
}

N_NIMCALL(Tsym264826*, gendispatcher_401010_3853300031)(Tsymseq264796* methods0, Intset241031* relevantcols0) {
	Tsym264826* result0;
	Tsym264826* base0;
	Tnode264794* LOC1;
	NI paramlen0;
	Tnode264794* disp0;
	Tsym264826* ands0;
	Tsym264826* iss0;
	result0 = (Tsym264826*)0;
	LOC1 = (Tnode264794*)0;
	LOC1 = lastson_267364_850551059((*methods0->data[((NI) 0)]).ast);
	base0 = (*LOC1).kindU.S4.sym;
	result0 = base0;
	paramlen0 = sonslen_267327_850551059((*base0).typ);
	disp0 = newnodei_266248_850551059(((Tnodekind264020) 92), (*base0).info);
	ands0 = getsyssym_309041_3937434831(((NimStringDesc*) &TMP4663));
	iss0 = getsyssym_309041_3937434831(((NimStringDesc*) &TMP4664));
	{
		NI meth_401035_3853300031;
		NI HEX3Atmp_401144_3853300031;
		NI res_401147_3853300031;
		meth_401035_3853300031 = (NI)0;
		HEX3Atmp_401144_3853300031 = (NI)0;
		HEX3Atmp_401144_3853300031 = (methods0 ? (methods0->Sup.len-1) : -1);
		res_401147_3853300031 = ((NI) 0);
		{
			while (1) {
				Tsym264826* curr0;
				Tnode264794* cond0;
				Tnode264794* call0;
				Tnode264794* LOC24;
				Tnode264794* ret0;
				if (!(res_401147_3853300031 <= HEX3Atmp_401144_3853300031)) goto LA4;
				meth_401035_3853300031 = res_401147_3853300031;
				curr0 = methods0->data[meth_401035_3853300031];
				cond0 = NIM_NIL;
				{
					NI col_401049_3853300031;
					NI HEX3Atmp_401128_3853300031;
					NI res_401131_3853300031;
					col_401049_3853300031 = (NI)0;
					HEX3Atmp_401128_3853300031 = (NI)0;
					HEX3Atmp_401128_3853300031 = (NI)(paramlen0 - ((NI) 1));
					res_401131_3853300031 = ((NI) 1);
					{
						while (1) {
							if (!(res_401131_3853300031 <= HEX3Atmp_401128_3853300031)) goto LA7;
							col_401049_3853300031 = res_401131_3853300031;
							{
								NIM_BOOL LOC10;
								Tnode264794* isn0;
								Ttype264832* LOC13;
								Tnode264794* LOC14;
								Tnode264794* LOC15;
								Tnode264794* LOC16;
								LOC10 = (NIM_BOOL)0;
								LOC10 = contains_241811_2627731572(relevantcols0, col_401049_3853300031);
								if (!LOC10) goto LA11;
								LOC13 = (Ttype264832*)0;
								LOC13 = getsystype_309153_3937434831(((Ttypekind264244) 1));
								isn0 = newnodeit_266801_850551059(((Tnodekind264020) 27), (*base0).info, LOC13);
								LOC14 = (Tnode264794*)0;
								LOC14 = newsymnode_266234_850551059(iss0);
								addson_266807_850551059(isn0, LOC14);
								LOC15 = (Tnode264794*)0;
								LOC15 = newsymnode_266234_850551059((*(*(*(*base0).typ).n).kindU.S6.sons->data[col_401049_3853300031]).kindU.S4.sym);
								addson_266807_850551059(isn0, LOC15);
								LOC16 = (Tnode264794*)0;
								LOC16 = newnodeit_266801_850551059(((Tnodekind264020) 4), (*base0).info, (*(*curr0).typ).sons->data[col_401049_3853300031]);
								addson_266807_850551059(isn0, LOC16);
								{
									Tnode264794* a0;
									Ttype264832* LOC21;
									Tnode264794* LOC22;
									if (!!((cond0 == NIM_NIL))) goto LA19;
									LOC21 = (Ttype264832*)0;
									LOC21 = getsystype_309153_3937434831(((Ttypekind264244) 1));
									a0 = newnodeit_266801_850551059(((Tnodekind264020) 27), (*base0).info, LOC21);
									LOC22 = (Tnode264794*)0;
									LOC22 = newsymnode_266234_850551059(ands0);
									addson_266807_850551059(a0, LOC22);
									addson_266807_850551059(a0, cond0);
									addson_266807_850551059(a0, isn0);
									cond0 = a0;
								}
								goto LA17;
								LA19: ;
								{
									cond0 = isn0;
								}
								LA17: ;
							}
							LA11: ;
							res_401131_3853300031 += ((NI) 1);
						} LA7: ;
					}
				}
				call0 = newnodei_266248_850551059(((Tnodekind264020) 27), (*base0).info);
				LOC24 = (Tnode264794*)0;
				LOC24 = newsymnode_266234_850551059(curr0);
				addson_266807_850551059(call0, LOC24);
				{
					NI col_401084_3853300031;
					NI HEX3Atmp_401136_3853300031;
					NI res_401139_3853300031;
					col_401084_3853300031 = (NI)0;
					HEX3Atmp_401136_3853300031 = (NI)0;
					HEX3Atmp_401136_3853300031 = (NI)(paramlen0 - ((NI) 1));
					res_401139_3853300031 = ((NI) 1);
					{
						while (1) {
							Tnode264794* LOC28;
							Tnode264794* LOC29;
							if (!(res_401139_3853300031 <= HEX3Atmp_401136_3853300031)) goto LA27;
							col_401084_3853300031 = res_401139_3853300031;
							LOC28 = (Tnode264794*)0;
							LOC28 = newsymnode_266234_850551059((*(*(*(*base0).typ).n).kindU.S6.sons->data[col_401084_3853300031]).kindU.S4.sym);
							LOC29 = (Tnode264794*)0;
							LOC29 = genconv_400005_3853300031(LOC28, (*(*curr0).typ).sons->data[col_401084_3853300031], NIM_FALSE);
							addson_266807_850551059(call0, LOC29);
							res_401139_3853300031 += ((NI) 1);
						} LA27: ;
					}
				}
				ret0 = (Tnode264794*)0;
				{
					Tnode264794* a0;
					Tnode264794* LOC34;
					if (!!(((*(*base0).typ).sons->data[((NI) 0)] == NIM_NIL))) goto LA32;
					a0 = newnodei_266248_850551059(((Tnodekind264020) 74), (*base0).info);
					LOC34 = (Tnode264794*)0;
					LOC34 = newsymnode_266234_850551059((*(*(*base0).ast).kindU.S6.sons->data[((NI) 7)]).kindU.S4.sym);
					addson_266807_850551059(a0, LOC34);
					addson_266807_850551059(a0, call0);
					ret0 = newnodei_266248_850551059(((Tnodekind264020) 109), (*base0).info);
					addson_266807_850551059(ret0, a0);
				}
				goto LA30;
				LA32: ;
				{
					ret0 = call0;
				}
				LA30: ;
				{
					Tnode264794* a0;
					if (!!((cond0 == NIM_NIL))) goto LA38;
					a0 = newnodei_266248_850551059(((Tnodekind264020) 86), (*base0).info);
					addson_266807_850551059(a0, cond0);
					addson_266807_850551059(a0, ret0);
					addson_266807_850551059(disp0, a0);
				}
				goto LA36;
				LA38: ;
				{
					disp0 = ret0;
				}
				LA36: ;
				res_401147_3853300031 += ((NI) 1);
			} LA4: ;
		}
	}
	asgnRefNoCycle((void**) (&(*(*result0).ast).kindU.S6.sons->data[((NI) 6)]), disp0);
	return result0;
}

N_NIMCALL(Tnode264794*, generatemethoddispatchers_401151_3853300031)(void) {
	Tnode264794* result0;
	result0 = (Tnode264794*)0;
	result0 = newnode_265401_850551059(((Tnodekind264020) 115));
	{
		NI bucket_401173_3853300031;
		NI HEX3Atmp_401199_3853300031;
		NI res_401202_3853300031;
		bucket_401173_3853300031 = (NI)0;
		HEX3Atmp_401199_3853300031 = (NI)0;
		HEX3Atmp_401199_3853300031 = (NI)((gmethods_400246_3853300031 ? gmethods_400246_3853300031->Sup.len : 0) - ((NI) 1));
		res_401202_3853300031 = ((NI) 0);
		{
			while (1) {
				Intset241031 relevantcols0;
				Tsym264826* LOC13;
				Tnode264794* LOC14;
				if (!(res_401202_3853300031 <= HEX3Atmp_401199_3853300031)) goto LA3;
				bucket_401173_3853300031 = res_401202_3853300031;
				memset((void*)(&relevantcols0), 0, sizeof(relevantcols0));
				chckNil((void*)(&relevantcols0));
				memset((void*)(&relevantcols0), 0, sizeof(relevantcols0));
				initintset_241885_2627731572((&relevantcols0));
				{
					NI col_401187_3853300031;
					NI HEX3Atmp_401192_3853300031;
					NI LOC5;
					NI res_401195_3853300031;
					col_401187_3853300031 = (NI)0;
					HEX3Atmp_401192_3853300031 = (NI)0;
					LOC5 = (NI)0;
					LOC5 = sonslen_267327_850551059((*gmethods_400246_3853300031->data[bucket_401173_3853300031].Field0->data[((NI) 0)]).typ);
					HEX3Atmp_401192_3853300031 = (NI)(LOC5 - ((NI) 1));
					res_401195_3853300031 = ((NI) 1);
					{
						while (1) {
							if (!(res_401195_3853300031 <= HEX3Atmp_401192_3853300031)) goto LA7;
							col_401187_3853300031 = res_401195_3853300031;
							{
								NIM_BOOL LOC10;
								LOC10 = (NIM_BOOL)0;
								LOC10 = relevantcol_400896_3853300031(gmethods_400246_3853300031->data[bucket_401173_3853300031].Field0, col_401187_3853300031);
								if (!LOC10) goto LA11;
								incl_241832_2627731572((&relevantcols0), col_401187_3853300031);
							}
							LA11: ;
							res_401195_3853300031 += ((NI) 1);
						} LA7: ;
					}
				}
				sortbucket_400970_3853300031((&gmethods_400246_3853300031->data[bucket_401173_3853300031].Field0), (&relevantcols0));
				LOC13 = (Tsym264826*)0;
				LOC13 = gendispatcher_401010_3853300031(gmethods_400246_3853300031->data[bucket_401173_3853300031].Field0, (&relevantcols0));
				LOC14 = (Tnode264794*)0;
				LOC14 = newsymnode_266234_850551059(LOC13);
				addson_266807_850551059(result0, LOC14);
				res_401202_3853300031 += ((NI) 1);
			} LA3: ;
		}
	}
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, compiler_cgmethInit000)(void) {
nimRegisterGlobalMarker(TMP1109);
	if (gmethods_400246_3853300031) nimGCunrefNoCycle(gmethods_400246_3853300031);
	gmethods_400246_3853300031 = (TY400226*) newSeqRC1((&NTI400226), 0);
}

NIM_EXTERNC N_NOINLINE(void, compiler_cgmethDatInit000)(void) {
static TNimNode* TMP1107[2];
static TNimNode TMP1105[3];
NTI400227.size = sizeof(TY400227);
NTI400227.kind = 18;
NTI400227.base = 0;
NTI400227.flags = 2;
TMP1107[0] = &TMP1105[1];
TMP1105[1].kind = 1;
TMP1105[1].offset = offsetof(TY400227, Field0);
TMP1105[1].typ = (&NTI264796);
TMP1105[1].name = "Field0";
TMP1107[1] = &TMP1105[2];
TMP1105[2].kind = 1;
TMP1105[2].offset = offsetof(TY400227, Field1);
TMP1105[2].typ = (&NTI264792);
TMP1105[2].name = "Field1";
TMP1105[0].len = 2; TMP1105[0].kind = 2; TMP1105[0].sons = &TMP1107[0];
NTI400227.node = &TMP1105[0];
NTI400226.size = sizeof(TY400226*);
NTI400226.kind = 24;
NTI400226.base = (&NTI400227);
NTI400226.flags = 2;
NTI400226.marker = TMP1108;
}

