/* Generated by Nim Compiler v0.14.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
typedef struct Tnode265794 Tnode265794;
typedef struct Tcontext316020 Tcontext316020;
typedef struct Tsym265826 Tsym265826;
typedef struct Tpatterncontext444004 Tpatterncontext444004;
typedef struct Tnodeseq265788 Tnodeseq265788;
typedef struct Ttype265832 Ttype265832;
typedef struct Tidobj195006 Tidobj195006;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Ttypeseq265828 Ttypeseq265828;
typedef struct Tscope265820 Tscope265820;
typedef struct TY265927 TY265927;
typedef struct Tstrtable265798 Tstrtable265798;
typedef struct Tsymseq265796 Tsymseq265796;
typedef struct Tident195012 Tident195012;
typedef struct Tlineinfo187336 Tlineinfo187336;
typedef struct Tloc265808 Tloc265808;
typedef struct Ropeobj175006 Ropeobj175006;
typedef struct Tlib265812 Tlib265812;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Cell47704 Cell47704;
typedef struct Cellseq47720 Cellseq47720;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Memregion29885 Memregion29885;
typedef struct Smallchunk29839 Smallchunk29839;
typedef struct Llchunk29879 Llchunk29879;
typedef struct Bigchunk29841 Bigchunk29841;
typedef struct Intset29814 Intset29814;
typedef struct Trunk29810 Trunk29810;
typedef struct Avlnode29883 Avlnode29883;
typedef struct Gcstat50214 Gcstat50214;
typedef struct Cellset47716 Cellset47716;
typedef struct Pagedesc47712 Pagedesc47712;
typedef struct TY444485 TY444485;
typedef struct Tpasscontext313002 Tpasscontext313002;
typedef struct Tproccon316008 Tproccon316008;
typedef struct Intset242031 Intset242031;
typedef struct Trunk242027 Trunk242027;
typedef struct Trunkseq242029 Trunkseq242029;
typedef struct Tlinkedlist145016 Tlinkedlist145016;
typedef struct Tlistentry145010 Tlistentry145010;
typedef struct Tidtable265844 Tidtable265844;
typedef struct Tidpairseq265842 Tidpairseq265842;
typedef struct Tctx315036 Tctx315036;
typedef struct TY316144 TY316144;
typedef struct Tinstantiation265816 Tinstantiation265816;
typedef struct Basechunk29837 Basechunk29837;
typedef struct Freecell29829 Freecell29829;
typedef struct Tidpair265840 Tidpair265840;
typedef struct TY315242 TY315242;
typedef struct TY188093 TY188093;
typedef struct PprocHEX3Aobjecttype315221 PprocHEX3Aobjecttype315221;
typedef struct TY315261 TY315261;
typedef struct Tinstantiationpair316010 Tinstantiationpair316010;
typedef struct TY265917 TY265917;
typedef struct TY315222 TY315222;
typedef struct TY315227 TY315227;
typedef struct TY315262 TY315262;
typedef struct Vmargs315030 Vmargs315030;
typedef struct Tblock315018 Tblock315018;
typedef struct TY315202 TY315202;
struct  Tpatterncontext444004  {
Tsym265826* owner;
Tnodeseq265788* mapping;
NI formals;
Tcontext316020* c;
NIM_BOOL submatch;
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Tidobj195006  {
  TNimObject Sup;
NI id;
};
typedef NU8 Tsymkind265435;
struct  Tstrtable265798  {
NI counter;
Tsymseq265796* data;
};
typedef NU8 Tmagic265525;
struct  Tlineinfo187336  {
NI16 line;
NI16 col;
NI32 fileindex;
};
typedef NU32 Tsymflag265184Set;
typedef NU32 Toption166009Set;
typedef NU8 Tlockind265800;
typedef NU8 Tstorageloc265804;
typedef NU16 Tlocflag265802Set;
struct  Tloc265808  {
Tlockind265800 k;
Tstorageloc265804 s;
Tlocflag265802Set flags;
Ttype265832* t;
Ropeobj175006* r;
Ropeobj175006* heaproot;
};
struct  Tsym265826  {
  Tidobj195006 Sup;
Tsymkind265435 kind;
union{
struct {Ttypeseq265828* typeinstcache;
Tscope265820* typscope;
} S1;
struct {TY265927* procinstcache;
Tsym265826* gcunsafetyreason;
} S2;
struct {TY265927* usedgenerics;
Tstrtable265798 tab;
} S3;
struct {Tsym265826* guard;
NI bitsize;
} S4;
} kindU;
Tmagic265525 magic;
Ttype265832* typ;
Tident195012* name;
Tlineinfo187336 info;
Tsym265826* owner;
Tsymflag265184Set flags;
Tnode265794* ast;
Toption166009Set options;
NI position;
NI offset;
Tloc265808 loc;
Tlib265812* annex;
Tnode265794* constraint;
};
typedef NU16 Tnodeflag265427Set;
typedef NU8 Tnodekind265020;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Tnode265794  {
Ttype265832* typ;
Tlineinfo187336 info;
Tnodeflag265427Set flags;
Tnodekind265020 kind;
union{
struct {NI64 intval;
} S1;
struct {NF floatval;
} S2;
struct {NimStringDesc* strval;
} S3;
struct {Tsym265826* sym;
} S4;
struct {Tident195012* ident;
} S5;
struct {Tnodeseq265788* sons;
} S6;
} kindU;
NimStringDesc* comment;
};
typedef NU8 Tnodeflag265427;
struct  Tident195012  {
  Tidobj195006 Sup;
NimStringDesc* s;
Tident195012* next;
NI h;
};
typedef NU8 Ttypecmpflag296625Set;
typedef NU8 Ttypekind265244;
typedef NU8 Tcallingconvention265002;
typedef NU32 Ttypeflag265431Set;
struct  Ttype265832  {
  Tidobj195006 Sup;
Ttypekind265244 kind;
Tcallingconvention265002 callconv;
Ttypeflag265431Set flags;
Ttypeseq265828* sons;
Tnode265794* n;
Tsym265826* owner;
Tsym265826* sym;
Tsym265826* destructor;
Tsym265826* deepcopy;
Tsym265826* assignment;
NI64 size;
NI16 align;
NI16 locklevel;
Tloc265808 loc;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47704  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47720  {
NI len;
NI cap;
Cell47704** d;
};
typedef Smallchunk29839* TY29900[512];
typedef Trunk29810* Trunkbuckets29812[256];
struct  Intset29814  {
Trunkbuckets29812 data;
};
struct  Memregion29885  {
NI minlargeobj;
NI maxlargeobj;
TY29900 freesmallchunks;
Llchunk29879* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29841* freechunkslist;
Intset29814 chunkstarts;
Avlnode29883* root;
Avlnode29883* deleted;
Avlnode29883* last;
Avlnode29883* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat50214  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47716  {
NI counter;
NI max;
Pagedesc47712* head;
Pagedesc47712** data;
};
struct  Gcheap50218  {
Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47720 zct;
Cellseq47720 decstack;
Cellseq47720 tempstack;
NI recgclock;
Memregion29885 region;
Gcstat50214 stat;
Cellset47716 marked;
Cellseq47720 additionalroots;
};
struct  TY444485  {
NI HEX3Astate;
Tnode265794* p444375;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Tpatterncontext444004* c0, Tnode265794* op0, Tnode265794* n_444383_1003693714, Tnode265794* arglist0, NIM_BOOL rpn0, void* ClEnv);
void* ClEnv;
} TY444380;
typedef N_CLOSURE_PTR(NIM_BOOL, TMP3527) (Tpatterncontext444004* c0, Tnode265794* op0, Tnode265794* n_444383_1003693714, Tnode265794* arglist0, NIM_BOOL rpn0);
typedef N_CLOSURE_PTR(NIM_BOOL, TMP3528) (Tpatterncontext444004* c0, Tnode265794* op0, Tnode265794* n_444383_1003693714, Tnode265794* arglist0, NIM_BOOL rpn0);
typedef N_CLOSURE_PTR(NIM_BOOL, TMP3529) (Tpatterncontext444004* c0, Tnode265794* op0, Tnode265794* n_444383_1003693714, Tnode265794* arglist0, NIM_BOOL rpn0);
typedef NU8 Taliasrequest335006;
typedef NU8 Tanalysisresult443004;
struct  Tpasscontext313002  {
  TNimObject Sup;
NIM_BOOL fromcache;
};
struct  Intset242031  {
NI counter;
NI max;
Trunk242027* head;
Trunkseq242029* data;
};
struct  Tlinkedlist145016  {
Tlistentry145010* head;
Tlistentry145010* tail;
NI counter;
};
struct  Tidtable265844  {
NI counter;
Tidpairseq265842* data;
};
typedef N_NIMCALL_PTR(Tnode265794*, TY316075) (Tcontext316020* c0, Tnode265794* n0);
typedef NU16 Texprflag316012Set;
typedef N_NIMCALL_PTR(Tnode265794*, TY316080) (Tcontext316020* c0, Tnode265794* n0, Texprflag316012Set flags0);
typedef N_NIMCALL_PTR(Tnode265794*, TY316088) (Tcontext316020* c0, Tnode265794* n0, Texprflag316012Set flags0);
typedef N_NIMCALL_PTR(Tnode265794*, TY316096) (Tcontext316020* c0, Tnode265794* n0);
typedef N_NIMCALL_PTR(Tnode265794*, TY316101) (Tcontext316020* c0, Tnode265794* n0, Texprflag316012Set flags0);
typedef N_NIMCALL_PTR(Tnode265794*, TY316109) (Tcontext316020* c0, Tnode265794* n0);
typedef NU32 Tsymkind265435Set;
typedef N_NIMCALL_PTR(Tnode265794*, TY316114) (Tcontext316020* c0, Tnode265794* n0, Tnode265794* norig0, Tsymkind265435Set filter0);
typedef N_NIMCALL_PTR(Ttype265832*, TY316121) (Tcontext316020* c0, Tnode265794* n0, Ttype265832* prev0);
typedef struct {
N_NIMCALL_PTR(Tnode265794*, ClPrc) (Tcontext316020* c0, Tidtable265844 pt0, Tnode265794* n0, void* ClEnv);
void* ClEnv;
} TY316127;
typedef struct {
N_NIMCALL_PTR(Tsym265826*, ClPrc) (Tcontext316020* c0, Tsym265826* fn0, Tidtable265844 pt0, Tlineinfo187336 info0, void* ClEnv);
void* ClEnv;
} TY316133;
typedef NU8 Ttypeattachedop316016;
typedef N_NIMCALL_PTR(Tsym265826*, TY316149) (Tcontext316020* c0, Tsym265826* dc0, Ttype265832* t0, Tlineinfo187336 info0, Ttypeattachedop316016 op0);
struct  Tcontext316020  {
  Tpasscontext313002 Sup;
Tsym265826* module;
Tscope265820* currentscope;
Tscope265820* importtable;
Tscope265820* toplevelscope;
Tproccon316008* p;
Tsymseq265796* friendmodules;
NI instcounter;
Intset242031 ambiguoussymbols;
NI intypeclass;
NI ingenericcontext;
NI inunrolledcontext;
NI compilescontextid;
NI compilescontextidgenerator;
NI ingenericinst;
Tsymseq265796* converters;
Tsymseq265796* patterns;
Tlinkedlist145016 optionstack;
Tidtable265844 symmapping;
Tlinkedlist145016 libs;
TY316075 semconstexpr;
TY316080 semexpr;
TY316088 semtryexpr;
TY316096 semtryconstexpr;
TY316101 semoperand;
TY316109 semconstboolexpr;
TY316114 semoverloadedcall;
TY316121 semtypenode;
TY316127 seminferredlambda;
TY316133 semgenerateinstance;
Intset242031 includedfiles;
Tstrtable265798 userpragmas;
Tctx315036* evalcontext;
Intset242031 unknownidents;
TY316144* generics;
NI lastgenericidx;
NI hloloopdetector;
NI inparallelstmt;
TY316149 insttypeboundop;
Tident195012* selfname;
Tstrtable265798 signatures;
};
struct  Tscope265820  {
NI depthlevel;
Tstrtable265798 symbols;
Tscope265820* parent;
};
struct  Ropeobj175006  {
  TNimObject Sup;
Ropeobj175006* left;
Ropeobj175006* right;
NI length;
NimStringDesc* data;
};
struct  Tlistentry145010  {
  TNimObject Sup;
Tlistentry145010* prev;
Tlistentry145010* next;
};
typedef NU8 Tlibkind265810;
struct  Tlib265812  {
  Tlistentry145010 Sup;
Tlibkind265810 kind;
NIM_BOOL generated;
NIM_BOOL isoverriden;
Ropeobj175006* name;
Tnode265794* path;
};
struct  Gcstack50216  {
Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29837  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29839  {
  Basechunk29837 Sup;
Smallchunk29839* next;
Smallchunk29839* prev;
Freecell29829* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29879  {
NI size;
NI acc;
Llchunk29879* next;
};
struct  Bigchunk29841  {
  Basechunk29837 Sup;
Bigchunk29841* next;
Bigchunk29841* prev;
NI align;
NF data;
};
typedef NI TY29818[16];
struct  Trunk29810  {
Trunk29810* next;
NI key;
TY29818 bits;
};
typedef Avlnode29883* TY29890[2];
struct  Avlnode29883  {
TY29890 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47712  {
Pagedesc47712* next;
NI key;
TY29818 bits;
};
struct  Tproccon316008  {
Tsym265826* owner;
Tsym265826* resultsym;
Tsym265826* selfsym;
NI nestedloopcounter;
NI nestedblockcounter;
NI intrystmt;
Tproccon316008* next;
NIM_BOOL wasforwarded;
Tnode265794* bracketexpr;
};
struct  Trunk242027  {
Trunk242027* next;
NI key;
TY29818 bits;
};
struct  Tidpair265840  {
Tidobj195006* key;
TNimObject* val;
};
typedef NU8 Tevalmode315020;
typedef NU8 Tsandboxflag315022Set;
struct  Tctx315036  {
  Tpasscontext313002 Sup;
TY315242* code;
TY188093* debug;
Tnode265794* globals;
Tnode265794* constants;
Ttypeseq265828* types;
Tnode265794* currentexceptiona;
Tnode265794* currentexceptionb;
NI exceptioninstr;
PprocHEX3Aobjecttype315221* prc;
Tsym265826* module;
Tnode265794* callsite;
Tevalmode315020 mode;
Tsandboxflag315022Set features;
NIM_BOOL traceactive;
NI loopiterations;
Tlineinfo187336 comesfromheuristic;
TY315261* callbacks;
NimStringDesc* errorflag;
};
struct  Tinstantiationpair316010  {
Tsym265826* genericsym;
Tinstantiation265816* inst;
};
struct  Tinstantiation265816  {
Tsym265826* sym;
Ttypeseq265828* concretetypes;
TY265917* usedby;
NI compilesid;
};
struct  Freecell29829  {
Freecell29829* next;
NI zerofield;
};
typedef NU8 Tslotkind315026;
struct TY315227 {
NIM_BOOL Field0;
Tslotkind315026 Field1;
};
typedef TY315227 TY315230[256];
struct  PprocHEX3Aobjecttype315221  {
TY315222* blocks;
Tsym265826* sym;
TY315230 slots;
NI maxslots;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (Vmargs315030* args0, void* ClEnv);
void* ClEnv;
} Vmcallback315032;
struct TY315262 {
NimStringDesc* Field0;
Vmcallback315032 Field1;
};
struct  Tblock315018  {
Tsym265826* label;
TY315202* fixups;
};
struct  Vmargs315030  {
NI ra;
NI rb;
NI rc;
void* slots;
Tnode265794* currentexception;
};
struct Tnodeseq265788 {
  TGenericSeq Sup;
  Tnode265794* data[SEQ_DECL_SIZE];
};
struct Ttypeseq265828 {
  TGenericSeq Sup;
  Ttype265832* data[SEQ_DECL_SIZE];
};
struct TY265927 {
  TGenericSeq Sup;
  Tinstantiation265816* data[SEQ_DECL_SIZE];
};
struct Tsymseq265796 {
  TGenericSeq Sup;
  Tsym265826* data[SEQ_DECL_SIZE];
};
struct Trunkseq242029 {
  TGenericSeq Sup;
  Trunk242027* data[SEQ_DECL_SIZE];
};
struct Tidpairseq265842 {
  TGenericSeq Sup;
  Tidpair265840 data[SEQ_DECL_SIZE];
};
struct TY316144 {
  TGenericSeq Sup;
  Tinstantiationpair316010 data[SEQ_DECL_SIZE];
};
struct TY315242 {
  TGenericSeq Sup;
  NU32 data[SEQ_DECL_SIZE];
};
struct TY188093 {
  TGenericSeq Sup;
  Tlineinfo187336 data[SEQ_DECL_SIZE];
};
struct TY315261 {
  TGenericSeq Sup;
  TY315262 data[SEQ_DECL_SIZE];
};
struct TY265917 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
struct TY315222 {
  TGenericSeq Sup;
  Tblock315018 data[SEQ_DECL_SIZE];
};
struct TY315202 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, sonslen_268327_850551059)(Ttype265832* n0);
N_NIMCALL(Tnode265794*, matchstmtlist_444981_1003693714)(Tpatterncontext444004* c0, Tnode265794* p0, Tnode265794* n_444985_1003693714);
static N_INLINE(NI, len_266080_850551059)(Tnode265794* n0);
N_NIMCALL(Tnode265794*, flattenstmts_291587_2616423590)(Tnode265794* n0);
N_NIMCALL(NIM_BOOL, matchrange_444987_1003693714)(Tpatterncontext444004* c0, Tnode265794* p0, Tnode265794* n0, NI i0);
N_NIMCALL(NIM_BOOL, matches_444052_1003693714)(Tpatterncontext444004* c0, Tnode265794* p0, Tnode265794* n_444056_1003693714);
N_NIMCALL(Tnode265794*, skiphidden_301308_3876443242)(Tnode265794* n0);
static N_INLINE(NIM_BOOL, ispatternparam_444244_1003693714)(Tpatterncontext444004* c0, Tnode265794* p0);
N_NIMCALL(NIM_BOOL, bindorcheck_444315_1003693714)(Tpatterncontext444004* c0, Tsym265826* param0, Tnode265794* n0);
N_NIMCALL(Tnode265794*, getlazy_444014_1003693714)(Tpatterncontext444004* c0, Tsym265826* sym0);
N_NIMCALL(NIM_BOOL, sametrees_444086_1003693714)(Tnode265794* a0, Tnode265794* b0);
static N_INLINE(NIM_BOOL, samekinds_444061_1003693714)(Tnode265794* a0, Tnode265794* b0);
N_NIMCALL(Tnodekind265020, canonkind_444057_1003693714)(Tnode265794* n0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a0, NimStringDesc* b0);
N_NIMCALL(NIM_BOOL, sametypeornil_296839_3876443242)(Ttype265832* a0, Ttype265832* b0, Ttypecmpflag296625Set flags0);
N_NIMCALL(NI, sonslen_268351_850551059)(Tnode265794* n0);
N_NIMCALL(NIM_BOOL, checktypes_444203_1003693714)(Tpatterncontext444004* c0, Tsym265826* p0, Tnode265794* n0);
N_NIMCALL(NIM_BOOL, matchnodekinds_336063_3566143041)(Tnode265794* p0, Tnode265794* n0);
N_NIMCALL(NIM_BOOL, argtypematches_395652_561905635)(Tcontext316020* c0, Ttype265832* f0, Ttype265832* a0);
N_NIMCALL(void, putlazy_444028_1003693714)(Tpatterncontext444004* c0, Tsym265826* sym0, Tnode265794* n0);
N_NIMCALL(void*, newSeq)(TNimType* typ0, NI len0);
N_NIMCALL(void, unsureAsgnRef)(void** dest0, void* src0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell47704*, usrtocell_51840_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_53001_1689653243)(Cell47704* c0);
N_NOINLINE(void, addzct_51817_1689653243)(Cellseq47720* s0, Cell47704* c0);
N_NIMCALL(NIM_BOOL, insymchoice_444134_1003693714)(Tnode265794* sc0, Tnode265794* x0);
N_NIMCALL(NIM_BOOL, matchchoice_444281_1003693714)(Tpatterncontext444004* c0, Tnode265794* p0, Tnode265794* n0);
N_NIMCALL(NIM_BOOL, matchnested_444372_1003693714)(Tpatterncontext444004* c0, Tnode265794* p0, Tnode265794* n0, NIM_BOOL rpn0);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, TMP3526)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
N_NIMCALL(Tnode265794*, newnodei_267248_850551059)(Tnodekind265020 kind0, Tlineinfo187336 info0);
N_CLOSURE(NIM_BOOL, matchstaraux_444379_1003693714)(Tpatterncontext444004* c0, Tnode265794* op0, Tnode265794* n_444383_1003693714, Tnode265794* arglist0, NIM_BOOL rpn0, void* ClEnv);
static N_INLINE(Tnode265794*, HEX5BHEX5D_266238_850551059)(Tnode265794* n0, NI i0);
N_NIMCALL(void, add_266135_850551059)(Tnode265794* father0, Tnode265794* son0);
N_NIMCALL(void, internalerror_192100_155036129)(Tlineinfo187336 info0, NimStringDesc* errmsg0);
N_NIMCALL(void, gather_444343_1003693714)(Tpatterncontext444004* c0, Tsym265826* param0, Tnode265794* n0);
N_NIMCALL(Tnode265794*, newnodei_267401_850551059)(Tnodekind265020 kind0, Tlineinfo187336 info0, NI children0);
N_NIMCALL(Tnode265794*, lastson_268364_850551059)(Tnode265794* n0);
N_NIMCALL(void, genericSeqAssign)(void* dest0, void* src_86004_1689653243, TNimType* mt0);
N_NIMCALL(Tnode265794*, extractrange_291593_2616423590)(Tnodekind265020 k0, Tnode265794* n0, NI a0, NI b0);
N_NIMCALL(Tnode265794*, newsymnode_267241_850551059)(Tsym265826* sym0, Tlineinfo187336 info0);
N_NIMCALL(NIM_BOOL, aliasanalysisrequested_445078_1003693714)(Tnode265794* params0);
N_NIMCALL(Taliasrequest335006, whichalias_335047_3566143041)(Tsym265826* p0);
N_NIMCALL(void, addtoarglist_445122_1003693714)(Tnode265794* result0, Tnode265794* n0);
N_NIMCALL(Tanalysisresult443004, ispartof_443328_788060399)(Tnode265794* a0, Tnode265794* b0);
N_NIMCALL(void, markused_389246_561905635)(Tlineinfo187336 info0, Tsym265826* s0);
STRING_LITERAL(TMP3521, "|", 1);
STRING_LITERAL(TMP3522, "*", 1);
STRING_LITERAL(TMP3523, "**", 2);
STRING_LITERAL(TMP3524, "~", 1);
STRING_LITERAL(TMP3530, "invalid pattern", 15);
extern TNimType NTI265788; /* TNodeSeq */
extern Gcheap50218 gch_50258_1689653243;
TNimType NTI444485; /* object */
extern TNimType NTI352021; /* range -1..0(int) */
extern TNimType NTI265786; /* PNode */
TNimType NTI444484; /* ref object */

static N_INLINE(NI, len_266080_850551059)(Tnode265794* n0) {
	NI result0;
	result0 = (NI)0;
	{
		if (!(*n0).kindU.S6.sons == 0) goto LA3;
		result0 = ((NI) 0);
	}
	goto LA1;
	LA3: ;
	{
		result0 = ((*n0).kindU.S6.sons ? (*n0).kindU.S6.sons->Sup.len : 0);
	}
	LA1: ;
	return result0;
}

static N_INLINE(NIM_BOOL, ispatternparam_444244_1003693714)(Tpatterncontext444004* c0, Tnode265794* p0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	result0 = (NIM_BOOL)0;
	LOC1 = (NIM_BOOL)0;
	LOC2 = (NIM_BOOL)0;
	LOC2 = ((*p0).kind == ((Tnodekind265020) 3));
	if (!(LOC2)) goto LA3;
	LOC2 = ((*(*p0).kindU.S4.sym).kind == ((Tsymkind265435) 3));
	LA3: ;
	LOC1 = LOC2;
	if (!(LOC1)) goto LA4;
	LOC1 = ((*(*p0).kindU.S4.sym).owner == (*c0).owner);
	LA4: ;
	result0 = LOC1;
	return result0;
}

N_NIMCALL(Tnode265794*, getlazy_444014_1003693714)(Tpatterncontext444004* c0, Tsym265826* sym0) {
	Tnode265794* result0;
	result0 = (Tnode265794*)0;
	{
		if (!!((*c0).mapping == 0)) goto LA3;
		result0 = (*c0).mapping->data[(*sym0).position];
	}
	LA3: ;
	return result0;
}

N_NIMCALL(Tnodekind265020, canonkind_444057_1003693714)(Tnode265794* n0) {
	Tnodekind265020 result0;
	result0 = (Tnodekind265020)0;
	result0 = (*n0).kind;
	switch (result0) {
	case ((Tnodekind265020) 27):
	case ((Tnodekind265020) 29):
	case ((Tnodekind265020) 30):
	case ((Tnodekind265020) 31):
	case ((Tnodekind265020) 26):
	case ((Tnodekind265020) 28):
	case ((Tnodekind265020) 32):
	{
		result0 = ((Tnodekind265020) 27);
	}
	break;
	case ((Tnodekind265020) 20) ... ((Tnodekind265020) 22):
	{
		result0 = ((Tnodekind265020) 20);
	}
	break;
	case ((Tnodekind265020) 74):
	{
		result0 = ((Tnodekind265020) 73);
	}
	break;
	default:
	{
	}
	break;
	}
	return result0;
}

static N_INLINE(NIM_BOOL, samekinds_444061_1003693714)(Tnode265794* a0, Tnode265794* b0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	Tnodekind265020 LOC3;
	Tnodekind265020 LOC4;
	result0 = (NIM_BOOL)0;
	LOC1 = (NIM_BOOL)0;
	LOC1 = ((*a0).kind == (*b0).kind);
	if (LOC1) goto LA2;
	LOC3 = (Tnodekind265020)0;
	LOC3 = canonkind_444057_1003693714(a0);
	LOC4 = (Tnodekind265020)0;
	LOC4 = canonkind_444057_1003693714(b0);
	LOC1 = (LOC3 == LOC4);
	LA2: ;
	result0 = LOC1;
	return result0;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a0, NimStringDesc* b0) {
	NIM_BOOL result0;
	NIM_BOOL LOC11;
	int LOC13;
{	result0 = (NIM_BOOL)0;
	{
		if (!(a0 == b0)) goto LA3;
		result0 = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b0 == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result0 = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = (NIM_BOOL)0;
	LOC11 = ((*a0).Sup.len == (*b0).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = (int)0;
	LOC13 = memcmp(((NCSTRING) ((*a0).data)), ((NCSTRING) ((*b0).data)), (*a0).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result0 = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_BOOL, sametrees_444086_1003693714)(Tnode265794* a0, Tnode265794* b0) {
	NIM_BOOL result0;
{	result0 = (NIM_BOOL)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = samekinds_444061_1003693714(a0, b0);
		if (!LOC3) goto LA4;
		switch ((*a0).kind) {
		case ((Tnodekind265020) 3):
		{
			result0 = ((*a0).kindU.S4.sym == (*b0).kindU.S4.sym);
		}
		break;
		case ((Tnodekind265020) 2):
		{
			result0 = ((*(*a0).kindU.S5.ident).Sup.id == (*(*b0).kindU.S5.ident).Sup.id);
		}
		break;
		case ((Tnodekind265020) 5) ... ((Tnodekind265020) 10):
		{
			result0 = ((*a0).kindU.S1.intval == (*b0).kindU.S1.intval);
		}
		break;
		case ((Tnodekind265020) 16) ... ((Tnodekind265020) 18):
		{
			result0 = ((*a0).kindU.S2.floatval == (*b0).kindU.S2.floatval);
		}
		break;
		case ((Tnodekind265020) 20) ... ((Tnodekind265020) 22):
		{
			result0 = eqStrings((*a0).kindU.S3.strval, (*b0).kindU.S3.strval);
		}
		break;
		case ((Tnodekind265020) 1):
		case ((Tnodekind265020) 23):
		{
			result0 = NIM_TRUE;
		}
		break;
		case ((Tnodekind265020) 4):
		{
			result0 = sametypeornil_296839_3876443242((*a0).typ, (*b0).typ, 0);
		}
		break;
		default:
		{
			{
				NI LOC16;
				NI LOC17;
				LOC16 = (NI)0;
				LOC16 = sonslen_268351_850551059(a0);
				LOC17 = (NI)0;
				LOC17 = sonslen_268351_850551059(b0);
				if (!(LOC16 == LOC17)) goto LA18;
				{
					NI i_444123_1003693714;
					NI HEX3Atmp_444127_1003693714;
					NI LOC21;
					NI res_444130_1003693714;
					i_444123_1003693714 = (NI)0;
					HEX3Atmp_444127_1003693714 = (NI)0;
					LOC21 = (NI)0;
					LOC21 = sonslen_268351_850551059(a0);
					HEX3Atmp_444127_1003693714 = (NI)(LOC21 - ((NI) 1));
					res_444130_1003693714 = ((NI) 0);
					{
						while (1) {
							if (!(res_444130_1003693714 <= HEX3Atmp_444127_1003693714)) goto LA23;
							i_444123_1003693714 = res_444130_1003693714;
							{
								NIM_BOOL LOC26;
								LOC26 = (NIM_BOOL)0;
								LOC26 = sametrees_444086_1003693714((*a0).kindU.S6.sons->data[i_444123_1003693714], (*b0).kindU.S6.sons->data[i_444123_1003693714]);
								if (!!(LOC26)) goto LA27;
								goto BeforeRet;
							}
							LA27: ;
							res_444130_1003693714 += ((NI) 1);
						} LA23: ;
					}
				}
				result0 = NIM_TRUE;
			}
			LA18: ;
		}
		break;
		}
	}
	LA4: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_BOOL, checktypes_444203_1003693714)(Tpatterncontext444004* c0, Tsym265826* p0, Tnode265794* n0) {
	NIM_BOOL result0;
{	result0 = (NIM_BOOL)0;
	{
		if (!!(((*p0).constraint == NIM_NIL))) goto LA3;
		result0 = matchnodekinds_336063_3566143041((*p0).constraint, n0);
		{
			if (!!(result0)) goto LA7;
			goto BeforeRet;
		}
		LA7: ;
	}
	LA3: ;
	{
		if (!(*n0).typ == 0) goto LA11;
		result0 = ((*(*p0).typ).kind == ((Ttypekind265244) 3) || (*(*p0).typ).kind == ((Ttypekind265244) 7));
	}
	goto LA9;
	LA11: ;
	{
		result0 = argtypematches_395652_561905635((*c0).c, (*p0).typ, (*n0).typ);
	}
	LA9: ;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(Cell47704*, usrtocell_51840_1689653243)(void* usr0) {
	Cell47704* result0;
	result0 = (Cell47704*)0;
	result0 = ((Cell47704*) ((NI)((NU32)(((NI) (usr0))) - (NU32)(((NI)sizeof(Cell47704))))));
	return result0;
}

static N_INLINE(void, rtladdzct_53001_1689653243)(Cell47704* c0) {
	addzct_51817_1689653243((&gch_50258_1689653243.zct), c0);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	{
		Cell47704* c0;
		if (!!((src0 == NIM_NIL))) goto LA3;
		c0 = usrtocell_51840_1689653243(src0);
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	{
		Cell47704* c0;
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		c0 = usrtocell_51840_1689653243((*dest0));
		{
			(*c0).refcount -= ((NI) 8);
			if (!((NU32)((*c0).refcount) < (NU32)(((NI) 8)))) goto LA11;
			rtladdzct_53001_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	(*dest0) = src0;
}

N_NIMCALL(void, putlazy_444028_1003693714)(Tpatterncontext444004* c0, Tsym265826* sym0, Tnode265794* n0) {
	{
		if (!(*c0).mapping == 0) goto LA3;
		unsureAsgnRef((void**) (&(*c0).mapping), (Tnodeseq265788*) newSeq((&NTI265788), ((NI) ((*c0).formals))));
	}
	LA3: ;
	asgnRefNoCycle((void**) (&(*c0).mapping->data[(*sym0).position]), n0);
}

N_NIMCALL(NIM_BOOL, bindorcheck_444315_1003693714)(Tpatterncontext444004* c0, Tsym265826* param0, Tnode265794* n0) {
	NIM_BOOL result0;
	Tnode265794* pp0;
	result0 = (NIM_BOOL)0;
	pp0 = getlazy_444014_1003693714(c0, param0);
	{
		if (!!((pp0 == NIM_NIL))) goto LA3;
		result0 = sametrees_444086_1003693714(pp0, n0);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		LOC6 = (NIM_BOOL)0;
		LOC6 = ((*n0).kind == ((Tnodekind265020) 152));
		if (LOC6) goto LA7;
		LOC6 = checktypes_444203_1003693714(c0, param0, n0);
		LA7: ;
		if (!LOC6) goto LA8;
		putlazy_444028_1003693714(c0, param0, n0);
		result0 = NIM_TRUE;
	}
	goto LA1;
	LA8: ;
	LA1: ;
	return result0;
}

N_NIMCALL(NIM_BOOL, insymchoice_444134_1003693714)(Tnode265794* sc0, Tnode265794* x0) {
	NIM_BOOL result0;
{	result0 = (NIM_BOOL)0;
	{
		if (!((*sc0).kind == ((Tnodekind265020) 56))) goto LA3;
		{
			NI i_444166_1003693714;
			NI HEX3Atmp_444196_1003693714;
			NI LOC6;
			NI res_444199_1003693714;
			i_444166_1003693714 = (NI)0;
			HEX3Atmp_444196_1003693714 = (NI)0;
			LOC6 = (NI)0;
			LOC6 = len_266080_850551059(sc0);
			HEX3Atmp_444196_1003693714 = (LOC6 - 1);
			res_444199_1003693714 = ((NI) 0);
			{
				while (1) {
					if (!(res_444199_1003693714 <= HEX3Atmp_444196_1003693714)) goto LA8;
					i_444166_1003693714 = res_444199_1003693714;
					{
						if (!((*(*sc0).kindU.S6.sons->data[i_444166_1003693714]).kindU.S4.sym == (*x0).kindU.S4.sym)) goto LA11;
						result0 = NIM_TRUE;
						goto BeforeRet;
					}
					LA11: ;
					res_444199_1003693714 += ((NI) 1);
				} LA8: ;
			}
		}
	}
	goto LA1;
	LA3: ;
	{
		if (!((*sc0).kind == ((Tnodekind265020) 57))) goto LA14;
		result0 = ((*(*(*(*sc0).kindU.S6.sons->data[((NI) 0)]).kindU.S4.sym).name).Sup.id == (*(*(*x0).kindU.S4.sym).name).Sup.id);
	}
	goto LA1;
	LA14: ;
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_BOOL, matchchoice_444281_1003693714)(Tpatterncontext444004* c0, Tnode265794* p0, Tnode265794* n0) {
	NIM_BOOL result0;
{	result0 = (NIM_BOOL)0;
	{
		NI i_444305_1003693714;
		NI HEX3Atmp_444308_1003693714;
		NI LOC2;
		NI res_444311_1003693714;
		i_444305_1003693714 = (NI)0;
		HEX3Atmp_444308_1003693714 = (NI)0;
		LOC2 = (NI)0;
		LOC2 = len_266080_850551059(p0);
		HEX3Atmp_444308_1003693714 = (LOC2 - 1);
		res_444311_1003693714 = ((NI) 1);
		{
			while (1) {
				if (!(res_444311_1003693714 <= HEX3Atmp_444308_1003693714)) goto LA4;
				i_444305_1003693714 = res_444311_1003693714;
				{
					NIM_BOOL LOC7;
					LOC7 = (NIM_BOOL)0;
					LOC7 = matches_444052_1003693714(c0, (*p0).kindU.S6.sons->data[i_444305_1003693714], n0);
					if (!LOC7) goto LA8;
					result0 = NIM_TRUE;
					goto BeforeRet;
				}
				LA8: ;
				res_444311_1003693714 += ((NI) 1);
			} LA4: ;
		}
	}
	}BeforeRet: ;
	return result0;
}
N_NIMCALL(void, TMP3526)(void* p, NI op) {
	TY444485* a;
	a = (TY444485*)p;
	nimGCvisit((void*)(*a).p444375, op);
}

static N_INLINE(Tnode265794*, HEX5BHEX5D_266238_850551059)(Tnode265794* n0, NI i0) {
	Tnode265794* result0;
	result0 = (Tnode265794*)0;
	result0 = (*n0).kindU.S6.sons->data[i0];
	return result0;
}

N_CLOSURE(NIM_BOOL, matchstaraux_444379_1003693714)(Tpatterncontext444004* c0, Tnode265794* op0, Tnode265794* n_444383_1003693714, Tnode265794* arglist0, NIM_BOOL rpn0, void* ClEnv) {
	NIM_BOOL result0;
	TY444485* HEX3Aenvp_444488_1003693714;
{	result0 = (NIM_BOOL)0;
	HEX3Aenvp_444488_1003693714 = (TY444485*) ClEnv;
	result0 = NIM_TRUE;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = ((*n_444383_1003693714).kind == ((Tnodekind265020) 27) || (*n_444383_1003693714).kind == ((Tnodekind265020) 29) || (*n_444383_1003693714).kind == ((Tnodekind265020) 30) || (*n_444383_1003693714).kind == ((Tnodekind265020) 31) || (*n_444383_1003693714).kind == ((Tnodekind265020) 26) || (*n_444383_1003693714).kind == ((Tnodekind265020) 28) || (*n_444383_1003693714).kind == ((Tnodekind265020) 32));
		if (!(LOC3)) goto LA4;
		LOC3 = matches_444052_1003693714(c0, (*op0).kindU.S6.sons->data[((NI) 1)], (*n_444383_1003693714).kindU.S6.sons->data[((NI) 0)]);
		LA4: ;
		if (!LOC3) goto LA5;
		{
			NI i_444408_1003693714;
			NI HEX3Atmp_444454_1003693714;
			NI LOC8;
			NI res_444457_1003693714;
			i_444408_1003693714 = (NI)0;
			HEX3Atmp_444454_1003693714 = (NI)0;
			LOC8 = (NI)0;
			LOC8 = sonslen_268351_850551059(n_444383_1003693714);
			HEX3Atmp_444454_1003693714 = (NI)(LOC8 - ((NI) 1));
			res_444457_1003693714 = ((NI) 1);
			{
				while (1) {
					if (!(res_444457_1003693714 <= HEX3Atmp_444454_1003693714)) goto LA10;
					i_444408_1003693714 = res_444457_1003693714;
					{
						TY444380 LOC13;
						Tnode265794* LOC14;
						NIM_BOOL LOC15;
						memset((void*)(&LOC13), 0, sizeof(LOC13));
						LOC13.ClPrc = matchstaraux_444379_1003693714; LOC13.ClEnv = HEX3Aenvp_444488_1003693714;
						LOC14 = (Tnode265794*)0;
						LOC14 = HEX5BHEX5D_266238_850551059(n_444383_1003693714, i_444408_1003693714);
						LOC15 = (NIM_BOOL)0;
						LOC15 = LOC13.ClEnv? LOC13.ClPrc(c0, op0, LOC14, arglist0, rpn0, LOC13.ClEnv):((TMP3527)(LOC13.ClPrc))(c0, op0, LOC14, arglist0, rpn0);
						if (!!(LOC15)) goto LA16;
						result0 = NIM_FALSE;
						goto BeforeRet;
					}
					LA16: ;
					res_444457_1003693714 += ((NI) 1);
				} LA10: ;
			}
		}
		{
			if (!rpn0) goto LA20;
			add_266135_850551059(arglist0, (*n_444383_1003693714).kindU.S6.sons->data[((NI) 0)]);
		}
		LA20: ;
	}
	goto LA1;
	LA5: ;
	{
		NIM_BOOL LOC23;
		Tnode265794* n0;
		LOC23 = (NIM_BOOL)0;
		LOC23 = ((*n_444383_1003693714).kind == ((Tnodekind265020) 58));
		if (!(LOC23)) goto LA24;
		LOC23 = ((*(*n_444383_1003693714).kindU.S6.sons->data[((NI) 1)]).kind == ((Tnodekind265020) 41));
		LA24: ;
		if (!LOC23) goto LA25;
		n0 = (*n_444383_1003693714).kindU.S6.sons->data[((NI) 1)];
		{
			NI i_444450_1003693714;
			NI HEX3Atmp_444462_1003693714;
			NI LOC28;
			NI res_444465_1003693714;
			i_444450_1003693714 = (NI)0;
			HEX3Atmp_444462_1003693714 = (NI)0;
			LOC28 = (NI)0;
			LOC28 = len_266080_850551059(n0);
			HEX3Atmp_444462_1003693714 = (LOC28 - 1);
			res_444465_1003693714 = ((NI) 0);
			{
				while (1) {
					if (!(res_444465_1003693714 <= HEX3Atmp_444462_1003693714)) goto LA30;
					i_444450_1003693714 = res_444465_1003693714;
					{
						TY444380 LOC33;
						Tnode265794* LOC34;
						NIM_BOOL LOC35;
						memset((void*)(&LOC33), 0, sizeof(LOC33));
						LOC33.ClPrc = matchstaraux_444379_1003693714; LOC33.ClEnv = HEX3Aenvp_444488_1003693714;
						LOC34 = (Tnode265794*)0;
						LOC34 = HEX5BHEX5D_266238_850551059(n0, i_444450_1003693714);
						LOC35 = (NIM_BOOL)0;
						LOC35 = LOC33.ClEnv? LOC33.ClPrc(c0, op0, LOC34, arglist0, rpn0, LOC33.ClEnv):((TMP3528)(LOC33.ClPrc))(c0, op0, LOC34, arglist0, rpn0);
						if (!!(LOC35)) goto LA36;
						result0 = NIM_FALSE;
						goto BeforeRet;
					}
					LA36: ;
					res_444465_1003693714 += ((NI) 1);
				} LA30: ;
			}
		}
	}
	goto LA1;
	LA25: ;
	{
		NIM_BOOL LOC39;
		LOC39 = (NIM_BOOL)0;
		LOC39 = checktypes_444203_1003693714(c0, (*(*(*HEX3Aenvp_444488_1003693714).p444375).kindU.S6.sons->data[((NI) 2)]).kindU.S4.sym, n_444383_1003693714);
		if (!LOC39) goto LA40;
		add_266135_850551059(arglist0, n_444383_1003693714);
	}
	goto LA1;
	LA40: ;
	{
		result0 = NIM_FALSE;
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_BOOL, matchnested_444372_1003693714)(Tpatterncontext444004* c0, Tnode265794* p0, Tnode265794* n0, NIM_BOOL rpn0) {
	NIM_BOOL result0;
	TY444485* HEX3Aenv_444490_1003693714;
{	result0 = (NIM_BOOL)0;
	HEX3Aenv_444490_1003693714 = (TY444485*)0;
	HEX3Aenv_444490_1003693714 = (TY444485*) newObj((&NTI444484), sizeof(TY444485));
	asgnRefNoCycle((void**) (&(*HEX3Aenv_444490_1003693714).p444375), p0);
	{
		if (!!(((*n0).kind == ((Tnodekind265020) 27) || (*n0).kind == ((Tnodekind265020) 29) || (*n0).kind == ((Tnodekind265020) 30) || (*n0).kind == ((Tnodekind265020) 31) || (*n0).kind == ((Tnodekind265020) 26) || (*n0).kind == ((Tnodekind265020) 28) || (*n0).kind == ((Tnodekind265020) 32)))) goto LA3;
		result0 = NIM_FALSE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		Tnode265794* arglist0;
		LOC7 = (NIM_BOOL)0;
		LOC7 = matches_444052_1003693714(c0, (*(*HEX3Aenv_444490_1003693714).p444375).kindU.S6.sons->data[((NI) 1)], (*n0).kindU.S6.sons->data[((NI) 0)]);
		if (!LOC7) goto LA8;
		arglist0 = newnodei_267248_850551059(((Tnodekind265020) 152), (*n0).info);
		{
			TY444380 LOC12;
			NIM_BOOL LOC13;
			memset((void*)(&LOC12), 0, sizeof(LOC12));
			LOC12.ClPrc = matchstaraux_444379_1003693714; LOC12.ClEnv = HEX3Aenv_444490_1003693714;
			LOC13 = (NIM_BOOL)0;
			LOC13 = LOC12.ClEnv? LOC12.ClPrc(c0, (*HEX3Aenv_444490_1003693714).p444375, n0, arglist0, rpn0, LOC12.ClEnv):((TMP3529)(LOC12.ClPrc))(c0, (*HEX3Aenv_444490_1003693714).p444375, n0, arglist0, rpn0);
			if (!LOC13) goto LA14;
			result0 = bindorcheck_444315_1003693714(c0, (*(*(*HEX3Aenv_444490_1003693714).p444375).kindU.S6.sons->data[((NI) 2)]).kindU.S4.sym, arglist0);
		}
		LA14: ;
	}
	LA8: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, gather_444343_1003693714)(Tpatterncontext444004* c0, Tsym265826* param0, Tnode265794* n0) {
	Tnode265794* pp0;
	pp0 = getlazy_444014_1003693714(c0, param0);
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = !((pp0 == NIM_NIL));
		if (!(LOC3)) goto LA4;
		LOC3 = ((*pp0).kind == ((Tnodekind265020) 152));
		LA4: ;
		if (!LOC3) goto LA5;
		add_266135_850551059(pp0, n0);
	}
	goto LA1;
	LA5: ;
	{
		pp0 = newnodei_267401_850551059(((Tnodekind265020) 152), (*n0).info, ((NI) 1));
		asgnRefNoCycle((void**) (&(*pp0).kindU.S6.sons->data[((NI) 0)]), n0);
		putlazy_444028_1003693714(c0, param0, pp0);
	}
	LA1: ;
}

N_NIMCALL(NIM_BOOL, matches_444052_1003693714)(Tpatterncontext444004* c0, Tnode265794* p0, Tnode265794* n_444056_1003693714) {
	NIM_BOOL result0;
	Tnode265794* n_444498_1003693714;
{	result0 = (NIM_BOOL)0;
	n_444498_1003693714 = skiphidden_301308_3876443242(n_444056_1003693714);
	{
		if (!(((*n_444498_1003693714).flags &(1U<<((NU)(((Tnodeflag265427) 6))&15U)))!=0)) goto LA3;
		result0 = NIM_FALSE;
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		LOC6 = (NIM_BOOL)0;
		LOC6 = ispatternparam_444244_1003693714(c0, p0);
		if (!LOC6) goto LA7;
		result0 = bindorcheck_444315_1003693714(c0, (*p0).kindU.S4.sym, n_444498_1003693714);
	}
	goto LA1;
	LA7: ;
	{
		NIM_BOOL LOC10;
		LOC10 = (NIM_BOOL)0;
		LOC10 = ((*n_444498_1003693714).kind == ((Tnodekind265020) 3));
		if (!(LOC10)) goto LA11;
		LOC10 = ((*p0).kind == ((Tnodekind265020) 2));
		LA11: ;
		if (!LOC10) goto LA12;
		result0 = ((*(*p0).kindU.S5.ident).Sup.id == (*(*(*n_444498_1003693714).kindU.S4.sym).name).Sup.id);
	}
	goto LA1;
	LA12: ;
	{
		NIM_BOOL LOC15;
		LOC15 = (NIM_BOOL)0;
		LOC15 = ((*n_444498_1003693714).kind == ((Tnodekind265020) 3));
		if (!(LOC15)) goto LA16;
		LOC15 = insymchoice_444134_1003693714(p0, n_444498_1003693714);
		LA16: ;
		if (!LOC15) goto LA17;
		result0 = NIM_TRUE;
	}
	goto LA1;
	LA17: ;
	{
		NIM_BOOL LOC20;
		LOC20 = (NIM_BOOL)0;
		LOC20 = ((*n_444498_1003693714).kind == ((Tnodekind265020) 3));
		if (!(LOC20)) goto LA21;
		LOC20 = ((*(*n_444498_1003693714).kindU.S4.sym).kind == ((Tsymkind265435) 10));
		LA21: ;
		if (!LOC20) goto LA22;
		{
			if (!((*p0).kind == ((Tnodekind265020) 3))) goto LA26;
			result0 = ((*p0).kindU.S4.sym == (*n_444498_1003693714).kindU.S4.sym);
		}
		goto LA24;
		LA26: ;
		{
			NIM_BOOL LOC29;
			LOC29 = (NIM_BOOL)0;
			LOC29 = matches_444052_1003693714(c0, p0, (*(*n_444498_1003693714).kindU.S4.sym).ast);
			if (!LOC29) goto LA30;
			result0 = NIM_TRUE;
		}
		goto LA24;
		LA30: ;
		LA24: ;
	}
	goto LA1;
	LA22: ;
	{
		NimStringDesc* opr0;
		if (!((*p0).kind == ((Tnodekind265020) 153))) goto LA33;
		opr0 = (*(*(*p0).kindU.S6.sons->data[((NI) 0)]).kindU.S5.ident).s;
		if (eqStrings(opr0, ((NimStringDesc*) &TMP3521))) goto LA35;
		if (eqStrings(opr0, ((NimStringDesc*) &TMP3522))) goto LA36;
		if (eqStrings(opr0, ((NimStringDesc*) &TMP3523))) goto LA37;
		if (eqStrings(opr0, ((NimStringDesc*) &TMP3524))) goto LA38;
		goto LA39;
		LA35: ;
		{
			result0 = matchchoice_444281_1003693714(c0, p0, n_444498_1003693714);
		}
		goto LA40;
		LA36: ;
		{
			result0 = matchnested_444372_1003693714(c0, p0, n_444498_1003693714, NIM_FALSE);
		}
		goto LA40;
		LA37: ;
		{
			result0 = matchnested_444372_1003693714(c0, p0, n_444498_1003693714, NIM_TRUE);
		}
		goto LA40;
		LA38: ;
		{
			NIM_BOOL LOC45;
			LOC45 = (NIM_BOOL)0;
			LOC45 = matches_444052_1003693714(c0, (*p0).kindU.S6.sons->data[((NI) 1)], n_444498_1003693714);
			result0 = !(LOC45);
		}
		goto LA40;
		LA39: ;
		{
			internalerror_192100_155036129((*p0).info, ((NimStringDesc*) &TMP3530));
		}
		LA40: ;
	}
	goto LA1;
	LA33: ;
	{
		if (!((*p0).kind == ((Tnodekind265020) 40))) goto LA48;
		{
			if (!((*(*p0).kindU.S6.sons->data[((NI) 1)]).kind == ((Tnodekind265020) 30))) goto LA52;
			{
				NIM_BOOL LOC56;
				LOC56 = (NIM_BOOL)0;
				LOC56 = matches_444052_1003693714(c0, (*p0).kindU.S6.sons->data[((NI) 0)], n_444498_1003693714);
				if (!LOC56) goto LA57;
				gather_444343_1003693714(c0, (*(*(*p0).kindU.S6.sons->data[((NI) 1)]).kindU.S6.sons->data[((NI) 1)]).kindU.S4.sym, n_444498_1003693714);
				result0 = NIM_TRUE;
			}
			LA57: ;
		}
		goto LA50;
		LA52: ;
		{
			{
				NIM_BOOL LOC62;
				LOC62 = (NIM_BOOL)0;
				LOC62 = matches_444052_1003693714(c0, (*p0).kindU.S6.sons->data[((NI) 0)], n_444498_1003693714);
				if (!LOC62) goto LA63;
				result0 = bindorcheck_444315_1003693714(c0, (*(*p0).kindU.S6.sons->data[((NI) 1)]).kindU.S4.sym, n_444498_1003693714);
			}
			LA63: ;
		}
		LA50: ;
	}
	goto LA1;
	LA48: ;
	{
		NIM_BOOL LOC66;
		LOC66 = (NIM_BOOL)0;
		LOC66 = samekinds_444061_1003693714(p0, n_444498_1003693714);
		if (!LOC66) goto LA67;
		switch ((*p0).kind) {
		case ((Tnodekind265020) 3):
		{
			result0 = ((*p0).kindU.S4.sym == (*n_444498_1003693714).kindU.S4.sym);
		}
		break;
		case ((Tnodekind265020) 2):
		{
			result0 = ((*(*p0).kindU.S5.ident).Sup.id == (*(*n_444498_1003693714).kindU.S5.ident).Sup.id);
		}
		break;
		case ((Tnodekind265020) 5) ... ((Tnodekind265020) 10):
		{
			result0 = ((*p0).kindU.S1.intval == (*n_444498_1003693714).kindU.S1.intval);
		}
		break;
		case ((Tnodekind265020) 16) ... ((Tnodekind265020) 18):
		{
			result0 = ((*p0).kindU.S2.floatval == (*n_444498_1003693714).kindU.S2.floatval);
		}
		break;
		case ((Tnodekind265020) 20) ... ((Tnodekind265020) 22):
		{
			result0 = eqStrings((*p0).kindU.S3.strval, (*n_444498_1003693714).kindU.S3.strval);
		}
		break;
		case ((Tnodekind265020) 1):
		case ((Tnodekind265020) 23):
		case ((Tnodekind265020) 4):
		{
			result0 = NIM_TRUE;
		}
		break;
		default:
		{
			NI plen0;
			Tnode265794* v0;
			plen0 = sonslen_268351_850551059(p0);
			v0 = lastson_268364_850551059(p0);
			{
				NIM_BOOL LOC78;
				Tnode265794* arglist0;
				LOC78 = (NIM_BOOL)0;
				LOC78 = ispatternparam_444244_1003693714(c0, v0);
				if (!(LOC78)) goto LA79;
				LOC78 = ((*(*(*v0).kindU.S4.sym).typ).kind == ((Ttypekind265244) 48));
				LA79: ;
				if (!LOC78) goto LA80;
				arglist0 = (Tnode265794*)0;
				{
					NI LOC84;
					LOC84 = (NI)0;
					LOC84 = sonslen_268351_850551059(n_444498_1003693714);
					if (!(plen0 <= LOC84)) goto LA85;
					{
						NI i_444850_1003693714;
						NI HEX3Atmp_444942_1003693714;
						NI res_444945_1003693714;
						i_444850_1003693714 = (NI)0;
						HEX3Atmp_444942_1003693714 = (NI)0;
						HEX3Atmp_444942_1003693714 = (NI)(plen0 - ((NI) 2));
						res_444945_1003693714 = ((NI) 0);
						{
							while (1) {
								if (!(res_444945_1003693714 <= HEX3Atmp_444942_1003693714)) goto LA89;
								i_444850_1003693714 = res_444945_1003693714;
								{
									NIM_BOOL LOC92;
									LOC92 = (NIM_BOOL)0;
									LOC92 = matches_444052_1003693714(c0, (*p0).kindU.S6.sons->data[i_444850_1003693714], (*n_444498_1003693714).kindU.S6.sons->data[i_444850_1003693714]);
									if (!!(LOC92)) goto LA93;
									goto BeforeRet;
								}
								LA93: ;
								res_444945_1003693714 += ((NI) 1);
							} LA89: ;
						}
					}
					{
						NIM_BOOL LOC97;
						NIM_BOOL LOC98;
						NI LOC99;
						Tnode265794* LOC101;
						Tnode265794* LOC103;
						Tnode265794* n0;
						Tnode265794* LOC106;
						NI LOC107;
						LOC97 = (NIM_BOOL)0;
						LOC98 = (NIM_BOOL)0;
						LOC99 = (NI)0;
						LOC99 = sonslen_268351_850551059(n_444498_1003693714);
						LOC98 = (plen0 == LOC99);
						if (!(LOC98)) goto LA100;
						LOC101 = (Tnode265794*)0;
						LOC101 = lastson_268364_850551059(n_444498_1003693714);
						LOC98 = ((*LOC101).kind == ((Tnodekind265020) 58));
						LA100: ;
						LOC97 = LOC98;
						if (!(LOC97)) goto LA102;
						LOC103 = (Tnode265794*)0;
						LOC103 = lastson_268364_850551059(n_444498_1003693714);
						LOC97 = ((*(*LOC103).kindU.S6.sons->data[((NI) 1)]).kind == ((Tnodekind265020) 41));
						LA102: ;
						if (!LOC97) goto LA104;
						LOC106 = (Tnode265794*)0;
						LOC106 = lastson_268364_850551059(n_444498_1003693714);
						n0 = (*LOC106).kindU.S6.sons->data[((NI) 1)];
						LOC107 = (NI)0;
						LOC107 = len_266080_850551059(n0);
						arglist0 = newnodei_267401_850551059(((Tnodekind265020) 152), (*n0).info, LOC107);
						{
							NI i_444893_1003693714;
							NI HEX3Atmp_444950_1003693714;
							NI LOC109;
							NI res_444953_1003693714;
							i_444893_1003693714 = (NI)0;
							HEX3Atmp_444950_1003693714 = (NI)0;
							LOC109 = (NI)0;
							LOC109 = len_266080_850551059(n0);
							HEX3Atmp_444950_1003693714 = (LOC109 - 1);
							res_444953_1003693714 = ((NI) 0);
							{
								while (1) {
									if (!(res_444953_1003693714 <= HEX3Atmp_444950_1003693714)) goto LA111;
									i_444893_1003693714 = res_444953_1003693714;
									asgnRefNoCycle((void**) (&(*arglist0).kindU.S6.sons->data[i_444893_1003693714]), (*n0).kindU.S6.sons->data[i_444893_1003693714]);
									res_444953_1003693714 += ((NI) 1);
								} LA111: ;
							}
						}
					}
					goto LA95;
					LA104: ;
					{
						NI LOC113;
						LOC113 = (NI)0;
						LOC113 = sonslen_268351_850551059(n_444498_1003693714);
						arglist0 = newnodei_267401_850551059(((Tnodekind265020) 152), (*n_444498_1003693714).info, (NI)((NI)(LOC113 - plen0) + ((NI) 1)));
						{
							NI i_444907_1003693714;
							NI HEX3Atmp_444958_1003693714;
							NI LOC115;
							NI res_444961_1003693714;
							i_444907_1003693714 = (NI)0;
							HEX3Atmp_444958_1003693714 = (NI)0;
							LOC115 = (NI)0;
							LOC115 = sonslen_268351_850551059(n_444498_1003693714);
							HEX3Atmp_444958_1003693714 = (NI)(LOC115 - plen0);
							res_444961_1003693714 = ((NI) 0);
							{
								while (1) {
									if (!(res_444961_1003693714 <= HEX3Atmp_444958_1003693714)) goto LA117;
									i_444907_1003693714 = res_444961_1003693714;
									asgnRefNoCycle((void**) (&(*arglist0).kindU.S6.sons->data[i_444907_1003693714]), (*n_444498_1003693714).kindU.S6.sons->data[(NI)((NI)(i_444907_1003693714 + plen0) - ((NI) 1))]);
									res_444961_1003693714 += ((NI) 1);
								} LA117: ;
							}
						}
					}
					LA95: ;
					result0 = bindorcheck_444315_1003693714(c0, (*v0).kindU.S4.sym, arglist0);
					goto BeforeRet;
				}
				goto LA82;
				LA85: ;
				{
					NI LOC119;
					LOC119 = (NI)0;
					LOC119 = sonslen_268351_850551059(n_444498_1003693714);
					if (!((NI)(plen0 - ((NI) 1)) == LOC119)) goto LA120;
					{
						NI i_444922_1003693714;
						NI HEX3Atmp_444966_1003693714;
						NI res_444969_1003693714;
						i_444922_1003693714 = (NI)0;
						HEX3Atmp_444966_1003693714 = (NI)0;
						HEX3Atmp_444966_1003693714 = (NI)(plen0 - ((NI) 2));
						res_444969_1003693714 = ((NI) 0);
						{
							while (1) {
								if (!(res_444969_1003693714 <= HEX3Atmp_444966_1003693714)) goto LA124;
								i_444922_1003693714 = res_444969_1003693714;
								{
									NIM_BOOL LOC127;
									LOC127 = (NIM_BOOL)0;
									LOC127 = matches_444052_1003693714(c0, (*p0).kindU.S6.sons->data[i_444922_1003693714], (*n_444498_1003693714).kindU.S6.sons->data[i_444922_1003693714]);
									if (!!(LOC127)) goto LA128;
									goto BeforeRet;
								}
								LA128: ;
								res_444969_1003693714 += ((NI) 1);
							} LA124: ;
						}
					}
					arglist0 = newnodei_267248_850551059(((Tnodekind265020) 152), (*n_444498_1003693714).info);
					result0 = bindorcheck_444315_1003693714(c0, (*v0).kindU.S4.sym, arglist0);
					goto BeforeRet;
				}
				goto LA82;
				LA120: ;
				LA82: ;
			}
			LA80: ;
			{
				NI LOC132;
				LOC132 = (NI)0;
				LOC132 = sonslen_268351_850551059(n_444498_1003693714);
				if (!(plen0 == LOC132)) goto LA133;
				{
					NI i_444937_1003693714;
					NI HEX3Atmp_444974_1003693714;
					NI LOC136;
					NI res_444977_1003693714;
					i_444937_1003693714 = (NI)0;
					HEX3Atmp_444974_1003693714 = (NI)0;
					LOC136 = (NI)0;
					LOC136 = sonslen_268351_850551059(p0);
					HEX3Atmp_444974_1003693714 = (NI)(LOC136 - ((NI) 1));
					res_444977_1003693714 = ((NI) 0);
					{
						while (1) {
							if (!(res_444977_1003693714 <= HEX3Atmp_444974_1003693714)) goto LA138;
							i_444937_1003693714 = res_444977_1003693714;
							{
								NIM_BOOL LOC141;
								LOC141 = (NIM_BOOL)0;
								LOC141 = matches_444052_1003693714(c0, (*p0).kindU.S6.sons->data[i_444937_1003693714], (*n_444498_1003693714).kindU.S6.sons->data[i_444937_1003693714]);
								if (!!(LOC141)) goto LA142;
								goto BeforeRet;
							}
							LA142: ;
							res_444977_1003693714 += ((NI) 1);
						} LA138: ;
					}
				}
				result0 = NIM_TRUE;
			}
			LA133: ;
		}
		break;
		}
	}
	goto LA1;
	LA67: ;
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_BOOL, matchrange_444987_1003693714)(Tpatterncontext444004* c0, Tnode265794* p0, Tnode265794* n0, NI i0) {
	NIM_BOOL result0;
{	result0 = (NIM_BOOL)0;
	{
		NI j_445012_1003693714;
		NI HEX3Atmp_445024_1003693714;
		NI LOC2;
		NI res_445027_1003693714;
		j_445012_1003693714 = (NI)0;
		HEX3Atmp_445024_1003693714 = (NI)0;
		LOC2 = (NI)0;
		LOC2 = len_266080_850551059(p0);
		HEX3Atmp_445024_1003693714 = (LOC2 - 1);
		res_445027_1003693714 = ((NI) 0);
		{
			while (1) {
				if (!(res_445027_1003693714 <= HEX3Atmp_445024_1003693714)) goto LA4;
				j_445012_1003693714 = res_445027_1003693714;
				{
					NIM_BOOL LOC7;
					LOC7 = (NIM_BOOL)0;
					LOC7 = matches_444052_1003693714(c0, (*p0).kindU.S6.sons->data[j_445012_1003693714], (*n0).kindU.S6.sons->data[(NI)(i0 + j_445012_1003693714)]);
					if (!!(LOC7)) goto LA8;
					{
						if (!!((*c0).mapping == 0)) goto LA12;
						genericSeqAssign((&(*c0).mapping), NIM_NIL, (&NTI265788));
					}
					LA12: ;
					result0 = NIM_FALSE;
					goto BeforeRet;
				}
				LA8: ;
				res_445027_1003693714 += ((NI) 1);
			} LA4: ;
		}
	}
	result0 = NIM_TRUE;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(Tnode265794*, matchstmtlist_444981_1003693714)(Tpatterncontext444004* c0, Tnode265794* p0, Tnode265794* n_444985_1003693714) {
	Tnode265794* result0;
	result0 = (Tnode265794*)0;
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NI LOC7;
		NI LOC8;
		Tnode265794* n0;
		LOC3 = (NIM_BOOL)0;
		LOC4 = (NIM_BOOL)0;
		LOC4 = ((*p0).kind == ((Tnodekind265020) 115));
		if (!(LOC4)) goto LA5;
		LOC4 = ((*n_444985_1003693714).kind == (*p0).kind);
		LA5: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA6;
		LOC7 = (NI)0;
		LOC7 = len_266080_850551059(p0);
		LOC8 = (NI)0;
		LOC8 = len_266080_850551059(n_444985_1003693714);
		LOC3 = (LOC7 < LOC8);
		LA6: ;
		if (!LOC3) goto LA9;
		n0 = flattenstmts_291587_2616423590(n_444985_1003693714);
		{
			NI i_445063_1003693714;
			NI HEX3Atmp_445071_1003693714;
			NI LOC12;
			NI LOC13;
			NI res_445074_1003693714;
			i_445063_1003693714 = (NI)0;
			HEX3Atmp_445071_1003693714 = (NI)0;
			LOC12 = (NI)0;
			LOC12 = len_266080_850551059(n0);
			LOC13 = (NI)0;
			LOC13 = len_266080_850551059(p0);
			HEX3Atmp_445071_1003693714 = (NI)(LOC12 - LOC13);
			res_445074_1003693714 = ((NI) 0);
			{
				while (1) {
					if (!(res_445074_1003693714 <= HEX3Atmp_445071_1003693714)) goto LA15;
					i_445063_1003693714 = res_445074_1003693714;
					{
						NIM_BOOL LOC18;
						NI LOC21;
						NI LOC22;
						NI LOC23;
						LOC18 = (NIM_BOOL)0;
						LOC18 = matchrange_444987_1003693714(c0, p0, n0, i_445063_1003693714);
						if (!LOC18) goto LA19;
						(*c0).submatch = NIM_TRUE;
						result0 = newnodei_267401_850551059(((Tnodekind265020) 115), (*n0).info, ((NI) 3));
						asgnRefNoCycle((void**) (&(*result0).kindU.S6.sons->data[((NI) 0)]), extractrange_291593_2616423590(((Tnodekind265020) 115), n0, ((NI) 0), (NI)(i_445063_1003693714 - ((NI) 1))));
						LOC21 = (NI)0;
						LOC21 = len_266080_850551059(p0);
						asgnRefNoCycle((void**) (&(*result0).kindU.S6.sons->data[((NI) 1)]), extractrange_291593_2616423590(((Tnodekind265020) 115), n0, i_445063_1003693714, (NI)((NI)(i_445063_1003693714 + LOC21) - ((NI) 1))));
						LOC22 = (NI)0;
						LOC22 = len_266080_850551059(p0);
						LOC23 = (NI)0;
						LOC23 = len_266080_850551059(n0);
						asgnRefNoCycle((void**) (&(*result0).kindU.S6.sons->data[((NI) 2)]), extractrange_291593_2616423590(((Tnodekind265020) 115), n0, (NI)(i_445063_1003693714 + LOC22), (NI)(LOC23 - ((NI) 1))));
						goto LA11;
					}
					LA19: ;
					res_445074_1003693714 += ((NI) 1);
				} LA15: ;
			}
		} LA11: ;
	}
	goto LA1;
	LA9: ;
	{
		NIM_BOOL LOC25;
		LOC25 = (NIM_BOOL)0;
		LOC25 = matches_444052_1003693714(c0, p0, n_444985_1003693714);
		if (!LOC25) goto LA26;
		result0 = n_444985_1003693714;
	}
	goto LA1;
	LA26: ;
	LA1: ;
	return result0;
}

N_NIMCALL(NIM_BOOL, aliasanalysisrequested_445078_1003693714)(Tnode265794* params0) {
	NIM_BOOL result0;
{	result0 = (NIM_BOOL)0;
	{
		NI LOC3;
		LOC3 = (NI)0;
		LOC3 = len_266080_850551059(params0);
		if (!(((NI) 2) <= LOC3)) goto LA4;
		{
			NI i_445101_1003693714;
			NI HEX3Atmp_445115_1003693714;
			NI LOC7;
			NI res_445118_1003693714;
			i_445101_1003693714 = (NI)0;
			HEX3Atmp_445115_1003693714 = (NI)0;
			LOC7 = (NI)0;
			LOC7 = len_266080_850551059(params0);
			HEX3Atmp_445115_1003693714 = (LOC7 - 1);
			res_445118_1003693714 = ((NI) 1);
			{
				while (1) {
					Tsym265826* param0;
					if (!(res_445118_1003693714 <= HEX3Atmp_445115_1003693714)) goto LA9;
					i_445101_1003693714 = res_445118_1003693714;
					param0 = (*(*params0).kindU.S6.sons->data[i_445101_1003693714]).kindU.S4.sym;
					{
						Taliasrequest335006 LOC12;
						LOC12 = (Taliasrequest335006)0;
						LOC12 = whichalias_335047_3566143041(param0);
						if (!!((LOC12 == ((Taliasrequest335006) 1)))) goto LA13;
						result0 = NIM_TRUE;
						goto BeforeRet;
					}
					LA13: ;
					res_445118_1003693714 += ((NI) 1);
				} LA9: ;
			}
		}
	}
	LA4: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, addtoarglist_445122_1003693714)(Tnode265794* result0, Tnode265794* n0) {
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = !(((*n0).typ == NIM_NIL));
		if (!(LOC3)) goto LA4;
		LOC3 = !(((*(*n0).typ).kind == ((Ttypekind265244) 7)));
		LA4: ;
		if (!LOC3) goto LA5;
		{
			if (!!(((*n0).kind == ((Tnodekind265020) 152)))) goto LA9;
			add_266135_850551059(result0, n0);
		}
		goto LA7;
		LA9: ;
		{
			{
				NI i_445175_1003693714;
				NI HEX3Atmp_445179_1003693714;
				NI LOC13;
				NI res_445182_1003693714;
				i_445175_1003693714 = (NI)0;
				HEX3Atmp_445179_1003693714 = (NI)0;
				LOC13 = (NI)0;
				LOC13 = len_266080_850551059(n0);
				HEX3Atmp_445179_1003693714 = (LOC13 - 1);
				res_445182_1003693714 = ((NI) 0);
				{
					while (1) {
						if (!(res_445182_1003693714 <= HEX3Atmp_445179_1003693714)) goto LA15;
						i_445175_1003693714 = res_445182_1003693714;
						add_266135_850551059(result0, (*n0).kindU.S6.sons->data[i_445175_1003693714]);
						res_445182_1003693714 += ((NI) 1);
					} LA15: ;
				}
			}
		}
		LA7: ;
	}
	LA5: ;
}

N_NIMCALL(Tnode265794*, applyrule_445186_1003693714)(Tcontext316020* c0, Tsym265826* s0, Tnode265794* n0) {
	Tnode265794* result0;
	Tpatterncontext444004 ctx0;
	NI LOC1;
	Tnode265794* m0;
	Tnode265794* LOC6;
	Tnode265794* params0;
	NIM_BOOL requiresaa0;
	Tnode265794* args0;
{	result0 = (Tnode265794*)0;
	memset((void*)(&ctx0), 0, sizeof(ctx0));
	ctx0.owner = s0;
	ctx0.c = c0;
	LOC1 = (NI)0;
	LOC1 = sonslen_268327_850551059((*s0).typ);
	ctx0.formals = (NI)(LOC1 - ((NI) 1));
	m0 = matchstmtlist_444981_1003693714((&ctx0), (*(*s0).ast).kindU.S6.sons->data[((NI) 1)], n0);
	{
		if (!m0 == 0) goto LA4;
		result0 = NIM_NIL;
		goto BeforeRet;
	}
	LA4: ;
	result0 = newnodei_267248_850551059(((Tnodekind265020) 27), (*n0).info);
	LOC6 = (Tnode265794*)0;
	LOC6 = newsymnode_267241_850551059(s0, (*n0).info);
	add_266135_850551059(result0, LOC6);
	params0 = (*(*s0).typ).n;
	requiresaa0 = aliasanalysisrequested_445078_1003693714(params0);
	args0 = (Tnode265794*)0;
	{
		if (!requiresaa0) goto LA9;
		args0 = newnodei_267248_850551059(((Tnodekind265020) 152), (*n0).info);
	}
	LA9: ;
	{
		NI i_445229_1003693714;
		NI HEX3Atmp_445405_1003693714;
		NI LOC12;
		NI res_445408_1003693714;
		i_445229_1003693714 = (NI)0;
		HEX3Atmp_445405_1003693714 = (NI)0;
		LOC12 = (NI)0;
		LOC12 = len_266080_850551059(params0);
		HEX3Atmp_445405_1003693714 = (LOC12 - 1);
		res_445408_1003693714 = ((NI) 1);
		{
			while (1) {
				Tsym265826* param0;
				Tnode265794* x0;
				if (!(res_445408_1003693714 <= HEX3Atmp_445405_1003693714)) goto LA14;
				i_445229_1003693714 = res_445408_1003693714;
				param0 = (*(*params0).kindU.S6.sons->data[i_445229_1003693714]).kindU.S4.sym;
				x0 = getlazy_444014_1003693714((&ctx0), param0);
				{
					if (!x0 == 0) goto LA17;
					result0 = NIM_NIL;
					goto BeforeRet;
				}
				LA17: ;
				add_266135_850551059(result0, x0);
				{
					if (!requiresaa0) goto LA21;
					addtoarglist_445122_1003693714(args0, x0);
				}
				LA21: ;
				res_445408_1003693714 += ((NI) 1);
			} LA14: ;
		}
	}
	{
		if (!requiresaa0) goto LA25;
		{
			NI i_445262_1003693714;
			NI HEX3Atmp_445435_1003693714;
			NI LOC28;
			NI res_445438_1003693714;
			i_445262_1003693714 = (NI)0;
			HEX3Atmp_445435_1003693714 = (NI)0;
			LOC28 = (NI)0;
			LOC28 = len_266080_850551059(params0);
			HEX3Atmp_445435_1003693714 = (LOC28 - 1);
			res_445438_1003693714 = ((NI) 1);
			{
				while (1) {
					Tnode265794* rs0;
					Tsym265826* param0;
					Taliasrequest335006 LOC31;
					if (!(res_445438_1003693714 <= HEX3Atmp_445435_1003693714)) goto LA30;
					i_445262_1003693714 = res_445438_1003693714;
					rs0 = (*result0).kindU.S6.sons->data[i_445262_1003693714];
					param0 = (*(*params0).kindU.S6.sons->data[i_445262_1003693714]).kindU.S4.sym;
					LOC31 = (Taliasrequest335006)0;
					LOC31 = whichalias_335047_3566143041(param0);
					switch (LOC31) {
					case ((Taliasrequest335006) 1):
					{
					}
					break;
					case ((Taliasrequest335006) 2):
					{
						NIM_BOOL ok0;
						ok0 = NIM_FALSE;
						{
							Tnode265794* arg_445269_1003693714;
							arg_445269_1003693714 = (Tnode265794*)0;
							{
								NI i_445417_1003693714;
								NI HEX3Atmp_445419_1003693714;
								NI LOC36;
								NI res_445421_1003693714;
								i_445417_1003693714 = (NI)0;
								HEX3Atmp_445419_1003693714 = (NI)0;
								LOC36 = (NI)0;
								LOC36 = len_266080_850551059(args0);
								HEX3Atmp_445419_1003693714 = (LOC36 - 1);
								res_445421_1003693714 = ((NI) 0);
								{
									while (1) {
										if (!(res_445421_1003693714 <= HEX3Atmp_445419_1003693714)) goto LA38;
										i_445417_1003693714 = res_445421_1003693714;
										arg_445269_1003693714 = (*args0).kindU.S6.sons->data[i_445417_1003693714];
										{
											NIM_BOOL LOC41;
											Tanalysisresult443004 LOC43;
											LOC41 = (NIM_BOOL)0;
											LOC41 = !((arg_445269_1003693714 == rs0));
											if (!(LOC41)) goto LA42;
											LOC43 = (Tanalysisresult443004)0;
											LOC43 = ispartof_443328_788060399(rs0, arg_445269_1003693714);
											LOC41 = (LOC43 == ((Tanalysisresult443004) 2));
											LA42: ;
											if (!LOC41) goto LA44;
											ok0 = NIM_TRUE;
											goto LA34;
										}
										LA44: ;
										res_445421_1003693714 += ((NI) 1);
									} LA38: ;
								}
							}
						} LA34: ;
						{
							if (!!(ok0)) goto LA48;
							result0 = NIM_NIL;
							goto BeforeRet;
						}
						LA48: ;
					}
					break;
					case ((Taliasrequest335006) 3):
					{
						NIM_BOOL ok0;
						ok0 = NIM_TRUE;
						{
							Tnode265794* arg_445291_1003693714;
							arg_445291_1003693714 = (Tnode265794*)0;
							{
								NI i_445428_1003693714;
								NI HEX3Atmp_445430_1003693714;
								NI LOC53;
								NI res_445432_1003693714;
								i_445428_1003693714 = (NI)0;
								HEX3Atmp_445430_1003693714 = (NI)0;
								LOC53 = (NI)0;
								LOC53 = len_266080_850551059(args0);
								HEX3Atmp_445430_1003693714 = (LOC53 - 1);
								res_445432_1003693714 = ((NI) 0);
								{
									while (1) {
										if (!(res_445432_1003693714 <= HEX3Atmp_445430_1003693714)) goto LA55;
										i_445428_1003693714 = res_445432_1003693714;
										arg_445291_1003693714 = (*args0).kindU.S6.sons->data[i_445428_1003693714];
										{
											NIM_BOOL LOC58;
											Tanalysisresult443004 LOC60;
											LOC58 = (NIM_BOOL)0;
											LOC58 = !((arg_445291_1003693714 == rs0));
											if (!(LOC58)) goto LA59;
											LOC60 = (Tanalysisresult443004)0;
											LOC60 = ispartof_443328_788060399(rs0, arg_445291_1003693714);
											LOC58 = !((LOC60 == ((Tanalysisresult443004) 0)));
											LA59: ;
											if (!LOC58) goto LA61;
											ok0 = NIM_FALSE;
											goto LA51;
										}
										LA61: ;
										res_445432_1003693714 += ((NI) 1);
									} LA55: ;
								}
							}
						} LA51: ;
						{
							if (!!(ok0)) goto LA65;
							result0 = NIM_NIL;
							goto BeforeRet;
						}
						LA65: ;
					}
					break;
					}
					res_445438_1003693714 += ((NI) 1);
				} LA30: ;
			}
		}
	}
	LA25: ;
	markused_389246_561905635((*n0).info, s0);
	{
		if (!ctx0.submatch) goto LA69;
		asgnRefNoCycle((void**) (&(*m0).kindU.S6.sons->data[((NI) 1)]), result0);
		result0 = m0;
	}
	LA69: ;
	}BeforeRet: ;
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, compiler_patternsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, compiler_patternsDatInit000)(void) {
static TNimNode* TMP3525[2];
static TNimNode TMP1158[3];
NTI444485.size = sizeof(TY444485);
NTI444485.kind = 18;
NTI444485.base = 0;
NTI444485.flags = 2;
TMP3525[0] = &TMP1158[1];
TMP1158[1].kind = 1;
TMP1158[1].offset = offsetof(TY444485, HEX3Astate);
TMP1158[1].typ = (&NTI352021);
TMP1158[1].name = ":state";
TMP3525[1] = &TMP1158[2];
TMP1158[2].kind = 1;
TMP1158[2].offset = offsetof(TY444485, p444375);
TMP1158[2].typ = (&NTI265786);
TMP1158[2].name = "p444375";
TMP1158[0].len = 2; TMP1158[0].kind = 2; TMP1158[0].sons = &TMP3525[0];
NTI444485.node = &TMP1158[0];
NTI444484.size = sizeof(TY444485*);
NTI444484.kind = 22;
NTI444484.base = (&NTI444485);
NTI444484.flags = 2;
NTI444484.marker = TMP3526;
}

