/* Generated by Nim Compiler v0.14.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
typedef struct Tnodetable265856 Tnodetable265856;
typedef struct Tnode265794 Tnode265794;
typedef struct Tnodepairseq265854 Tnodepairseq265854;
typedef struct Tnodepair265852 Tnodepair265852;
typedef struct TGenericSeq TGenericSeq;
typedef struct Ttype265832 Ttype265832;
typedef struct Tlineinfo187336 Tlineinfo187336;
typedef struct NimStringDesc NimStringDesc;
typedef struct Tsym265826 Tsym265826;
typedef struct Tident195012 Tident195012;
typedef struct Tnodeseq265788 Tnodeseq265788;
typedef struct Tidobj195006 Tidobj195006;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Ttypeseq265828 Ttypeseq265828;
typedef struct Tscope265820 Tscope265820;
typedef struct TY265927 TY265927;
typedef struct Tstrtable265798 Tstrtable265798;
typedef struct Tsymseq265796 Tsymseq265796;
typedef struct Tloc265808 Tloc265808;
typedef struct Ropeobj175006 Ropeobj175006;
typedef struct Tlib265812 Tlib265812;
typedef struct Cell47704 Cell47704;
typedef struct Cellseq47720 Cellseq47720;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Memregion29885 Memregion29885;
typedef struct Smallchunk29839 Smallchunk29839;
typedef struct Llchunk29879 Llchunk29879;
typedef struct Bigchunk29841 Bigchunk29841;
typedef struct Intset29814 Intset29814;
typedef struct Trunk29810 Trunk29810;
typedef struct Avlnode29883 Avlnode29883;
typedef struct Gcstat50214 Gcstat50214;
typedef struct Cellset47716 Cellset47716;
typedef struct Pagedesc47712 Pagedesc47712;
typedef struct Tinstantiation265816 Tinstantiation265816;
typedef struct Tlistentry145010 Tlistentry145010;
typedef struct Basechunk29837 Basechunk29837;
typedef struct Freecell29829 Freecell29829;
typedef struct TY265917 TY265917;
struct  Tnodepair265852  {
NI h;
Tnode265794* key;
NI val;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  Tlineinfo187336  {
NI16 line;
NI16 col;
NI32 fileindex;
};
typedef NU16 Tnodeflag265427Set;
typedef NU8 Tnodekind265020;
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Tnode265794  {
Ttype265832* typ;
Tlineinfo187336 info;
Tnodeflag265427Set flags;
Tnodekind265020 kind;
union{
struct {NI64 intval;
} S1;
struct {NF floatval;
} S2;
struct {NimStringDesc* strval;
} S3;
struct {Tsym265826* sym;
} S4;
struct {Tident195012* ident;
} S5;
struct {Tnodeseq265788* sons;
} S6;
} kindU;
NimStringDesc* comment;
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Tidobj195006  {
  TNimObject Sup;
NI id;
};
struct  Tident195012  {
  Tidobj195006 Sup;
NimStringDesc* s;
Tident195012* next;
NI h;
};
typedef NU8 Tsymkind265435;
struct  Tstrtable265798  {
NI counter;
Tsymseq265796* data;
};
typedef NU8 Tmagic265525;
typedef NU32 Tsymflag265184Set;
typedef NU32 Toption166009Set;
typedef NU8 Tlockind265800;
typedef NU8 Tstorageloc265804;
typedef NU16 Tlocflag265802Set;
struct  Tloc265808  {
Tlockind265800 k;
Tstorageloc265804 s;
Tlocflag265802Set flags;
Ttype265832* t;
Ropeobj175006* r;
Ropeobj175006* heaproot;
};
struct  Tsym265826  {
  Tidobj195006 Sup;
Tsymkind265435 kind;
union{
struct {Ttypeseq265828* typeinstcache;
Tscope265820* typscope;
} S1;
struct {TY265927* procinstcache;
Tsym265826* gcunsafetyreason;
} S2;
struct {TY265927* usedgenerics;
Tstrtable265798 tab;
} S3;
struct {Tsym265826* guard;
NI bitsize;
} S4;
} kindU;
Tmagic265525 magic;
Ttype265832* typ;
Tident195012* name;
Tlineinfo187336 info;
Tsym265826* owner;
Tsymflag265184Set flags;
Tnode265794* ast;
Toption166009Set options;
NI position;
NI offset;
Tloc265808 loc;
Tlib265812* annex;
Tnode265794* constraint;
};
struct  Tnodetable265856  {
NI counter;
Tnodepairseq265854* data;
};
typedef NU8 Ttypecmpflag296625Set;
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47704  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47720  {
NI len;
NI cap;
Cell47704** d;
};
typedef Smallchunk29839* TY29900[512];
typedef Trunk29810* Trunkbuckets29812[256];
struct  Intset29814  {
Trunkbuckets29812 data;
};
struct  Memregion29885  {
NI minlargeobj;
NI maxlargeobj;
TY29900 freesmallchunks;
Llchunk29879* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29841* freechunkslist;
Intset29814 chunkstarts;
Avlnode29883* root;
Avlnode29883* deleted;
Avlnode29883* last;
Avlnode29883* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat50214  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47716  {
NI counter;
NI max;
Pagedesc47712* head;
Pagedesc47712** data;
};
struct  Gcheap50218  {
Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47720 zct;
Cellseq47720 decstack;
Cellseq47720 tempstack;
NI recgclock;
Memregion29885 region;
Gcstat50214 stat;
Cellset47716 marked;
Cellseq47720 additionalroots;
};
typedef NU8 Ttypekind265244;
typedef NU8 Tcallingconvention265002;
typedef NU32 Ttypeflag265431Set;
struct  Ttype265832  {
  Tidobj195006 Sup;
Ttypekind265244 kind;
Tcallingconvention265002 callconv;
Ttypeflag265431Set flags;
Ttypeseq265828* sons;
Tnode265794* n;
Tsym265826* owner;
Tsym265826* sym;
Tsym265826* destructor;
Tsym265826* deepcopy;
Tsym265826* assignment;
NI64 size;
NI16 align;
NI16 locklevel;
Tloc265808 loc;
};
struct  Tscope265820  {
NI depthlevel;
Tstrtable265798 symbols;
Tscope265820* parent;
};
struct  Ropeobj175006  {
  TNimObject Sup;
Ropeobj175006* left;
Ropeobj175006* right;
NI length;
NimStringDesc* data;
};
struct  Tlistentry145010  {
  TNimObject Sup;
Tlistentry145010* prev;
Tlistentry145010* next;
};
typedef NU8 Tlibkind265810;
struct  Tlib265812  {
  Tlistentry145010 Sup;
Tlibkind265810 kind;
NIM_BOOL generated;
NIM_BOOL isoverriden;
Ropeobj175006* name;
Tnode265794* path;
};
struct  Gcstack50216  {
Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29837  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29839  {
  Basechunk29837 Sup;
Smallchunk29839* next;
Smallchunk29839* prev;
Freecell29829* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29879  {
NI size;
NI acc;
Llchunk29879* next;
};
struct  Bigchunk29841  {
  Basechunk29837 Sup;
Bigchunk29841* next;
Bigchunk29841* prev;
NI align;
NF data;
};
typedef NI TY29818[16];
struct  Trunk29810  {
Trunk29810* next;
NI key;
TY29818 bits;
};
typedef Avlnode29883* TY29890[2];
struct  Avlnode29883  {
TY29890 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47712  {
Pagedesc47712* next;
NI key;
TY29818 bits;
};
struct  Tinstantiation265816  {
Tsym265826* sym;
Ttypeseq265828* concretetypes;
TY265917* usedby;
NI compilesid;
};
struct  Freecell29829  {
Freecell29829* next;
NI zerofield;
};
struct Tnodepairseq265854 {
  TGenericSeq Sup;
  Tnodepair265852 data[SEQ_DECL_SIZE];
};
struct Tnodeseq265788 {
  TGenericSeq Sup;
  Tnode265794* data[SEQ_DECL_SIZE];
};
struct Ttypeseq265828 {
  TGenericSeq Sup;
  Ttype265832* data[SEQ_DECL_SIZE];
};
struct TY265927 {
  TGenericSeq Sup;
  Tinstantiation265816* data[SEQ_DECL_SIZE];
};
struct Tsymseq265796 {
  TGenericSeq Sup;
  Tsym265826* data[SEQ_DECL_SIZE];
};
struct TY265917 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, hashtree_314009_1142335848)(Tnode265794* n0);
static N_INLINE(NI, HEX21HEX26_147004_213663784)(NI h0, NI val0);
N_NIMCALL(NI, hash_147827_213663784)(NimStringDesc* x0);
N_NIMCALL(NI, sonslen_268351_850551059)(Tnode265794* n0);
N_NIMCALL(NI, nodetablerawget_314159_1142335848)(Tnodetable265856 t0, NI k0, Tnode265794* key0);
N_NIMCALL(NIM_BOOL, treesequivalent_314076_1142335848)(Tnode265794* a0, Tnode265794* b0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a0, NimStringDesc* b0);
N_NIMCALL(NIM_BOOL, sametypeornil_296839_3876443242)(Ttype265832* a0, Ttype265832* b0, Ttypecmpflag296625Set flags0);
static N_INLINE(NI, nexttry_272155_2984716966)(NI h0, NI maxhash0);
N_NIMCALL(NIM_BOOL, mustrehash_272151_2984716966)(NI length0, NI counter0);
N_NIMCALL(void*, newSeq)(TNimType* typ0, NI len0);
N_NIMCALL(void, nodetablerawinsert_314189_1142335848)(Tnodepairseq265854** data0, NI k0, Tnode265794* key0, NI val0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell47704*, usrtocell_51840_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_53001_1689653243)(Cell47704* c0);
N_NOINLINE(void, addzct_51817_1689653243)(Cellseq47720* s0, Cell47704* c0);
N_NIMCALL(void, unsureAsgnRef)(void** dest0, void* src0);
extern TNimType NTI265854; /* TNodePairSeq */
extern Gcheap50218 gch_50258_1689653243;

static N_INLINE(NI, HEX21HEX26_147004_213663784)(NI h0, NI val0) {
	NI result0;
	result0 = (NI)0;
	result0 = (NI)((NU32)(h0) + (NU32)(val0));
	result0 = (NI)((NU32)(result0) + (NU32)((NI)((NU32)(result0) << (NU32)(((NI) 10)))));
	result0 = (NI)(result0 ^ (NI)((NU32)(result0) >> (NU32)(((NI) 6))));
	return result0;
}

N_NIMCALL(NI, hashtree_314009_1142335848)(Tnode265794* n0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!(n0 == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	result0 = ((NI) ((*n0).kind));
	switch ((*n0).kind) {
	case ((Tnodekind265020) 1):
	case ((Tnodekind265020) 23):
	case ((Tnodekind265020) 4):
	{
	}
	break;
	case ((Tnodekind265020) 2):
	{
		result0 = HEX21HEX26_147004_213663784(result0, (*(*n0).kindU.S5.ident).h);
	}
	break;
	case ((Tnodekind265020) 3):
	{
		result0 = HEX21HEX26_147004_213663784(result0, (*(*(*n0).kindU.S4.sym).name).h);
	}
	break;
	case ((Tnodekind265020) 5) ... ((Tnodekind265020) 15):
	{
		{
			NIM_BOOL LOC11;
			LOC11 = (NIM_BOOL)0;
			LOC11 = (IL64(-2147483648) <= (*n0).kindU.S1.intval);
			if (!(LOC11)) goto LA12;
			LOC11 = ((*n0).kindU.S1.intval <= IL64(2147483647));
			LA12: ;
			if (!LOC11) goto LA13;
			result0 = HEX21HEX26_147004_213663784(result0, ((NI) ((*n0).kindU.S1.intval)));
		}
		LA13: ;
	}
	break;
	case ((Tnodekind265020) 16) ... ((Tnodekind265020) 18):
	{
		{
			NIM_BOOL LOC18;
			LOC18 = (NIM_BOOL)0;
			LOC18 = (-1.0000000000000000e+06 <= (*n0).kindU.S2.floatval);
			if (!(LOC18)) goto LA19;
			LOC18 = ((*n0).kindU.S2.floatval <= 1.0000000000000000e+06);
			LA19: ;
			if (!LOC18) goto LA20;
			result0 = HEX21HEX26_147004_213663784(result0, float64ToInt32((*n0).kindU.S2.floatval));
		}
		LA20: ;
	}
	break;
	case ((Tnodekind265020) 20) ... ((Tnodekind265020) 22):
	{
		{
			NI LOC27;
			if (!!((*n0).kindU.S3.strval == 0)) goto LA25;
			LOC27 = (NI)0;
			LOC27 = hash_147827_213663784((*n0).kindU.S3.strval);
			result0 = HEX21HEX26_147004_213663784(result0, LOC27);
		}
		LA25: ;
	}
	break;
	default:
	{
		{
			NI i_314062_1142335848;
			NI HEX3Atmp_314069_1142335848;
			NI LOC30;
			NI res_314072_1142335848;
			i_314062_1142335848 = (NI)0;
			HEX3Atmp_314069_1142335848 = (NI)0;
			LOC30 = (NI)0;
			LOC30 = sonslen_268351_850551059(n0);
			HEX3Atmp_314069_1142335848 = (NI)(LOC30 - ((NI) 1));
			res_314072_1142335848 = ((NI) 0);
			{
				while (1) {
					NI LOC33;
					if (!(res_314072_1142335848 <= HEX3Atmp_314069_1142335848)) goto LA32;
					i_314062_1142335848 = res_314072_1142335848;
					LOC33 = (NI)0;
					LOC33 = hashtree_314009_1142335848((*n0).kindU.S6.sons->data[i_314062_1142335848]);
					result0 = HEX21HEX26_147004_213663784(result0, LOC33);
					res_314072_1142335848 += ((NI) 1);
				} LA32: ;
			}
		}
	}
	break;
	}
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a0, NimStringDesc* b0) {
	NIM_BOOL result0;
	NIM_BOOL LOC11;
	int LOC13;
{	result0 = (NIM_BOOL)0;
	{
		if (!(a0 == b0)) goto LA3;
		result0 = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b0 == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result0 = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = (NIM_BOOL)0;
	LOC11 = ((*a0).Sup.len == (*b0).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = (int)0;
	LOC13 = memcmp(((NCSTRING) ((*a0).data)), ((NCSTRING) ((*b0).data)), (*a0).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result0 = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_BOOL, treesequivalent_314076_1142335848)(Tnode265794* a0, Tnode265794* b0) {
	NIM_BOOL result0;
{	result0 = (NIM_BOOL)0;
	{
		if (!(a0 == b0)) goto LA3;
		result0 = NIM_TRUE;
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		NIM_BOOL LOC7;
		LOC6 = (NIM_BOOL)0;
		LOC7 = (NIM_BOOL)0;
		LOC7 = !((a0 == NIM_NIL));
		if (!(LOC7)) goto LA8;
		LOC7 = !((b0 == NIM_NIL));
		LA8: ;
		LOC6 = LOC7;
		if (!(LOC6)) goto LA9;
		LOC6 = ((*a0).kind == (*b0).kind);
		LA9: ;
		if (!LOC6) goto LA10;
		switch ((*a0).kind) {
		case ((Tnodekind265020) 1):
		case ((Tnodekind265020) 23):
		case ((Tnodekind265020) 4):
		{
			result0 = NIM_TRUE;
		}
		break;
		case ((Tnodekind265020) 3):
		{
			result0 = ((*(*a0).kindU.S4.sym).Sup.id == (*(*b0).kindU.S4.sym).Sup.id);
		}
		break;
		case ((Tnodekind265020) 2):
		{
			result0 = ((*(*a0).kindU.S5.ident).Sup.id == (*(*b0).kindU.S5.ident).Sup.id);
		}
		break;
		case ((Tnodekind265020) 5) ... ((Tnodekind265020) 15):
		{
			result0 = ((*a0).kindU.S1.intval == (*b0).kindU.S1.intval);
		}
		break;
		case ((Tnodekind265020) 16) ... ((Tnodekind265020) 18):
		{
			result0 = ((*a0).kindU.S2.floatval == (*b0).kindU.S2.floatval);
		}
		break;
		case ((Tnodekind265020) 20) ... ((Tnodekind265020) 22):
		{
			result0 = eqStrings((*a0).kindU.S3.strval, (*b0).kindU.S3.strval);
		}
		break;
		default:
		{
			{
				NI LOC21;
				NI LOC22;
				LOC21 = (NI)0;
				LOC21 = sonslen_268351_850551059(a0);
				LOC22 = (NI)0;
				LOC22 = sonslen_268351_850551059(b0);
				if (!(LOC21 == LOC22)) goto LA23;
				{
					NI i_314148_1142335848;
					NI HEX3Atmp_314152_1142335848;
					NI LOC26;
					NI res_314155_1142335848;
					i_314148_1142335848 = (NI)0;
					HEX3Atmp_314152_1142335848 = (NI)0;
					LOC26 = (NI)0;
					LOC26 = sonslen_268351_850551059(a0);
					HEX3Atmp_314152_1142335848 = (NI)(LOC26 - ((NI) 1));
					res_314155_1142335848 = ((NI) 0);
					{
						while (1) {
							if (!(res_314155_1142335848 <= HEX3Atmp_314152_1142335848)) goto LA28;
							i_314148_1142335848 = res_314155_1142335848;
							{
								NIM_BOOL LOC31;
								LOC31 = (NIM_BOOL)0;
								LOC31 = treesequivalent_314076_1142335848((*a0).kindU.S6.sons->data[i_314148_1142335848], (*b0).kindU.S6.sons->data[i_314148_1142335848]);
								if (!!(LOC31)) goto LA32;
								goto BeforeRet;
							}
							LA32: ;
							res_314155_1142335848 += ((NI) 1);
						} LA28: ;
					}
				}
				result0 = NIM_TRUE;
			}
			LA23: ;
		}
		break;
		}
		{
			if (!result0) goto LA36;
			result0 = sametypeornil_296839_3876443242((*a0).typ, (*b0).typ, 0);
		}
		LA36: ;
	}
	goto LA1;
	LA10: ;
	LA1: ;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, nexttry_272155_2984716966)(NI h0, NI maxhash0) {
	NI result0;
	result0 = (NI)0;
	result0 = (NI)((NI)((NI)(((NI) 5) * h0) + ((NI) 1)) & maxhash0);
	return result0;
}

N_NIMCALL(NI, nodetablerawget_314159_1142335848)(Tnodetable265856 t0, NI k0, Tnode265794* key0) {
	NI result0;
	NI h0;
{	result0 = (NI)0;
	h0 = (NI)(k0 & (t0.data ? (t0.data->Sup.len-1) : -1));
	{
		while (1) {
			if (!!((t0.data->data[h0].key == NIM_NIL))) goto LA2;
			{
				NIM_BOOL LOC5;
				LOC5 = (NIM_BOOL)0;
				LOC5 = (t0.data->data[h0].h == k0);
				if (!(LOC5)) goto LA6;
				LOC5 = treesequivalent_314076_1142335848(t0.data->data[h0].key, key0);
				LA6: ;
				if (!LOC5) goto LA7;
				result0 = h0;
				goto BeforeRet;
			}
			LA7: ;
			h0 = nexttry_272155_2984716966(h0, (t0.data ? (t0.data->Sup.len-1) : -1));
		} LA2: ;
	}
	result0 = ((NI) -1);
	}BeforeRet: ;
	return result0;
}

static N_INLINE(Cell47704*, usrtocell_51840_1689653243)(void* usr0) {
	Cell47704* result0;
	result0 = (Cell47704*)0;
	result0 = ((Cell47704*) ((NI)((NU32)(((NI) (usr0))) - (NU32)(((NI)sizeof(Cell47704))))));
	return result0;
}

static N_INLINE(void, rtladdzct_53001_1689653243)(Cell47704* c0) {
	addzct_51817_1689653243((&gch_50258_1689653243.zct), c0);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	{
		Cell47704* c0;
		if (!!((src0 == NIM_NIL))) goto LA3;
		c0 = usrtocell_51840_1689653243(src0);
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	{
		Cell47704* c0;
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		c0 = usrtocell_51840_1689653243((*dest0));
		{
			(*c0).refcount -= ((NI) 8);
			if (!((NU32)((*c0).refcount) < (NU32)(((NI) 8)))) goto LA11;
			rtladdzct_53001_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	(*dest0) = src0;
}

N_NIMCALL(void, nodetablerawinsert_314189_1142335848)(Tnodepairseq265854** data0, NI k0, Tnode265794* key0, NI val0) {
	NI h0;
	h0 = (NI)(k0 & ((*data0) ? ((*data0)->Sup.len-1) : -1));
	{
		while (1) {
			if (!!(((*data0)->data[h0].key == NIM_NIL))) goto LA2;
			h0 = nexttry_272155_2984716966(h0, ((*data0) ? ((*data0)->Sup.len-1) : -1));
		} LA2: ;
	}
	(*data0)->data[h0].h = k0;
	asgnRefNoCycle((void**) (&(*data0)->data[h0].key), key0);
	(*data0)->data[h0].val = val0;
}

N_NIMCALL(NI, nodetabletestorset_314682_1142335848)(Tnodetable265856* t0, Tnode265794* key0, NI val0) {
	NI result0;
	Tnodepairseq265854* n0;
	NI k0;
	NI index0;
	result0 = (NI)0;
	n0 = (Tnodepairseq265854*)0;
	k0 = hashtree_314009_1142335848(key0);
	index0 = nodetablerawget_314159_1142335848((*t0), k0, key0);
	{
		if (!(((NI) 0) <= index0)) goto LA3;
		result0 = (*t0).data->data[index0].val;
	}
	goto LA1;
	LA3: ;
	{
		{
			NIM_BOOL LOC8;
			Tnodepairseq265854* LOC18;
			LOC8 = (NIM_BOOL)0;
			LOC8 = mustrehash_272151_2984716966(((*t0).data ? (*t0).data->Sup.len : 0), (*t0).counter);
			if (!LOC8) goto LA9;
			n0 = (Tnodepairseq265854*) newSeq((&NTI265854), ((NI) ((NI)(((*t0).data ? (*t0).data->Sup.len : 0) * ((NI) 2)))));
			{
				NI i_314838_1142335848;
				NI HEX3Atmp_314875_1142335848;
				NI res_314878_1142335848;
				i_314838_1142335848 = (NI)0;
				HEX3Atmp_314875_1142335848 = (NI)0;
				HEX3Atmp_314875_1142335848 = ((*t0).data ? ((*t0).data->Sup.len-1) : -1);
				res_314878_1142335848 = ((NI) 0);
				{
					while (1) {
						if (!(res_314878_1142335848 <= HEX3Atmp_314875_1142335848)) goto LA13;
						i_314838_1142335848 = res_314878_1142335848;
						{
							if (!!(((*t0).data->data[i_314838_1142335848].key == NIM_NIL))) goto LA16;
							nodetablerawinsert_314189_1142335848((&n0), (*t0).data->data[i_314838_1142335848].h, (*t0).data->data[i_314838_1142335848].key, (*t0).data->data[i_314838_1142335848].val);
						}
						LA16: ;
						res_314878_1142335848 += ((NI) 1);
					} LA13: ;
				}
			}
			LOC18 = (Tnodepairseq265854*)0;
			LOC18 = (*t0).data;
			unsureAsgnRef((void**) (&(*t0).data), n0);
			n0 = LOC18;
		}
		LA9: ;
		nodetablerawinsert_314189_1142335848((&(*t0).data), k0, key0, val0);
		result0 = val0;
		(*t0).counter += ((NI) 1);
	}
	LA1: ;
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, compiler_treetabInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, compiler_treetabDatInit000)(void) {
}

