/* Generated by Nim Compiler v0.14.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct Tiitable272167 Tiitable272167;
typedef struct Tiipairseq272165 Tiipairseq272165;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Tiipair272163 Tiipair272163;
typedef struct TGenericSeq TGenericSeq;
typedef struct Tsym265826 Tsym265826;
typedef struct Ttabiter272075 Ttabiter272075;
typedef struct Tstrtable265798 Tstrtable265798;
typedef struct Tsymseq265796 Tsymseq265796;
typedef struct Tident195012 Tident195012;
typedef struct Tidobj195006 Tidobj195006;
typedef struct TNimObject TNimObject;
typedef struct NimStringDesc NimStringDesc;
typedef struct Ttypeseq265828 Ttypeseq265828;
typedef struct Tscope265820 Tscope265820;
typedef struct TY265927 TY265927;
typedef struct Ttype265832 Ttype265832;
typedef struct Tlineinfo187336 Tlineinfo187336;
typedef struct Tnode265794 Tnode265794;
typedef struct Tloc265808 Tloc265808;
typedef struct Ropeobj175006 Ropeobj175006;
typedef struct Tlib265812 Tlib265812;
typedef struct Tidtable265844 Tidtable265844;
typedef struct Tidpairseq265842 Tidpairseq265842;
typedef struct Tidpair265840 Tidpair265840;
typedef struct Cell47704 Cell47704;
typedef struct Cellseq47720 Cellseq47720;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Memregion29886 Memregion29886;
typedef struct Smallchunk29840 Smallchunk29840;
typedef struct Llchunk29880 Llchunk29880;
typedef struct Bigchunk29842 Bigchunk29842;
typedef struct Intset29814 Intset29814;
typedef struct Trunk29810 Trunk29810;
typedef struct Avlnode29884 Avlnode29884;
typedef struct Gcstat50214 Gcstat50214;
typedef struct Cellset47716 Cellset47716;
typedef struct Pagedesc47712 Pagedesc47712;
typedef struct Tnodeseq265788 Tnodeseq265788;
typedef struct Tidentiter272088 Tidentiter272088;
typedef struct Intset242031 Intset242031;
typedef struct Tidnodetable265850 Tidnodetable265850;
typedef struct Tidnodepairseq265848 Tidnodepairseq265848;
typedef struct Tidnodepair265846 Tidnodepair265846;
typedef struct Tinstantiation265816 Tinstantiation265816;
typedef struct Tlistentry145010 Tlistentry145010;
typedef struct Basechunk29838 Basechunk29838;
typedef struct Freecell29830 Freecell29830;
typedef struct Trunk242027 Trunk242027;
typedef struct Trunkseq242029 Trunkseq242029;
typedef struct TY265917 TY265917;
struct  Tiitable272167  {
NI counter;
Tiipairseq272165* data;
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Tiipair272163  {
NI key;
NI val;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  Tstrtable265798  {
NI counter;
Tsymseq265796* data;
};
struct  Ttabiter272075  {
NI h;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Tidobj195006  {
  TNimObject Sup;
NI id;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Tident195012  {
  Tidobj195006 Sup;
NimStringDesc* s;
Tident195012* next;
NI h;
};
typedef NU8 Tsymkind265435;
typedef NU8 Tmagic265525;
struct  Tlineinfo187336  {
NI16 line;
NI16 col;
NI32 fileindex;
};
typedef NU32 Tsymflag265184Set;
typedef NU32 Toption166009Set;
typedef NU8 Tlockind265800;
typedef NU8 Tstorageloc265804;
typedef NU16 Tlocflag265802Set;
struct  Tloc265808  {
Tlockind265800 k;
Tstorageloc265804 s;
Tlocflag265802Set flags;
Ttype265832* t;
Ropeobj175006* r;
Ropeobj175006* heaproot;
};
struct  Tsym265826  {
  Tidobj195006 Sup;
Tsymkind265435 kind;
union{
struct {Ttypeseq265828* typeinstcache;
Tscope265820* typscope;
} S1;
struct {TY265927* procinstcache;
Tsym265826* gcunsafetyreason;
} S2;
struct {TY265927* usedgenerics;
Tstrtable265798 tab;
} S3;
struct {Tsym265826* guard;
NI bitsize;
} S4;
} kindU;
Tmagic265525 magic;
Ttype265832* typ;
Tident195012* name;
Tlineinfo187336 info;
Tsym265826* owner;
Tsymflag265184Set flags;
Tnode265794* ast;
Toption166009Set options;
NI position;
NI offset;
Tloc265808 loc;
Tlib265812* annex;
Tnode265794* constraint;
};
struct  Tidtable265844  {
NI counter;
Tidpairseq265842* data;
};
struct  Tidpair265840  {
Tidobj195006* key;
TNimObject* val;
};
struct  Cell47704  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47720  {
NI len;
NI cap;
Cell47704** d;
};
typedef Smallchunk29840* TY29901[512];
typedef Trunk29810* Trunkbuckets29812[256];
struct  Intset29814  {
Trunkbuckets29812 data;
};
struct  Memregion29886  {
NI minlargeobj;
NI maxlargeobj;
TY29901 freesmallchunks;
Llchunk29880* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29842* freechunkslist;
Intset29814 chunkstarts;
Avlnode29884* root;
Avlnode29884* deleted;
Avlnode29884* last;
Avlnode29884* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat50214  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47716  {
NI counter;
NI max;
Pagedesc47712* head;
Pagedesc47712** data;
};
struct  Gcheap50218  {
Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47720 zct;
Cellseq47720 decstack;
Cellseq47720 tempstack;
NI recgclock;
Memregion29886 region;
Gcstat50214 stat;
Cellset47716 marked;
Cellseq47720 additionalroots;
};
typedef NU16 Tnodeflag265427Set;
typedef NU8 Tnodekind265020;
struct  Tnode265794  {
Ttype265832* typ;
Tlineinfo187336 info;
Tnodeflag265427Set flags;
Tnodekind265020 kind;
union{
struct {NI64 intval;
} S1;
struct {NF floatval;
} S2;
struct {NimStringDesc* strval;
} S3;
struct {Tsym265826* sym;
} S4;
struct {Tident195012* ident;
} S5;
struct {Tnodeseq265788* sons;
} S6;
} kindU;
NimStringDesc* comment;
};
typedef NU8 Tsymflag265184;
struct  Tidentiter272088  {
NI h;
Tident195012* name;
};
typedef NU8 Timplication265862;
struct  Tidnodetable265850  {
NI counter;
Tidnodepairseq265848* data;
};
struct  Tidnodepair265846  {
Tidobj195006* key;
Tnode265794* val;
};
struct  Tscope265820  {
NI depthlevel;
Tstrtable265798 symbols;
Tscope265820* parent;
};
typedef NU8 Ttypekind265244;
typedef NU8 Tcallingconvention265002;
typedef NU32 Ttypeflag265431Set;
struct  Ttype265832  {
  Tidobj195006 Sup;
Ttypekind265244 kind;
Tcallingconvention265002 callconv;
Ttypeflag265431Set flags;
Ttypeseq265828* sons;
Tnode265794* n;
Tsym265826* owner;
Tsym265826* sym;
Tsym265826* destructor;
Tsym265826* deepcopy;
Tsym265826* assignment;
NI64 size;
NI16 align;
NI16 locklevel;
Tloc265808 loc;
};
struct  Ropeobj175006  {
  TNimObject Sup;
Ropeobj175006* left;
Ropeobj175006* right;
NI length;
NimStringDesc* data;
};
struct  Tlistentry145010  {
  TNimObject Sup;
Tlistentry145010* prev;
Tlistentry145010* next;
};
typedef NU8 Tlibkind265810;
struct  Tlib265812  {
  Tlistentry145010 Sup;
Tlibkind265810 kind;
NIM_BOOL generated;
NIM_BOOL isoverriden;
Ropeobj175006* name;
Tnode265794* path;
};
struct  Gcstack50216  {
Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29840  {
  Basechunk29838 Sup;
Smallchunk29840* next;
Smallchunk29840* prev;
Freecell29830* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29880  {
NI size;
NI acc;
Llchunk29880* next;
};
struct  Bigchunk29842  {
  Basechunk29838 Sup;
Bigchunk29842* next;
Bigchunk29842* prev;
NI align;
NF data;
};
typedef NI TY29819[8];
struct  Trunk29810  {
Trunk29810* next;
NI key;
TY29819 bits;
};
typedef Avlnode29884* TY29891[2];
struct  Avlnode29884  {
TY29891 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47712  {
Pagedesc47712* next;
NI key;
TY29819 bits;
};
struct  Intset242031  {
NI counter;
NI max;
Trunk242027* head;
Trunkseq242029* data;
};
struct  Tinstantiation265816  {
Tsym265826* sym;
Ttypeseq265828* concretetypes;
TY265917* usedby;
NI compilesid;
};
struct  Freecell29830  {
Freecell29830* next;
NI zerofield;
};
struct  Trunk242027  {
Trunk242027* next;
NI key;
TY29819 bits;
};
struct Tiipairseq272165 {
  TGenericSeq Sup;
  Tiipair272163 data[SEQ_DECL_SIZE];
};
struct Tidpairseq265842 {
  TGenericSeq Sup;
  Tidpair265840 data[SEQ_DECL_SIZE];
};
struct Tsymseq265796 {
  TGenericSeq Sup;
  Tsym265826* data[SEQ_DECL_SIZE];
};
struct Tidnodepairseq265848 {
  TGenericSeq Sup;
  Tidnodepair265846 data[SEQ_DECL_SIZE];
};
struct Ttypeseq265828 {
  TGenericSeq Sup;
  Ttype265832* data[SEQ_DECL_SIZE];
};
struct TY265927 {
  TGenericSeq Sup;
  Tinstantiation265816* data[SEQ_DECL_SIZE];
};
struct Tnodeseq265788 {
  TGenericSeq Sup;
  Tnode265794* data[SEQ_DECL_SIZE];
};
struct Trunkseq242029 {
  TGenericSeq Sup;
  Trunk242027* data[SEQ_DECL_SIZE];
};
struct TY265917 {
  TGenericSeq Sup;
  NI32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, TMP1000)(void* p, NI op);
N_NIMCALL(Tsym265826*, nextiter_272082_2984716966)(Ttabiter272075* ti0, Tstrtable265798 tab0);
static N_INLINE(NI, nexttry_272155_2984716966)(NI h0, NI maxhash0);
N_NIMCALL(NI, iitablerawget_278162_2984716966)(Tiitable272167 t0, NI key0);
N_NIMCALL(NI, idtablerawget_276599_2984716966)(Tidtable265844 t0, NI key0);
static N_INLINE(void, asgnRef)(void** dest0, void* src0);
static N_INLINE(void, incref_53819_1689653243)(Cell47704* c0);
static N_INLINE(Cell47704*, usrtocell_51840_1689653243)(void* usr0);
static N_INLINE(void, decref_53401_1689653243)(Cell47704* c0);
static N_INLINE(void, rtladdzct_53001_1689653243)(Cell47704* c0);
N_NOINLINE(void, addzct_51817_1689653243)(Cellseq47720* s0, Cell47704* c0);
N_NIMCALL(NIM_BOOL, mustrehash_272151_2984716966)(NI length0, NI counter0);
N_NIMCALL(void*, newSeq)(TNimType* typ0, NI len0);
N_NIMCALL(void, idtablerawinsert_276685_2984716966)(Tidpairseq265842** data0, Tidobj195006* key0, TNimObject* val0);
N_NIMCALL(void, unsureAsgnRef)(void** dest0, void* src0);
N_NIMCALL(NI, sonslen_268351_850551059)(Tnode265794* n0);
N_NIMCALL(Tsym265826*, lookupinrecord_272144_2984716966)(Tnode265794* n0, Tident195012* field0);
N_NIMCALL(void, internalerror_192100_155036129)(Tlineinfo187336 info0, NimStringDesc* errmsg0);
N_NIMCALL(Tnode265794*, lastson_268364_850551059)(Tnode265794* n0);
static N_INLINE(NIM_BOOL, reallysameident_275900_2984716966)(NimStringDesc* a0, NimStringDesc* b0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
N_NIMCALL(void, strtableenlarge_275810_2984716966)(Tstrtable265798* t0);
N_NIMCALL(void, strtablerawinsert_275127_2984716966)(Tsymseq265796** data0, Tsym265826* n0);
N_NIMCALL(void, iitablerawinsert_278176_2984716966)(Tiipairseq272165** data0, NI key0, NI val0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a0, NimStringDesc* b0);
N_NIMCALL(Tsym265826*, nextidentiter_272097_2984716966)(Tidentiter272088* ti0, Tstrtable265798 tab0);
static N_INLINE(NI, cmpStrings)(NimStringDesc* a0, NimStringDesc* b0);
N_NIMCALL(NIM_BOOL, levalue_272238_2984716966)(Tnode265794* a0, Tnode265794* b0);
N_NIMCALL(Tsym265826*, nextidentexcluding_276462_2984716966)(Tidentiter272088* ti0, Tstrtable265798 tab0, Intset242031* excluding0);
N_NIMCALL(NIM_BOOL, contains_242811_2627731572)(Intset242031* s0, NI key0);
N_NIMCALL(NI, idnodetablerawget_277464_2984716966)(Tidnodetable265850 t0, Tidobj195006* key0);
N_NIMCALL(void, idnodetablerawinsert_277504_2984716966)(Tidnodepairseq265848** data0, Tidobj195006* key0, Tnode265794* val0);
N_NIMCALL(void, symtabreplaceraw_275414_2984716966)(Tsymseq265796** data0, Tsym265826* prevsym0, Tsym265826* newsym0);
STRING_LITERAL(TMP1266, "lookupInRecord", 14);
STRING_LITERAL(TMP1267, "lookupInRecord(record case branch)", 34);
STRING_LITERAL(TMP1268, "lookupInRecord()", 16);
STRING_LITERAL(TMP1273, "getSymFromList", 14);
TNimType NTI272167; /* TIITable */
extern TNimType NTI104; /* int */
TNimType NTI272163; /* TIIPair */
TNimType NTI272165; /* TIIPairSeq */
extern Gcheap50218 gch_50258_1689653243;
extern TNimType NTI265842; /* TIdPairSeq */
extern TNimType NTI265796; /* TSymSeq */
extern TNimType NTI265848; /* TIdNodePairSeq */
N_NIMCALL(void, TMP1000)(void* p, NI op) {
	Tiipairseq272165* a;
	NI LOC1;
	a = (Tiipairseq272165*)p;
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

N_NIMCALL(Tsym265826*, nextiter_272082_2984716966)(Ttabiter272075* ti0, Tstrtable265798 tab0) {
	Tsym265826* result0;
	result0 = (Tsym265826*)0;
	result0 = NIM_NIL;
	{
		while (1) {
			if (!((*ti0).h <= (tab0.data ? (tab0.data->Sup.len-1) : -1))) goto LA2;
			result0 = tab0.data->data[(*ti0).h];
			(*ti0).h += ((NI) 1);
			{
				if (!!((result0 == NIM_NIL))) goto LA5;
				goto LA1;
			}
			LA5: ;
		} LA2: ;
	} LA1: ;
	return result0;
}

N_NIMCALL(Tsym265826*, inittabiter_272077_2984716966)(Ttabiter272075* ti0, Tstrtable265798 tab0) {
	Tsym265826* result0;
	result0 = (Tsym265826*)0;
	(*ti0).h = ((NI) 0);
	{
		if (!(tab0.counter == ((NI) 0))) goto LA3;
		result0 = NIM_NIL;
	}
	goto LA1;
	LA3: ;
	{
		result0 = nextiter_272082_2984716966(ti0, tab0);
	}
	LA1: ;
	return result0;
}

static N_INLINE(NI, nexttry_272155_2984716966)(NI h0, NI maxhash0) {
	NI result0;
	result0 = (NI)0;
	result0 = (NI)((NI)((NI)(((NI) 5) * h0) + ((NI) 1)) & maxhash0);
	return result0;
}

N_NIMCALL(Tsym265826*, strtableget_272070_2984716966)(Tstrtable265798 t0, Tident195012* name0) {
	Tsym265826* result0;
	NI h0;
	result0 = (Tsym265826*)0;
	h0 = (NI)((*name0).h & (t0.data ? (t0.data->Sup.len-1) : -1));
	{
		while (1) {
			result0 = t0.data->data[h0];
			{
				if (!(result0 == NIM_NIL)) goto LA5;
				goto LA1;
			}
			LA5: ;
			{
				if (!((*(*result0).name).Sup.id == (*name0).Sup.id)) goto LA9;
				goto LA1;
			}
			LA9: ;
			h0 = nexttry_272155_2984716966(h0, (t0.data ? (t0.data->Sup.len-1) : -1));
		}
	} LA1: ;
	return result0;
}

N_NIMCALL(NI, iitablerawget_278162_2984716966)(Tiitable272167 t0, NI key0) {
	NI result0;
	NI h0;
{	result0 = (NI)0;
	h0 = (NI)0;
	h0 = (NI)(key0 & (t0.data ? (t0.data->Sup.len-1) : -1));
	{
		while (1) {
			if (!!((t0.data->data[h0].key == ((NI) (IL64(-9223372036854775807) - IL64(1)))))) goto LA2;
			{
				if (!(t0.data->data[h0].key == key0)) goto LA5;
				result0 = h0;
				goto BeforeRet;
			}
			LA5: ;
			h0 = nexttry_272155_2984716966(h0, (t0.data ? (t0.data->Sup.len-1) : -1));
		} LA2: ;
	}
	result0 = ((NI) -1);
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, iitableget_272177_2984716966)(Tiitable272167 t0, NI key0) {
	NI result0;
	NI index0;
	result0 = (NI)0;
	index0 = iitablerawget_278162_2984716966(t0, key0);
	{
		if (!(((NI) 0) <= index0)) goto LA3;
		result0 = t0.data->data[index0].val;
	}
	goto LA1;
	LA3: ;
	{
		result0 = ((NI) (IL64(-9223372036854775807) - IL64(1)));
	}
	LA1: ;
	return result0;
}

N_NIMCALL(NI, idtablerawget_276599_2984716966)(Tidtable265844 t0, NI key0) {
	NI result0;
	NI h0;
{	result0 = (NI)0;
	h0 = (NI)0;
	h0 = (NI)(key0 & (t0.data ? (t0.data->Sup.len-1) : -1));
	{
		while (1) {
			if (!!((t0.data->data[h0].key == NIM_NIL))) goto LA2;
			{
				if (!((*t0.data->data[h0].key).id == key0)) goto LA5;
				result0 = h0;
				goto BeforeRet;
			}
			LA5: ;
			h0 = nexttry_272155_2984716966(h0, (t0.data ? (t0.data->Sup.len-1) : -1));
		} LA2: ;
	}
	result0 = ((NI) -1);
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(TNimObject*, idtableget_272115_2984716966)(Tidtable265844 t0, NI key0) {
	TNimObject* result0;
	NI index0;
	result0 = (TNimObject*)0;
	index0 = idtablerawget_276599_2984716966(t0, key0);
	{
		if (!(((NI) 0) <= index0)) goto LA3;
		result0 = t0.data->data[index0].val;
	}
	goto LA1;
	LA3: ;
	{
		result0 = NIM_NIL;
	}
	LA1: ;
	return result0;
}

static N_INLINE(void, incref_53819_1689653243)(Cell47704* c0) {
	(*c0).refcount = (NI)((NU64)((*c0).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(Cell47704*, usrtocell_51840_1689653243)(void* usr0) {
	Cell47704* result0;
	result0 = (Cell47704*)0;
	result0 = ((Cell47704*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell47704))))));
	return result0;
}

static N_INLINE(void, rtladdzct_53001_1689653243)(Cell47704* c0) {
	addzct_51817_1689653243((&gch_50258_1689653243.zct), c0);
}

static N_INLINE(void, decref_53401_1689653243)(Cell47704* c0) {
	{
		(*c0).refcount -= ((NI) 8);
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_53001_1689653243(c0);
	}
	LA3: ;
}

static N_INLINE(void, asgnRef)(void** dest0, void* src0) {
	{
		Cell47704* LOC5;
		if (!!((src0 == NIM_NIL))) goto LA3;
		LOC5 = (Cell47704*)0;
		LOC5 = usrtocell_51840_1689653243(src0);
		incref_53819_1689653243(LOC5);
	}
	LA3: ;
	{
		Cell47704* LOC10;
		if (!!(((*dest0) == NIM_NIL))) goto LA8;
		LOC10 = (Cell47704*)0;
		LOC10 = usrtocell_51840_1689653243((*dest0));
		decref_53401_1689653243(LOC10);
	}
	LA8: ;
	(*dest0) = src0;
}

N_NIMCALL(NIM_BOOL, mustrehash_272151_2984716966)(NI length0, NI counter0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	result0 = (NIM_BOOL)0;
	LOC1 = (NIM_BOOL)0;
	LOC1 = ((NI)(length0 * ((NI) 2)) < (NI)(counter0 * ((NI) 3)));
	if (LOC1) goto LA2;
	LOC1 = ((NI)(length0 - counter0) < ((NI) 4));
	LA2: ;
	result0 = LOC1;
	return result0;
}

N_NIMCALL(void, idtablerawinsert_276685_2984716966)(Tidpairseq265842** data0, Tidobj195006* key0, TNimObject* val0) {
	NI h0;
	h0 = (NI)0;
	h0 = (NI)((*key0).id & ((*data0) ? ((*data0)->Sup.len-1) : -1));
	{
		while (1) {
			if (!!(((*data0)->data[h0].key == NIM_NIL))) goto LA2;
			h0 = nexttry_272155_2984716966(h0, ((*data0) ? ((*data0)->Sup.len-1) : -1));
		} LA2: ;
	}
	asgnRef((void**) (&(*data0)->data[h0].key), key0);
	asgnRef((void**) (&(*data0)->data[h0].val), val0);
}

N_NIMCALL(void, idtableput_272119_2984716966)(Tidtable265844* t0, Tidobj195006* key0, TNimObject* val0) {
	NI index0;
	Tidpairseq265842* n0;
	index0 = (NI)0;
	n0 = (Tidpairseq265842*)0;
	index0 = idtablerawget_276599_2984716966((*t0), (*key0).id);
	{
		if (!(((NI) 0) <= index0)) goto LA3;
		asgnRef((void**) (&(*t0).data->data[index0].val), val0);
	}
	goto LA1;
	LA3: ;
	{
		{
			NIM_BOOL LOC8;
			Tidpairseq265842* LOC18;
			LOC8 = (NIM_BOOL)0;
			LOC8 = mustrehash_272151_2984716966(((*t0).data ? (*t0).data->Sup.len : 0), (*t0).counter);
			if (!LOC8) goto LA9;
			n0 = (Tidpairseq265842*) newSeq((&NTI265842), ((NI) ((NI)(((*t0).data ? (*t0).data->Sup.len : 0) * ((NI) 2)))));
			{
				NI i_277238_2984716966;
				NI HEX3Atmp_277424_2984716966;
				NI res_277427_2984716966;
				i_277238_2984716966 = (NI)0;
				HEX3Atmp_277424_2984716966 = (NI)0;
				HEX3Atmp_277424_2984716966 = ((*t0).data ? ((*t0).data->Sup.len-1) : -1);
				res_277427_2984716966 = ((NI) 0);
				{
					while (1) {
						if (!(res_277427_2984716966 <= HEX3Atmp_277424_2984716966)) goto LA13;
						i_277238_2984716966 = res_277427_2984716966;
						{
							if (!!(((*t0).data->data[i_277238_2984716966].key == NIM_NIL))) goto LA16;
							idtablerawinsert_276685_2984716966((&n0), (*t0).data->data[i_277238_2984716966].key, (*t0).data->data[i_277238_2984716966].val);
						}
						LA16: ;
						res_277427_2984716966 += ((NI) 1);
					} LA13: ;
				}
			}
			LOC18 = (Tidpairseq265842*)0;
			LOC18 = (*t0).data;
			unsureAsgnRef((void**) (&(*t0).data), n0);
			n0 = LOC18;
		}
		LA9: ;
		idtablerawinsert_276685_2984716966((&(*t0).data), key0, val0);
		(*t0).counter += ((NI) 1);
	}
	LA1: ;
}

N_NIMCALL(Tsym265826*, lookupinrecord_272144_2984716966)(Tnode265794* n0, Tident195012* field0) {
	Tsym265826* result0;
{	result0 = (Tsym265826*)0;
	result0 = NIM_NIL;
	switch ((*n0).kind) {
	case ((Tnodekind265020) 138):
	{
		{
			NI i_272323_2984716966;
			NI HEX3Atmp_272390_2984716966;
			NI LOC3;
			NI res_272393_2984716966;
			i_272323_2984716966 = (NI)0;
			HEX3Atmp_272390_2984716966 = (NI)0;
			LOC3 = (NI)0;
			LOC3 = sonslen_268351_850551059(n0);
			HEX3Atmp_272390_2984716966 = (NI)(LOC3 - ((NI) 1));
			res_272393_2984716966 = ((NI) 0);
			{
				while (1) {
					if (!(res_272393_2984716966 <= HEX3Atmp_272390_2984716966)) goto LA5;
					i_272323_2984716966 = res_272393_2984716966;
					result0 = lookupinrecord_272144_2984716966((*n0).kindU.S6.sons->data[i_272323_2984716966], field0);
					{
						if (!!((result0 == NIM_NIL))) goto LA8;
						goto BeforeRet;
					}
					LA8: ;
					res_272393_2984716966 += ((NI) 1);
				} LA5: ;
			}
		}
	}
	break;
	case ((Tnodekind265020) 139):
	{
		{
			if (!!(((*(*n0).kindU.S6.sons->data[((NI) 0)]).kind == ((Tnodekind265020) 3)))) goto LA13;
			internalerror_192100_155036129((*n0).info, ((NimStringDesc*) &TMP1266));
		}
		LA13: ;
		result0 = lookupinrecord_272144_2984716966((*n0).kindU.S6.sons->data[((NI) 0)], field0);
		{
			if (!!((result0 == NIM_NIL))) goto LA17;
			goto BeforeRet;
		}
		LA17: ;
		{
			NI i_272371_2984716966;
			NI HEX3Atmp_272398_2984716966;
			NI LOC20;
			NI res_272401_2984716966;
			i_272371_2984716966 = (NI)0;
			HEX3Atmp_272398_2984716966 = (NI)0;
			LOC20 = (NI)0;
			LOC20 = sonslen_268351_850551059(n0);
			HEX3Atmp_272398_2984716966 = (NI)(LOC20 - ((NI) 1));
			res_272401_2984716966 = ((NI) 1);
			{
				while (1) {
					if (!(res_272401_2984716966 <= HEX3Atmp_272398_2984716966)) goto LA22;
					i_272371_2984716966 = res_272401_2984716966;
					switch ((*(*n0).kindU.S6.sons->data[i_272371_2984716966]).kind) {
					case ((Tnodekind265020) 85):
					case ((Tnodekind265020) 88):
					{
						Tnode265794* LOC24;
						LOC24 = (Tnode265794*)0;
						LOC24 = lastson_268364_850551059((*n0).kindU.S6.sons->data[i_272371_2984716966]);
						result0 = lookupinrecord_272144_2984716966(LOC24, field0);
						{
							if (!!((result0 == NIM_NIL))) goto LA27;
							goto BeforeRet;
						}
						LA27: ;
					}
					break;
					default:
					{
						internalerror_192100_155036129((*n0).info, ((NimStringDesc*) &TMP1267));
					}
					break;
					}
					res_272401_2984716966 += ((NI) 1);
				} LA22: ;
			}
		}
	}
	break;
	case ((Tnodekind265020) 3):
	{
		{
			if (!((*(*(*n0).kindU.S4.sym).name).Sup.id == (*field0).Sup.id)) goto LA33;
			result0 = (*n0).kindU.S4.sym;
		}
		LA33: ;
	}
	break;
	default:
	{
		internalerror_192100_155036129((*n0).info, ((NimStringDesc*) &TMP1268));
	}
	break;
	}
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(Tsym265826*, getsymfromlist_272139_2984716966)(Tnode265794* list0, Tident195012* ident0, NI start0) {
	Tsym265826* result0;
{	result0 = (Tsym265826*)0;
	{
		NI i_272641_2984716966;
		NI HEX3Atmp_272656_2984716966;
		NI LOC2;
		NI res_272659_2984716966;
		i_272641_2984716966 = (NI)0;
		HEX3Atmp_272656_2984716966 = (NI)0;
		LOC2 = (NI)0;
		LOC2 = sonslen_268351_850551059(list0);
		HEX3Atmp_272656_2984716966 = (NI)(LOC2 - ((NI) 1));
		res_272659_2984716966 = start0;
		{
			while (1) {
				if (!(res_272659_2984716966 <= HEX3Atmp_272656_2984716966)) goto LA4;
				i_272641_2984716966 = res_272659_2984716966;
				{
					if (!((*(*list0).kindU.S6.sons->data[i_272641_2984716966]).kind == ((Tnodekind265020) 3))) goto LA7;
					result0 = (*(*list0).kindU.S6.sons->data[i_272641_2984716966]).kindU.S4.sym;
					{
						if (!((*(*result0).name).Sup.id == (*ident0).Sup.id)) goto LA11;
						goto BeforeRet;
					}
					LA11: ;
				}
				goto LA5;
				LA7: ;
				{
					internalerror_192100_155036129((*list0).info, ((NimStringDesc*) &TMP1273));
				}
				LA5: ;
				res_272659_2984716966 += ((NI) 1);
			} LA4: ;
		}
	}
	result0 = NIM_NIL;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NIM_BOOL, reallysameident_275900_2984716966)(NimStringDesc* a0, NimStringDesc* b0) {
	NIM_BOOL result0;
	result0 = (NIM_BOOL)0;
	result0 = NIM_TRUE;
	return result0;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	{
		Cell47704* c0;
		if (!!((src0 == NIM_NIL))) goto LA3;
		c0 = usrtocell_51840_1689653243(src0);
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	{
		Cell47704* c0;
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		c0 = usrtocell_51840_1689653243((*dest0));
		{
			(*c0).refcount -= ((NI) 8);
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			rtladdzct_53001_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	(*dest0) = src0;
}

N_NIMCALL(void, strtablerawinsert_275127_2984716966)(Tsymseq265796** data0, Tsym265826* n0) {
	NI h0;
{	h0 = (NI)((*(*n0).name).h & ((*data0) ? ((*data0)->Sup.len-1) : -1));
	{
		if (!!((((*n0).flags &(1U<<((NU)(((Tsymflag265184) 25))&31U)))!=0))) goto LA3;
		{
			while (1) {
				if (!!(((*data0)->data[h0] == NIM_NIL))) goto LA6;
				{
					if (!((*data0)->data[h0] == n0)) goto LA9;
					goto BeforeRet;
				}
				LA9: ;
				h0 = nexttry_272155_2984716966(h0, ((*data0) ? ((*data0)->Sup.len-1) : -1));
			} LA6: ;
		}
		asgnRefNoCycle((void**) (&(*data0)->data[h0]), n0);
	}
	goto LA1;
	LA3: ;
	{
		NI favpos0;
		favpos0 = ((NI) -1);
		{
			while (1) {
				if (!!(((*data0)->data[h0] == NIM_NIL))) goto LA13;
				{
					if (!((*data0)->data[h0] == n0)) goto LA16;
					goto BeforeRet;
				}
				LA16: ;
				{
					NIM_BOOL LOC20;
					LOC20 = (NIM_BOOL)0;
					LOC20 = (favpos0 < ((NI) 0));
					if (!(LOC20)) goto LA21;
					LOC20 = ((*(*(*data0)->data[h0]).name).Sup.id == (*(*n0).name).Sup.id);
					LA21: ;
					if (!LOC20) goto LA22;
					favpos0 = h0;
				}
				LA22: ;
				h0 = nexttry_272155_2984716966(h0, ((*data0) ? ((*data0)->Sup.len-1) : -1));
			} LA13: ;
		}
		asgnRefNoCycle((void**) (&(*data0)->data[h0]), n0);
		{
			Tsym265826* LOC28;
			if (!(((NI) 0) <= favpos0)) goto LA26;
			LOC28 = (Tsym265826*)0;
			LOC28 = (*data0)->data[h0];
			asgnRefNoCycle((void**) (&(*data0)->data[h0]), (*data0)->data[favpos0]);
			asgnRefNoCycle((void**) (&(*data0)->data[favpos0]), LOC28);
		}
		LA26: ;
	}
	LA1: ;
	}BeforeRet: ;
}

N_NIMCALL(void, strtableenlarge_275810_2984716966)(Tstrtable265798* t0) {
	Tsymseq265796* n0;
	Tsymseq265796* LOC8;
	n0 = (Tsymseq265796*)0;
	n0 = (Tsymseq265796*) newSeq((&NTI265796), ((NI) ((NI)(((*t0).data ? (*t0).data->Sup.len : 0) * ((NI) 2)))));
	{
		NI i_275844_2984716966;
		NI HEX3Atmp_275870_2984716966;
		NI res_275873_2984716966;
		i_275844_2984716966 = (NI)0;
		HEX3Atmp_275870_2984716966 = (NI)0;
		HEX3Atmp_275870_2984716966 = ((*t0).data ? ((*t0).data->Sup.len-1) : -1);
		res_275873_2984716966 = ((NI) 0);
		{
			while (1) {
				if (!(res_275873_2984716966 <= HEX3Atmp_275870_2984716966)) goto LA3;
				i_275844_2984716966 = res_275873_2984716966;
				{
					if (!!(((*t0).data->data[i_275844_2984716966] == NIM_NIL))) goto LA6;
					strtablerawinsert_275127_2984716966((&n0), (*t0).data->data[i_275844_2984716966]);
				}
				LA6: ;
				res_275873_2984716966 += ((NI) 1);
			} LA3: ;
		}
	}
	LOC8 = (Tsymseq265796*)0;
	LOC8 = (*t0).data;
	unsureAsgnRef((void**) (&(*t0).data), n0);
	n0 = LOC8;
}

N_NIMCALL(NIM_BOOL, strtableincl_276001_2984716966)(Tstrtable265798* t0, Tsym265826* n0, NIM_BOOL onconflictkeepold0) {
	NIM_BOOL result0;
	NI h0;
	NI replaceslot0;
{	result0 = (NIM_BOOL)0;
	h0 = (NI)((*(*n0).name).h & ((*t0).data ? ((*t0).data->Sup.len-1) : -1));
	replaceslot0 = ((NI) -1);
	{
		while (1) {
			Tsym265826* it0;
			it0 = (*t0).data->data[h0];
			{
				if (!(it0 == NIM_NIL)) goto LA5;
				goto LA1;
			}
			LA5: ;
			{
				NIM_BOOL LOC9;
				LOC9 = (NIM_BOOL)0;
				LOC9 = ((*(*it0).name).Sup.id == (*(*n0).name).Sup.id);
				if (!(LOC9)) goto LA10;
				LOC9 = reallysameident_275900_2984716966((*(*it0).name).s, (*(*n0).name).s);
				LA10: ;
				if (!LOC9) goto LA11;
				{
					if (!(it0 == n0)) goto LA15;
					result0 = NIM_FALSE;
					goto BeforeRet;
				}
				LA15: ;
				replaceslot0 = h0;
			}
			LA11: ;
			h0 = nexttry_272155_2984716966(h0, ((*t0).data ? ((*t0).data->Sup.len-1) : -1));
		}
	} LA1: ;
	{
		if (!(((NI) 0) <= replaceslot0)) goto LA19;
		{
			if (!!(onconflictkeepold0)) goto LA23;
			asgnRefNoCycle((void**) (&(*t0).data->data[replaceslot0]), n0);
		}
		LA23: ;
		result0 = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA17;
	LA19: ;
	{
		NIM_BOOL LOC26;
		LOC26 = (NIM_BOOL)0;
		LOC26 = mustrehash_272151_2984716966(((*t0).data ? (*t0).data->Sup.len : 0), (*t0).counter);
		if (!LOC26) goto LA27;
		strtableenlarge_275810_2984716966(t0);
		strtablerawinsert_275127_2984716966((&(*t0).data), n0);
	}
	goto LA17;
	LA27: ;
	{
		asgnRefNoCycle((void**) (&(*t0).data->data[h0]), n0);
	}
	LA17: ;
	(*t0).counter += ((NI) 1);
	result0 = NIM_FALSE;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, strtableadd_272065_2984716966)(Tstrtable265798* t0, Tsym265826* n0) {
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = mustrehash_272151_2984716966(((*t0).data ? (*t0).data->Sup.len : 0), (*t0).counter);
		if (!LOC3) goto LA4;
		strtableenlarge_275810_2984716966(t0);
	}
	LA4: ;
	strtablerawinsert_275127_2984716966((&(*t0).data), n0);
	(*t0).counter += ((NI) 1);
}

N_NIMCALL(void, initiitable_272173_2984716966)(Tiitable272167* x0) {
	(*x0).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*x0).data), (Tiipairseq272165*) newSeq((&NTI272165), ((NI) 8)));
	{
		NI i_278154_2984716966;
		NI res_278158_2984716966;
		i_278154_2984716966 = (NI)0;
		res_278158_2984716966 = ((NI) 0);
		{
			while (1) {
				if (!(res_278158_2984716966 <= ((NI) 7))) goto LA3;
				i_278154_2984716966 = res_278158_2984716966;
				(*x0).data->data[i_278154_2984716966].key = ((NI) (IL64(-9223372036854775807) - IL64(1)));
				res_278158_2984716966 += ((NI) 1);
			} LA3: ;
		}
	}
}

N_NIMCALL(void, iitablerawinsert_278176_2984716966)(Tiipairseq272165** data0, NI key0, NI val0) {
	NI h0;
	h0 = (NI)0;
	h0 = (NI)(key0 & ((*data0) ? ((*data0)->Sup.len-1) : -1));
	{
		while (1) {
			if (!!(((*data0)->data[h0].key == ((NI) (IL64(-9223372036854775807) - IL64(1)))))) goto LA2;
			h0 = nexttry_272155_2984716966(h0, ((*data0) ? ((*data0)->Sup.len-1) : -1));
		} LA2: ;
	}
	(*data0)->data[h0].key = key0;
	(*data0)->data[h0].val = val0;
}

N_NIMCALL(void, iitableput_272181_2984716966)(Tiitable272167* t0, NI key0, NI val0) {
	NI index0;
	index0 = iitablerawget_278162_2984716966((*t0), key0);
	{
		if (!(((NI) 0) <= index0)) goto LA3;
		(*t0).data->data[index0].val = val0;
	}
	goto LA1;
	LA3: ;
	{
		{
			NIM_BOOL LOC8;
			Tiipairseq272165* n0;
			Tiipairseq272165* LOC21;
			LOC8 = (NIM_BOOL)0;
			LOC8 = mustrehash_272151_2984716966(((*t0).data ? (*t0).data->Sup.len : 0), (*t0).counter);
			if (!LOC8) goto LA9;
			n0 = (Tiipairseq272165*)0;
			n0 = (Tiipairseq272165*) newSeq((&NTI272165), ((NI) ((NI)(((*t0).data ? (*t0).data->Sup.len : 0) * ((NI) 2)))));
			{
				NI i_278639_2984716966;
				NI HEX3Atmp_278675_2984716966;
				NI res_278678_2984716966;
				i_278639_2984716966 = (NI)0;
				HEX3Atmp_278675_2984716966 = (NI)0;
				HEX3Atmp_278675_2984716966 = (n0 ? (n0->Sup.len-1) : -1);
				res_278678_2984716966 = ((NI) 0);
				{
					while (1) {
						if (!(res_278678_2984716966 <= HEX3Atmp_278675_2984716966)) goto LA13;
						i_278639_2984716966 = res_278678_2984716966;
						n0->data[i_278639_2984716966].key = ((NI) (IL64(-9223372036854775807) - IL64(1)));
						res_278678_2984716966 += ((NI) 1);
					} LA13: ;
				}
			}
			{
				NI i_278651_2984716966;
				NI HEX3Atmp_278683_2984716966;
				NI res_278686_2984716966;
				i_278651_2984716966 = (NI)0;
				HEX3Atmp_278683_2984716966 = (NI)0;
				HEX3Atmp_278683_2984716966 = ((*t0).data ? ((*t0).data->Sup.len-1) : -1);
				res_278686_2984716966 = ((NI) 0);
				{
					while (1) {
						if (!(res_278686_2984716966 <= HEX3Atmp_278683_2984716966)) goto LA16;
						i_278651_2984716966 = res_278686_2984716966;
						{
							if (!!(((*t0).data->data[i_278651_2984716966].key == ((NI) (IL64(-9223372036854775807) - IL64(1)))))) goto LA19;
							iitablerawinsert_278176_2984716966((&n0), (*t0).data->data[i_278651_2984716966].key, (*t0).data->data[i_278651_2984716966].val);
						}
						LA19: ;
						res_278686_2984716966 += ((NI) 1);
					} LA16: ;
				}
			}
			LOC21 = (Tiipairseq272165*)0;
			LOC21 = (*t0).data;
			unsureAsgnRef((void**) (&(*t0).data), n0);
			n0 = LOC21;
		}
		LA9: ;
		iitablerawinsert_278176_2984716966((&(*t0).data), key0, val0);
		(*t0).counter += ((NI) 1);
	}
	LA1: ;
}

N_NIMCALL(Tsym265826*, getmodule_272148_2984716966)(Tsym265826* s0) {
	Tsym265826* result0;
	result0 = (Tsym265826*)0;
	result0 = s0;
	{
		while (1) {
			NIM_BOOL LOC3;
			LOC3 = (NIM_BOOL)0;
			LOC3 = !((result0 == NIM_NIL));
			if (!(LOC3)) goto LA4;
			LOC3 = !(((*result0).kind == ((Tsymkind265435) 6)));
			LA4: ;
			if (!LOC3) goto LA2;
			result0 = (*result0).owner;
		} LA2: ;
	}
	return result0;
}

N_NIMCALL(TNimObject*, idtableget_272111_2984716966)(Tidtable265844 t0, Tidobj195006* key0) {
	TNimObject* result0;
	NI index0;
	result0 = (TNimObject*)0;
	index0 = idtablerawget_276599_2984716966(t0, (*key0).id);
	{
		if (!(((NI) 0) <= index0)) goto LA3;
		result0 = t0.data->data[index0].val;
	}
	goto LA1;
	LA3: ;
	{
		result0 = NIM_NIL;
	}
	LA1: ;
	return result0;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a0, NimStringDesc* b0) {
	NIM_BOOL result0;
	NIM_BOOL LOC11;
	int LOC13;
{	result0 = (NIM_BOOL)0;
	{
		if (!(a0 == b0)) goto LA3;
		result0 = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b0 == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result0 = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = (NIM_BOOL)0;
	LOC11 = ((*a0).Sup.len == (*b0).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = (int)0;
	LOC13 = memcmp(((NCSTRING) ((*a0).data)), ((NCSTRING) ((*b0).data)), (*a0).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result0 = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_BOOL, samevalue_272194_2984716966)(Tnode265794* a0, Tnode265794* b0) {
	NIM_BOOL result0;
	result0 = (NIM_BOOL)0;
	result0 = NIM_FALSE;
	switch ((*a0).kind) {
	case ((Tnodekind265020) 5) ... ((Tnodekind265020) 15):
	{
		{
			if (!((*b0).kind >= ((Tnodekind265020) 5) && (*b0).kind <= ((Tnodekind265020) 15))) goto LA4;
			result0 = ((*a0).kindU.S1.intval == (*b0).kindU.S1.intval);
		}
		LA4: ;
	}
	break;
	case ((Tnodekind265020) 16) ... ((Tnodekind265020) 18):
	{
		{
			if (!((*b0).kind >= ((Tnodekind265020) 16) && (*b0).kind <= ((Tnodekind265020) 18))) goto LA9;
			result0 = ((*a0).kindU.S2.floatval == (*b0).kindU.S2.floatval);
		}
		LA9: ;
	}
	break;
	case ((Tnodekind265020) 20) ... ((Tnodekind265020) 22):
	{
		{
			if (!((*b0).kind >= ((Tnodekind265020) 20) && (*b0).kind <= ((Tnodekind265020) 22))) goto LA14;
			result0 = eqStrings((*a0).kindU.S3.strval, (*b0).kindU.S3.strval);
		}
		LA14: ;
	}
	break;
	default:
	{
	}
	break;
	}
	return result0;
}

N_NIMCALL(Tsym265826*, nextidentiter_272097_2984716966)(Tidentiter272088* ti0, Tstrtable265798 tab0) {
	Tsym265826* result0;
	NI h0;
	NI start0;
	result0 = (Tsym265826*)0;
	h0 = (NI)((*ti0).h & (tab0.data ? (tab0.data->Sup.len-1) : -1));
	start0 = h0;
	result0 = tab0.data->data[h0];
	{
		while (1) {
			if (!!((result0 == NIM_NIL))) goto LA2;
			{
				if (!((*(*result0).name).Sup.id == (*(*ti0).name).Sup.id)) goto LA5;
				goto LA1;
			}
			LA5: ;
			h0 = nexttry_272155_2984716966(h0, (tab0.data ? (tab0.data->Sup.len-1) : -1));
			{
				if (!(h0 == start0)) goto LA9;
				result0 = NIM_NIL;
				goto LA1;
			}
			LA9: ;
			result0 = tab0.data->data[h0];
		} LA2: ;
	} LA1: ;
	(*ti0).h = nexttry_272155_2984716966(h0, (tab0.data ? (tab0.data->Sup.len-1) : -1));
	return result0;
}

N_NIMCALL(Tsym265826*, initidentiter_272091_2984716966)(Tidentiter272088* ti0, Tstrtable265798 tab0, Tident195012* s0) {
	Tsym265826* result0;
	result0 = (Tsym265826*)0;
	(*ti0).h = (*s0).h;
	unsureAsgnRef((void**) (&(*ti0).name), s0);
	{
		if (!(tab0.counter == ((NI) 0))) goto LA3;
		result0 = NIM_NIL;
	}
	goto LA1;
	LA3: ;
	{
		result0 = nextidentiter_272097_2984716966(ti0, tab0);
	}
	LA1: ;
	return result0;
}

static N_INLINE(NI, cmpStrings)(NimStringDesc* a0, NimStringDesc* b0) {
	NI result0;
	int LOC13;
{	result0 = (NI)0;
	{
		if (!(a0 == b0)) goto LA3;
		result0 = ((NI) 0);
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!(a0 == NIM_NIL)) goto LA7;
		result0 = ((NI) -1);
		goto BeforeRet;
	}
	LA7: ;
	{
		if (!(b0 == NIM_NIL)) goto LA11;
		result0 = ((NI) 1);
		goto BeforeRet;
	}
	LA11: ;
	LOC13 = (int)0;
	LOC13 = strcmp(((NCSTRING) ((*a0).data)), ((NCSTRING) ((*b0).data)));
	result0 = ((NI) (LOC13));
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_BOOL, levalue_272238_2984716966)(Tnode265794* a0, Tnode265794* b0) {
	NIM_BOOL result0;
	result0 = (NIM_BOOL)0;
	result0 = NIM_FALSE;
	switch ((*a0).kind) {
	case ((Tnodekind265020) 5) ... ((Tnodekind265020) 14):
	{
		{
			if (!((*b0).kind >= ((Tnodekind265020) 5) && (*b0).kind <= ((Tnodekind265020) 14))) goto LA4;
			result0 = ((*a0).kindU.S1.intval <= (*b0).kindU.S1.intval);
		}
		LA4: ;
	}
	break;
	case ((Tnodekind265020) 16) ... ((Tnodekind265020) 18):
	{
		{
			if (!((*b0).kind >= ((Tnodekind265020) 16) && (*b0).kind <= ((Tnodekind265020) 18))) goto LA9;
			result0 = ((*a0).kindU.S2.floatval <= (*b0).kindU.S2.floatval);
		}
		LA9: ;
	}
	break;
	case ((Tnodekind265020) 20) ... ((Tnodekind265020) 22):
	{
		{
			if (!((*b0).kind >= ((Tnodekind265020) 20) && (*b0).kind <= ((Tnodekind265020) 22))) goto LA14;
			result0 = (cmpStrings((*a0).kindU.S3.strval, (*b0).kindU.S3.strval) <= 0);
		}
		LA14: ;
	}
	break;
	default:
	{
	}
	break;
	}
	return result0;
}

N_NIMCALL(Timplication265862, weaklevalue_272282_2984716966)(Tnode265794* a0, Tnode265794* b0) {
	Timplication265862 result0;
	result0 = (Timplication265862)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = !(((*a0).kind >= ((Tnodekind265020) 5) && (*a0).kind <= ((Tnodekind265020) 22)));
		if (LOC3) goto LA4;
		LOC3 = !(((*b0).kind >= ((Tnodekind265020) 5) && (*b0).kind <= ((Tnodekind265020) 22)));
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = ((Timplication265862) 0);
	}
	goto LA1;
	LA5: ;
	{
		{
			NIM_BOOL LOC10;
			LOC10 = (NIM_BOOL)0;
			LOC10 = levalue_272238_2984716966(a0, b0);
			if (!LOC10) goto LA11;
			result0 = ((Timplication265862) 2);
		}
		goto LA8;
		LA11: ;
		{
			result0 = ((Timplication265862) 1);
		}
		LA8: ;
	}
	LA1: ;
	return result0;
}

N_NIMCALL(Tsym265826*, nextidentexcluding_276462_2984716966)(Tidentiter272088* ti0, Tstrtable265798 tab0, Intset242031* excluding0) {
	Tsym265826* result0;
	NI h0;
	NI start0;
	result0 = (Tsym265826*)0;
	h0 = (NI)((*ti0).h & (tab0.data ? (tab0.data->Sup.len-1) : -1));
	start0 = h0;
	result0 = tab0.data->data[h0];
	{
		while (1) {
			if (!!((result0 == NIM_NIL))) goto LA2;
			{
				NIM_BOOL LOC5;
				NIM_BOOL LOC7;
				LOC5 = (NIM_BOOL)0;
				LOC5 = ((*(*result0).name).Sup.id == (*(*ti0).name).Sup.id);
				if (!(LOC5)) goto LA6;
				LOC7 = (NIM_BOOL)0;
				LOC7 = contains_242811_2627731572(excluding0, (*result0).Sup.id);
				LOC5 = !(LOC7);
				LA6: ;
				if (!LOC5) goto LA8;
				goto LA1;
			}
			LA8: ;
			h0 = nexttry_272155_2984716966(h0, (tab0.data ? (tab0.data->Sup.len-1) : -1));
			{
				if (!(h0 == start0)) goto LA12;
				result0 = NIM_NIL;
				goto LA1;
			}
			LA12: ;
			result0 = tab0.data->data[h0];
		} LA2: ;
	} LA1: ;
	(*ti0).h = nexttry_272155_2984716966(h0, (tab0.data ? (tab0.data->Sup.len-1) : -1));
	{
		NIM_BOOL LOC16;
		LOC16 = (NIM_BOOL)0;
		LOC16 = !((result0 == NIM_NIL));
		if (!(LOC16)) goto LA17;
		LOC16 = contains_242811_2627731572(excluding0, (*result0).Sup.id);
		LA17: ;
		if (!LOC16) goto LA18;
		result0 = NIM_NIL;
	}
	LA18: ;
	return result0;
}

N_NIMCALL(Tsym265826*, firstidentexcluding_276500_2984716966)(Tidentiter272088* ti0, Tstrtable265798 tab0, Tident195012* s0, Intset242031* excluding0) {
	Tsym265826* result0;
	result0 = (Tsym265826*)0;
	(*ti0).h = (*s0).h;
	unsureAsgnRef((void**) (&(*ti0).name), s0);
	{
		if (!(tab0.counter == ((NI) 0))) goto LA3;
		result0 = NIM_NIL;
	}
	goto LA1;
	LA3: ;
	{
		result0 = nextidentexcluding_276462_2984716966(ti0, tab0, excluding0);
	}
	LA1: ;
	return result0;
}

N_NIMCALL(NI, idnodetablerawget_277464_2984716966)(Tidnodetable265850 t0, Tidobj195006* key0) {
	NI result0;
	NI h0;
{	result0 = (NI)0;
	h0 = (NI)0;
	h0 = (NI)((*key0).id & (t0.data ? (t0.data->Sup.len-1) : -1));
	{
		while (1) {
			if (!!((t0.data->data[h0].key == NIM_NIL))) goto LA2;
			{
				if (!((*t0.data->data[h0].key).id == (*key0).id)) goto LA5;
				result0 = h0;
				goto BeforeRet;
			}
			LA5: ;
			h0 = nexttry_272155_2984716966(h0, (t0.data ? (t0.data->Sup.len-1) : -1));
		} LA2: ;
	}
	result0 = ((NI) -1);
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(Tnode265794*, idnodetableget_272129_2984716966)(Tidnodetable265850 t0, Tidobj195006* key0) {
	Tnode265794* result0;
	NI index0;
	result0 = (Tnode265794*)0;
	index0 = (NI)0;
	index0 = idnodetablerawget_277464_2984716966(t0, key0);
	{
		if (!(((NI) 0) <= index0)) goto LA3;
		result0 = t0.data->data[index0].val;
	}
	goto LA1;
	LA3: ;
	{
		result0 = NIM_NIL;
	}
	LA1: ;
	return result0;
}

N_NIMCALL(void, idnodetablerawinsert_277504_2984716966)(Tidnodepairseq265848** data0, Tidobj195006* key0, Tnode265794* val0) {
	NI h0;
	h0 = (NI)0;
	h0 = (NI)((*key0).id & ((*data0) ? ((*data0)->Sup.len-1) : -1));
	{
		while (1) {
			if (!!(((*data0)->data[h0].key == NIM_NIL))) goto LA2;
			h0 = nexttry_272155_2984716966(h0, ((*data0) ? ((*data0)->Sup.len-1) : -1));
		} LA2: ;
	}
	asgnRef((void**) (&(*data0)->data[h0].key), key0);
	asgnRefNoCycle((void**) (&(*data0)->data[h0].val), val0);
}

N_NIMCALL(void, idnodetableput_272133_2984716966)(Tidnodetable265850* t0, Tidobj195006* key0, Tnode265794* val0) {
	NI index0;
	index0 = idnodetablerawget_277464_2984716966((*t0), key0);
	{
		if (!(((NI) 0) <= index0)) goto LA3;
		asgnRefNoCycle((void**) (&(*t0).data->data[index0].val), val0);
	}
	goto LA1;
	LA3: ;
	{
		{
			NIM_BOOL LOC8;
			Tidnodepairseq265848* n0;
			Tidnodepairseq265848* LOC18;
			LOC8 = (NIM_BOOL)0;
			LOC8 = mustrehash_272151_2984716966(((*t0).data ? (*t0).data->Sup.len : 0), (*t0).counter);
			if (!LOC8) goto LA9;
			n0 = (Tidnodepairseq265848*)0;
			n0 = (Tidnodepairseq265848*) newSeq((&NTI265848), ((NI) ((NI)(((*t0).data ? (*t0).data->Sup.len : 0) * ((NI) 2)))));
			{
				NI i_278039_2984716966;
				NI HEX3Atmp_278075_2984716966;
				NI res_278078_2984716966;
				i_278039_2984716966 = (NI)0;
				HEX3Atmp_278075_2984716966 = (NI)0;
				HEX3Atmp_278075_2984716966 = ((*t0).data ? ((*t0).data->Sup.len-1) : -1);
				res_278078_2984716966 = ((NI) 0);
				{
					while (1) {
						if (!(res_278078_2984716966 <= HEX3Atmp_278075_2984716966)) goto LA13;
						i_278039_2984716966 = res_278078_2984716966;
						{
							if (!!(((*t0).data->data[i_278039_2984716966].key == NIM_NIL))) goto LA16;
							idnodetablerawinsert_277504_2984716966((&n0), (*t0).data->data[i_278039_2984716966].key, (*t0).data->data[i_278039_2984716966].val);
						}
						LA16: ;
						res_278078_2984716966 += ((NI) 1);
					} LA13: ;
				}
			}
			LOC18 = (Tidnodepairseq265848*)0;
			LOC18 = (*t0).data;
			unsureAsgnRef((void**) (&(*t0).data), n0);
			n0 = LOC18;
		}
		LA9: ;
		idnodetablerawinsert_277504_2984716966((&(*t0).data), key0, val0);
		(*t0).counter += ((NI) 1);
	}
	LA1: ;
}

N_NIMCALL(Tnode265794*, skipconvandclosure_272187_2984716966)(Tnode265794* n0) {
	Tnode265794* result0;
	result0 = (Tnode265794*)0;
	result0 = n0;
	{
		while (1) {
			switch ((*result0).kind) {
			case ((Tnodekind265020) 67):
			case ((Tnodekind265020) 66):
			case ((Tnodekind265020) 70):
			case ((Tnodekind265020) 68):
			case ((Tnodekind265020) 69):
			case ((Tnodekind265020) 155):
			{
				result0 = (*result0).kindU.S6.sons->data[((NI) 0)];
			}
			break;
			case ((Tnodekind265020) 58):
			case ((Tnodekind265020) 59):
			case ((Tnodekind265020) 60):
			{
				result0 = (*result0).kindU.S6.sons->data[((NI) 1)];
			}
			break;
			default:
			{
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	return result0;
}

N_NIMCALL(void, symtabreplaceraw_275414_2984716966)(Tsymseq265796** data0, Tsym265826* prevsym0, Tsym265826* newsym0) {
	NI h0;
{	h0 = (NI)((*(*prevsym0).name).h & ((*data0) ? ((*data0)->Sup.len-1) : -1));
	{
		while (1) {
			if (!!(((*data0)->data[h0] == NIM_NIL))) goto LA2;
			{
				if (!((*data0)->data[h0] == prevsym0)) goto LA5;
				asgnRefNoCycle((void**) (&(*data0)->data[h0]), newsym0);
				goto BeforeRet;
			}
			LA5: ;
			h0 = nexttry_272155_2984716966(h0, ((*data0) ? ((*data0)->Sup.len-1) : -1));
		} LA2: ;
	}
	}BeforeRet: ;
}

N_NIMCALL(void, symtabreplace_275803_2984716966)(Tstrtable265798* t0, Tsym265826* prevsym0, Tsym265826* newsym0) {
	symtabreplaceraw_275414_2984716966((&(*t0).data), prevsym0, newsym0);
}

N_NIMCALL(NIM_BOOL, idtablehasobjectaskey_272125_2984716966)(Tidtable265844 t0, Tidobj195006* key0) {
	NIM_BOOL result0;
	NI index0;
	result0 = (NIM_BOOL)0;
	index0 = idtablerawget_276599_2984716966(t0, (*key0).id);
	{
		if (!(((NI) 0) <= index0)) goto LA3;
		result0 = (t0.data->data[index0].key == key0);
	}
	goto LA1;
	LA3: ;
	{
		result0 = NIM_FALSE;
	}
	LA1: ;
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, compiler_astalgoInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, compiler_astalgoDatInit000)(void) {
static TNimNode* TMP998[2];
static TNimNode* TMP999[2];
static TNimNode TMP961[6];
NTI272167.size = sizeof(Tiitable272167);
NTI272167.kind = 18;
NTI272167.base = 0;
NTI272167.flags = 2;
TMP998[0] = &TMP961[1];
TMP961[1].kind = 1;
TMP961[1].offset = offsetof(Tiitable272167, counter);
TMP961[1].typ = (&NTI104);
TMP961[1].name = "counter";
TMP998[1] = &TMP961[2];
NTI272163.size = sizeof(Tiipair272163);
NTI272163.kind = 18;
NTI272163.base = 0;
NTI272163.flags = 3;
TMP999[0] = &TMP961[4];
TMP961[4].kind = 1;
TMP961[4].offset = offsetof(Tiipair272163, key);
TMP961[4].typ = (&NTI104);
TMP961[4].name = "key";
TMP999[1] = &TMP961[5];
TMP961[5].kind = 1;
TMP961[5].offset = offsetof(Tiipair272163, val);
TMP961[5].typ = (&NTI104);
TMP961[5].name = "val";
TMP961[3].len = 2; TMP961[3].kind = 2; TMP961[3].sons = &TMP999[0];
NTI272163.node = &TMP961[3];
NTI272165.size = sizeof(Tiipairseq272165*);
NTI272165.kind = 24;
NTI272165.base = (&NTI272163);
NTI272165.flags = 2;
NTI272165.marker = TMP1000;
TMP961[2].kind = 1;
TMP961[2].offset = offsetof(Tiitable272167, data);
TMP961[2].typ = (&NTI272165);
TMP961[2].name = "data";
TMP961[0].len = 2; TMP961[0].kind = 2; TMP961[0].sons = &TMP998[0];
NTI272167.node = &TMP961[0];
}

