/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/ubuntu/nim-ci/Nim/lib -o /home/ubuntu/nim-ci/Nim/compiler/rnimcache/compiler_semfold.o /home/ubuntu/nim-ci/Nim/compiler/rnimcache/compiler_semfold.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
typedef struct Tnode293798 Tnode293798;
typedef struct Ttype293836 Ttype293836;
typedef struct Tlineinfo192336 Tlineinfo192336;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Tsym293830 Tsym293830;
typedef struct Tident200012 Tident200012;
typedef struct Tnodeseq293792 Tnodeseq293792;
typedef struct Tidobj200006 Tidobj200006;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Ttypeseq293832 Ttypeseq293832;
typedef struct TY293925 TY293925;
typedef struct Tstrtable293802 Tstrtable293802;
typedef struct Tsymseq293800 Tsymseq293800;
typedef struct Tloc293812 Tloc293812;
typedef struct Ropeobj179006 Ropeobj179006;
typedef struct Tlib293816 Tlib293816;
typedef struct Cell47305 Cell47305;
typedef struct Cellseq47321 Cellseq47321;
typedef struct Gcheap49818 Gcheap49818;
typedef struct Gcstack49816 Gcstack49816;
typedef struct Memregion29480 Memregion29480;
typedef struct Smallchunk29437 Smallchunk29437;
typedef struct Llchunk29474 Llchunk29474;
typedef struct Bigchunk29439 Bigchunk29439;
typedef struct Intset29414 Intset29414;
typedef struct Trunk29410 Trunk29410;
typedef struct Avlnode29478 Avlnode29478;
typedef struct Gcstat49814 Gcstat49814;
typedef struct Cellset47317 Cellset47317;
typedef struct Pagedesc47313 Pagedesc47313;
typedef struct TY293956 TY293956;
typedef struct Tinfocpu177463 Tinfocpu177463;
typedef struct Tinfoos177037 Tinfoos177037;
typedef struct Exception Exception;
typedef struct TSafePoint TSafePoint;
typedef struct TY204019 TY204019;
typedef struct Tinstantiation293820 Tinstantiation293820;
typedef struct Tlistentry147010 Tlistentry147010;
typedef struct Basechunk29435 Basechunk29435;
typedef struct Freecell29427 Freecell29427;
typedef struct TY293957 TY293957;
struct  Tlineinfo192336  {
NI16 line;
NI16 col;
NI32 fileindex;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Tnode293798  {
Ttype293836* typ;
Tlineinfo192336 info;
NU16 flags;
NU8 kind;
union{
struct {NI64 intval;
} S1;
struct {NF floatval;
} S2;
struct {NimStringDesc* strval;
} S3;
struct {Tsym293830* sym;
} S4;
struct {Tident200012* ident;
} S5;
struct {Tnodeseq293792* sons;
} S6;
} kindU;
NimStringDesc* comment;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Tidobj200006  {
  TNimObject Sup;
NI id;
};
struct  Tstrtable293802  {
NI counter;
Tsymseq293800* data;
};
struct  Tloc293812  {
NU8 k;
NU8 s;
NU16 flags;
Ttype293836* t;
Ropeobj179006* r;
};
struct  Tsym293830  {
  Tidobj200006 Sup;
NU8 kind;
union{
struct {Ttypeseq293832* typeinstcache;
} S1;
struct {TY293925* procinstcache;
Tsym293830* gcunsafetyreason;
} S2;
struct {TY293925* usedgenerics;
Tstrtable293802 tab;
} S3;
struct {Tsym293830* guard;
NI bitsize;
} S4;
} kindU;
NU16 magic;
Ttype293836* typ;
Tident200012* name;
Tlineinfo192336 info;
Tsym293830* owner;
NU32 flags;
Tnode293798* ast;
NU32 options;
NI position;
NI offset;
Tloc293812 loc;
Tlib293816* annex;
Tnode293798* constraint;
};
struct  Cell47305  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47321  {
NI len;
NI cap;
Cell47305** d;
};
typedef Smallchunk29437* TY29495[512];
typedef Trunk29410* Trunkbuckets29412[256];
struct  Intset29414  {
Trunkbuckets29412 data;
};
struct  Memregion29480  {
NI minlargeobj;
NI maxlargeobj;
TY29495 freesmallchunks;
Llchunk29474* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29439* freechunkslist;
Intset29414 chunkstarts;
Avlnode29478* root;
Avlnode29478* deleted;
Avlnode29478* last;
Avlnode29478* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat49814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47317  {
NI counter;
NI max;
Pagedesc47313* head;
Pagedesc47313** data;
};
struct  Gcheap49818  {
Gcstack49816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47321 zct;
Cellseq47321 decstack;
Cellseq47321 tempstack;
NI recgclock;
Memregion29480 region;
Gcstat49814 stat;
Cellset47317 marked;
Cellseq47321 additionalroots;
};
struct  Ttype293836  {
  Tidobj200006 Sup;
NU8 kind;
NU8 callconv;
NU32 flags;
Ttypeseq293832* sons;
Tnode293798* n;
Tsym293830* owner;
Tsym293830* sym;
Tsym293830* destructor;
Tsym293830* deepcopy;
Tsym293830* assignment;
TY293956* methods;
NI64 size;
NI16 align;
NI16 locklevel;
Tloc293812 loc;
};
struct Tinfocpu177463 {
NimStringDesc* Field0;
NI Field1;
NU8 Field2;
NI Field3;
NI Field4;
};
typedef Tinfocpu177463 TY177491[19];
struct Tinfoos177037 {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
NimStringDesc* Field3;
NimStringDesc* Field4;
NimStringDesc* Field5;
NimStringDesc* Field6;
NimStringDesc* Field7;
NimStringDesc* Field8;
NimStringDesc* Field9;
NimStringDesc* Field10;
NimStringDesc* Field11;
NU8 Field12;
};
typedef Tinfoos177037 TY177069[24];
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY17211;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY17211 raiseAction;
};
struct  Tident200012  {
  Tidobj200006 Sup;
NimStringDesc* s;
Tident200012* next;
NI h;
};
struct TY204019 {
NimStringDesc* Field0;
NI Field1;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NimStringDesc* TY194153[2];
struct  Ropeobj179006  {
  TNimObject Sup;
Ropeobj179006* left;
Ropeobj179006* right;
NI length;
NimStringDesc* data;
};
struct  Tlistentry147010  {
  TNimObject Sup;
Tlistentry147010* prev;
Tlistentry147010* next;
};
struct  Tlib293816  {
  Tlistentry147010 Sup;
NU8 kind;
NIM_BOOL generated;
NIM_BOOL isoverriden;
Ropeobj179006* name;
Tnode293798* path;
};
struct  Gcstack49816  {
Gcstack49816* prev;
Gcstack49816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29435  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29437  {
  Basechunk29435 Sup;
Smallchunk29437* next;
Smallchunk29437* prev;
Freecell29427* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29474  {
NI size;
NI acc;
Llchunk29474* next;
};
struct  Bigchunk29439  {
  Basechunk29435 Sup;
Bigchunk29439* next;
Bigchunk29439* prev;
NI align;
NF data;
};
typedef NI TY29419[8];
struct  Trunk29410  {
Trunk29410* next;
NI key;
TY29419 bits;
};
typedef Avlnode29478* TY29485[2];
struct  Avlnode29478  {
TY29485 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47313  {
Pagedesc47313* next;
NI key;
TY29419 bits;
};
struct TY293957 {
NI Field0;
Tsym293830* Field1;
};
struct  Tinstantiation293820  {
Tsym293830* sym;
Ttypeseq293832* concretetypes;
NI compilesid;
};
struct  Freecell29427  {
Freecell29427* next;
NI zerofield;
};
struct Tnodeseq293792 {
  TGenericSeq Sup;
  Tnode293798* data[SEQ_DECL_SIZE];
};
struct Ttypeseq293832 {
  TGenericSeq Sup;
  Ttype293836* data[SEQ_DECL_SIZE];
};
struct TY293925 {
  TGenericSeq Sup;
  Tinstantiation293820* data[SEQ_DECL_SIZE];
};
struct Tsymseq293800 {
  TGenericSeq Sup;
  Tsym293830* data[SEQ_DECL_SIZE];
};
struct TY293956 {
  TGenericSeq Sup;
  TY293957 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NF, round_111661)(NF x, NI places);
N_NIMCALL(void, internalerror_197100)(Tlineinfo192336 info, NimStringDesc* errmsg);
N_NIMCALL(Tnode293798*, newsymnode_295190)(Tsym293830* sym, Tlineinfo192336 info);
N_NIMCALL(Ttype293836*, newtype_296107)(NU8 kind, Tsym293830* owner);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell47305*, usrtocell_51440)(void* usr);
static N_INLINE(void, rtladdzct_52601)(Cell47305* c);
N_NOINLINE(void, addzct_51417)(Cellseq47321* s, Cell47305* c);
N_NIMCALL(void, addsonskipintlit_338680)(Ttype293836* father, Ttype293836* son);
N_NIMCALL(Ttype293836*, skiptypes_297099)(Ttype293836* t, NU64 kinds);
N_NIMCALL(Tnode293798*, newintnode_294659)(NU8 kind, NI64 intval);
N_NIMCALL(Ttype293836*, getintlittype_338627)(Tnode293798* literal);
N_NIMCALL(Tnode293798*, newstrnode_294677)(NU8 kind, NimStringDesc* strval);
N_NIMCALL(Tnode293798*, newintnodet_353016)(NI64 intval, Tnode293798* n);
N_NIMCALL(Tnode293798*, newstrnodet_353024)(NimStringDesc* strval, Tnode293798* n);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_NIMCALL(NimStringDesc*, nsuToLowerAsciiStr)(NimStringDesc* s);
N_NIMCALL(Tnode293798*, getapptype_354015)(Tnode293798* n);
N_NIMCALL(Tnode293798*, newfloatnodet_353020)(NF floatval, Tnode293798* n);
N_NIMCALL(Tnode293798*, newfloatnode_294671)(NU8 kind, NF floatval);
N_NIMCALL(Ttype293836*, getfloatlittype_338649)(Tnode293798* literal);
N_NIMCALL(NIM_BOOL, isdefined_201141)(Tident200012* symbol);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, lookupsymbol_201149)(Tident200012* symbol);
N_NIMCALL(Tnode293798*, copytree_297822)(Tnode293798* src);
N_NIMCALL(Tnode293798*, newsymnodetypedesc_354496)(Tsym293830* s, Tlineinfo192336 info);
N_NIMCALL(Tnode293798*, copynode_297528)(Tnode293798* src);
N_NIMCALL(Tnode293798*, getconstifexpr_353857)(Tsym293830* c, Tnode293798* n);
N_NIMCALL(NI, sonslen_296351)(Tnode293798* n);
static N_INLINE(NI, len_294062)(Tnode293798* n);
N_NIMCALL(Tnode293798*, getconstexpr_353001)(Tsym293830* m, Tnode293798* n);
N_NIMCALL(NI64, getordvalue_321118)(Tnode293798* n);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
N_NIMCALL(NI64, computesize_321121)(Ttype293836* typ);
N_NIMCALL(void, localerror_197080)(Tlineinfo192336 info, NU16 msg, NimStringDesc* arg);
N_NIMCALL(NI64, getsize_321124)(Ttype293836* typ);
N_NIMCALL(NI64, firstord_321001)(Ttype293836* t);
N_NIMCALL(NI64, lastord_321004)(Ttype293836* t);
static N_INLINE(Tnode293798*, HEX5BHEX5D_294238)(Tnode293798* n, NI i);
N_NIMCALL(Tnode293798*, getarrayconstr_354072)(Tsym293830* m, Tnode293798* n);
N_NIMCALL(Tnode293798*, magiccall_353962)(Tsym293830* m, Tnode293798* n);
N_NIMCALL(Tnode293798*, evalop_353005)(NU16 m, Tnode293798* n, Tnode293798* a, Tnode293798* b, Tnode293798* c);
N_NIMCALL(NI64, getint_298220)(Tnode293798* a);
N_NIMCALL(NF, getfloat_298225)(Tnode293798* a);
N_NIMCALL(NI64, cardset_340050)(Tnode293798* s);
N_NIMCALL(NI64, lengthord_321007)(Ttype293836* t);
N_NIMCALL(NI64, HEX7CHEX2DHEX7C_352012)(NI64 a, NI64 b);
N_NIMCALL(NI64, HEX7CHEX2BHEX7C_352007)(NI64 a, NI64 b);
N_NIMCALL(NI64, HEX7CHEX2AHEX7C_352031)(NI64 a, NI64 b);
N_NIMCALL(NI64, HEX7CdivHEX7C_352021)(NI64 a, NI64 b);
N_NIMCALL(NI64, HEX7CmodHEX7C_352026)(NI64 a, NI64 b);
N_NIMCALL(NimStringDesc*, getstr_298230)(Tnode293798* a);
static N_INLINE(NI, cmpStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalmem_7488)(void* a, void* b, NI size);
N_NIMCALL(NIM_BOOL, containssets_340042)(Tnode293798* a, Tnode293798* b);
N_NIMCALL(NIM_BOOL, equalsets_340046)(Tnode293798* a, Tnode293798* b);
N_NIMCALL(Tnode293798*, intersectsets_340034)(Tnode293798* a, Tnode293798* b);
N_NIMCALL(Tnode293798*, unionsets_340026)(Tnode293798* a, Tnode293798* b);
N_NIMCALL(Tnode293798*, diffsets_340030)(Tnode293798* a, Tnode293798* b);
N_NIMCALL(Tnode293798*, symdiffsets_340038)(Tnode293798* a, Tnode293798* b);
N_NIMCALL(NimStringDesc*, getstrorchar_298235)(Tnode293798* a);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copymem_7478)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NIM_BOOL, inset_340010)(Tnode293798* s, Tnode293798* elem);
N_NIMCALL(NimStringDesc*, nimInt64ToStr)(NI64 x);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_79210, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, ordinalvaltostring_353052)(Tnode293798* a);
N_NIMCALL(NimStringDesc*, nimCharToStr)(NIM_CHAR x);
N_NIMCALL(NIM_BOOL, testcompileoption_281708)(NimStringDesc* switch_281710, Tlineinfo192336 info);
N_NIMCALL(NIM_BOOL, testcompileoptionarg_281523)(NimStringDesc* switch_281525, NimStringDesc* arg, Tlineinfo192336 info);
N_NIMCALL(NIM_BOOL, exprstructuralequivalent_319311)(Tnode293798* a, Tnode293798* b, NIM_BOOL strictsymequality);
N_NIMCALL(NimStringDesc*, rendertree_312044)(Tnode293798* n, NU8 renderflags);
N_NIMCALL(Tnode293798*, foldconstrstr_354455)(Tsym293830* m, Tnode293798* n);
N_NIMCALL(Tnode293798*, newnodeit_295801)(NU8 kind, Tlineinfo192336 info, Ttype293836* typ);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(Tnode293798*, evalis_353470)(Tnode293798* n, Tnode293798* a);
N_NIMCALL(void, internalerror_197113)(NimStringDesc* errmsg);
N_NIMCALL(NimStringDesc*, HEX24_197185)(TY204019 x);
N_NIMCALL(NimStringDesc*, nsuNormalize)(NimStringDesc* s);
N_NIMCALL(NIM_BOOL, sametype_325432)(Ttype293836* a, Ttype293836* b, NU8 flags);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_53419)(Cell47305* c);
static N_INLINE(void, decref_53001)(Cell47305* c);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(void, addson_295807)(Tnode293798* father, Tnode293798* son);
N_NIMCALL(NIM_BOOL, levalueconv_353012)(Tnode293798* a, Tnode293798* b);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, msgkindtostring_193723)(NU16 kind);
N_NIMCALL(NimStringDesc*, typetostring_321017)(Ttype293836* typ, NU8 prefer);
N_NIMCALL(Tnode293798*, foldconv_354053)(Tnode293798* n, Tnode293798* a, NIM_BOOL check);
N_NIMCALL(void, rangecheck_354049)(Tnode293798* n, NI64 value);
N_NIMCALL(Tnode293798*, foldarrayaccess_354098)(Tsym293830* m, Tnode293798* n);
N_NIMCALL(Tnode293798*, foldfieldaccess_354167)(Tsym293830* m, Tnode293798* n);
static N_INLINE(NIM_BOOL, isintrange_353136)(Ttype293836* t);
N_NIMCALL(Ttype293836*, makerange_353203)(Ttype293836* typ, NI64 first, NI64 last);
N_NIMCALL(Tnode293798*, newnode_294401)(NU8 kind);
static N_INLINE(NIM_BOOL, isfloatrange_353112)(Ttype293836* t);
N_NIMCALL(Ttype293836*, makerangef_353242)(Ttype293836* typ, NF first, NF last);
N_NIMCALL(NI64, HEX7CabsHEX7C_352017)(NI64 a);
static N_INLINE(NIM_BOOL, isintlit_321222)(Ttype293836* t);
N_NIMCALL(NI64, pickminint_353169)(Tnode293798* n);
N_NIMCALL(NI64, pickmaxint_353186)(Tnode293798* n);
N_NIMCALL(NIM_BOOL, isintrangeorlit_353165)(Ttype293836* t);
N_NIMCALL(Ttype293836*, pickintrange_353160)(Ttype293836* a, Ttype293836* b);
STRING_LITERAL(TMP3029, "leValueConv", 11);
extern NIM_CONST TY177491 Cpu_177477;
extern NIM_CONST TY177069 Os_177055;
STRING_LITERAL(TMP3483, "lib", 3);
STRING_LITERAL(TMP3484, "staticlib", 9);
STRING_LITERAL(TMP3485, "gui", 3);
STRING_LITERAL(TMP3486, "console", 7);
STRING_LITERAL(TMP3487, "getConstIfExpr()", 16);
STRING_LITERAL(TMP3489, "sizeof", 6);
STRING_LITERAL(TMP3492, "constant folding for shl", 24);
STRING_LITERAL(TMP3493, "constant folding for shr", 24);
STRING_LITERAL(TMP3496, "false", 5);
STRING_LITERAL(TMP3497, "true", 4);
STRING_LITERAL(TMP3498, "", 0);
STRING_LITERAL(TMP3499, "ordinalValToString", 18);
STRING_LITERAL(TMP3500, "no symbol for ordinal value: ", 29);
STRING_LITERAL(TMP3502, "compiler/semfold.nim", 20);
NIM_CONST TY204019 TMP3501 = {((NimStringDesc*) &TMP3502),
((NI) 252)}
;
NIM_CONST TY204019 TMP3503 = {((NimStringDesc*) &TMP3502),
((NI) 253)}
;
STRING_LITERAL(TMP3504, "closure", 7);
STRING_LITERAL(TMP3505, "iterator", 8);
STRING_LITERAL(TMP3506, "cannot convert ", 15);
STRING_LITERAL(TMP3507, " to ", 4);
STRING_LITERAL(TMP3508, "pickMinInt", 10);
STRING_LITERAL(TMP3509, "pickMaxInt", 10);
extern Gcheap49818 gch_49855;
extern NU8 targetcpu_177608;
extern NU8 targetos_177610;
extern NU64 gglobaloptions_170127;
extern TSafePoint* exchandler_18837;
extern TNimType NTI3640; /* OverflowError */
extern Exception* currexception_18839;
extern TNimType NTI3638; /* DivByZeroError */

N_NIMCALL(NIM_BOOL, levalueconv_353012)(Tnode293798* a, Tnode293798* b) {
	NIM_BOOL result;
	result = 0;
	result = NIM_FALSE;
	switch ((*a).kind) {
	case ((NU8) 5) ... ((NU8) 15):
	{
		switch ((*b).kind) {
		case ((NU8) 5) ... ((NU8) 15):
		{
			result = ((*a).kindU.S1.intval <= (*b).kindU.S1.intval);
		}
		break;
		case ((NU8) 16) ... ((NU8) 19):
		{
			NF LOC4;
			LOC4 = 0;
			LOC4 = round_111661((*b).kindU.S2.floatval, ((NI) 0));
			result = ((*a).kindU.S1.intval <= ((NI64) (((NI) (LOC4)))));
		}
		break;
		default:
		{
			internalerror_197100((*a).info, ((NimStringDesc*) &TMP3029));
		}
		break;
		}
	}
	break;
	case ((NU8) 16) ... ((NU8) 19):
	{
		switch ((*b).kind) {
		case ((NU8) 16) ... ((NU8) 19):
		{
			result = ((*a).kindU.S2.floatval <= (*b).kindU.S2.floatval);
		}
		break;
		case ((NU8) 5) ... ((NU8) 15):
		{
			result = ((*a).kindU.S2.floatval <= ((double) (((NI) ((*b).kindU.S1.intval)))));
		}
		break;
		default:
		{
			internalerror_197100((*a).info, ((NimStringDesc*) &TMP3029));
		}
		break;
		}
	}
	break;
	default:
	{
		internalerror_197100((*a).info, ((NimStringDesc*) &TMP3029));
	}
	break;
	}
	return result;
}

static N_INLINE(Cell47305*, usrtocell_51440)(void* usr) {
	Cell47305* result;
	result = 0;
	result = ((Cell47305*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47305))))));
	return result;
}

static N_INLINE(void, rtladdzct_52601)(Cell47305* c) {
	addzct_51417((&gch_49855.zct), c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		Cell47305* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_51440(src);
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	{
		Cell47305* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_51440((*dest));
		{
			(*c).refcount -= ((NI) 8);
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			rtladdzct_52601(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(Tnode293798*, newsymnodetypedesc_354496)(Tsym293830* s, Tlineinfo192336 info) {
	Tnode293798* result;
	result = 0;
	result = newsymnode_295190(s, info);
	asgnRefNoCycle((void**) (&(*result).typ), newtype_296107(((NU8) 8), (*s).owner));
	addsonskipintlit_338680((*result).typ, (*s).typ);
	return result;
}

N_NIMCALL(Tnode293798*, newintnodet_353016)(NI64 intval, Tnode293798* n) {
	Tnode293798* result;
	Ttype293836* LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = skiptypes_297099((*n).typ, IL64(211106242013440));
	switch ((*LOC1).kind) {
	case ((NU8) 31):
	{
		result = newintnode_294659(((NU8) 6), intval);
		asgnRefNoCycle((void**) (&(*result).typ), getintlittype_338627(result));
	}
	break;
	case ((NU8) 2):
	{
		result = newintnode_294659(((NU8) 5), intval);
		asgnRefNoCycle((void**) (&(*result).typ), (*n).typ);
	}
	break;
	default:
	{
		result = newintnode_294659(((NU8) 6), intval);
		asgnRefNoCycle((void**) (&(*result).typ), (*n).typ);
	}
	break;
	}
	(*result).info = (*n).info;
	return result;
}

N_NIMCALL(Tnode293798*, newstrnodet_353024)(NimStringDesc* strval, Tnode293798* n) {
	Tnode293798* result;
	result = 0;
	result = newstrnode_294677(((NU8) 20), strval);
	asgnRefNoCycle((void**) (&(*result).typ), (*n).typ);
	(*result).info = (*n).info;
	return result;
}

N_NIMCALL(Tnode293798*, getapptype_354015)(Tnode293798* n) {
	Tnode293798* result;
	result = 0;
	{
		if (!((gglobaloptions_170127 &((NU64)1<<((NU)(((NU8) 8))&63U)))!=0)) goto LA3;
		result = newstrnodet_353024(((NimStringDesc*) &TMP3483), n);
	}
	goto LA1;
	LA3: ;
	{
		if (!((gglobaloptions_170127 &((NU64)1<<((NU)(((NU8) 9))&63U)))!=0)) goto LA6;
		result = newstrnodet_353024(((NimStringDesc*) &TMP3484), n);
	}
	goto LA1;
	LA6: ;
	{
		if (!((gglobaloptions_170127 &((NU64)1<<((NU)(((NU8) 10))&63U)))!=0)) goto LA9;
		result = newstrnodet_353024(((NimStringDesc*) &TMP3485), n);
	}
	goto LA1;
	LA9: ;
	{
		result = newstrnodet_353024(((NimStringDesc*) &TMP3486), n);
	}
	LA1: ;
	return result;
}

N_NIMCALL(Tnode293798*, newfloatnodet_353020)(NF floatval, Tnode293798* n) {
	Tnode293798* result;
	result = 0;
	result = newfloatnode_294671(((NU8) 16), floatval);
	{
		Ttype293836* LOC3;
		LOC3 = 0;
		LOC3 = skiptypes_297099((*n).typ, IL64(211106242013440));
		if (!((*LOC3).kind == ((NU8) 36))) goto LA4;
		asgnRefNoCycle((void**) (&(*result).typ), getfloatlittype_338649(result));
	}
	goto LA1;
	LA4: ;
	{
		asgnRefNoCycle((void**) (&(*result).typ), (*n).typ);
	}
	LA1: ;
	(*result).info = (*n).info;
	return result;
}

static N_INLINE(NI, len_294062)(Tnode293798* n) {
	NI result;
	result = 0;
	{
		if (!(*n).kindU.S6.sons == 0) goto LA3;
		result = ((NI) 0);
	}
	goto LA1;
	LA3: ;
	{
		result = ((*n).kindU.S6.sons ? (*n).kindU.S6.sons->Sup.len : 0);
	}
	LA1: ;
	return result;
}

N_NIMCALL(Tnode293798*, getconstifexpr_353857)(Tsym293830* c, Tnode293798* n) {
	Tnode293798* result;
{	result = 0;
	result = NIM_NIL;
	{
		NI i_353873;
		NI HEX3Atmp_353931;
		NI LOC2;
		NI res_353934;
		i_353873 = 0;
		HEX3Atmp_353931 = 0;
		LOC2 = 0;
		LOC2 = sonslen_296351(n);
		HEX3Atmp_353931 = (NI)(LOC2 - ((NI) 1));
		res_353934 = ((NI) 0);
		{
			while (1) {
				Tnode293798* it;
				if (!(res_353934 <= HEX3Atmp_353931)) goto LA4;
				i_353873 = res_353934;
				it = (*n).kindU.S6.sons->data[i_353873];
				{
					NI LOC7;
					Tnode293798* e;
					LOC7 = 0;
					LOC7 = len_294062(it);
					if (!(LOC7 == ((NI) 2))) goto LA8;
					e = getconstexpr_353001(c, (*it).kindU.S6.sons->data[((NI) 0)]);
					{
						if (!(e == NIM_NIL)) goto LA12;
						result = NIM_NIL;
						goto BeforeRet;
					}
					LA12: ;
					{
						NI64 LOC16;
						LOC16 = 0;
						LOC16 = getordvalue_321118(e);
						if (!!((LOC16 == IL64(0)))) goto LA17;
						{
							if (!(result == NIM_NIL)) goto LA21;
							result = getconstexpr_353001(c, (*it).kindU.S6.sons->data[((NI) 1)]);
							{
								if (!(result == NIM_NIL)) goto LA25;
								goto BeforeRet;
							}
							LA25: ;
						}
						LA21: ;
					}
					LA17: ;
				}
				goto LA5;
				LA8: ;
				{
					NI LOC28;
					LOC28 = 0;
					LOC28 = len_294062(it);
					if (!(LOC28 == ((NI) 1))) goto LA29;
					{
						if (!(result == NIM_NIL)) goto LA33;
						result = getconstexpr_353001(c, (*it).kindU.S6.sons->data[((NI) 0)]);
					}
					LA33: ;
				}
				goto LA5;
				LA29: ;
				{
					internalerror_197100((*it).info, ((NimStringDesc*) &TMP3487));
				}
				LA5: ;
				res_353934 += ((NI) 1);
			} LA4: ;
		}
	}
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_18837;
	exchandler_18837 = s;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_18837 = (*exchandler_18837).prev;
}

static N_INLINE(Tnode293798*, HEX5BHEX5D_294238)(Tnode293798* n, NI i) {
	Tnode293798* result;
	result = 0;
	result = (*n).kindU.S6.sons->data[i];
	return result;
}

N_NIMCALL(Tnode293798*, getarrayconstr_354072)(Tsym293830* m, Tnode293798* n) {
	Tnode293798* result;
	result = 0;
	{
		if (!((*n).kind == ((NU8) 41))) goto LA3;
		result = n;
	}
	goto LA1;
	LA3: ;
	{
		result = getconstexpr_353001(m, n);
		{
			if (!(result == NIM_NIL)) goto LA8;
			result = n;
		}
		LA8: ;
	}
	LA1: ;
	return result;
}

static N_INLINE(NI, cmpStrings)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = ((NI) 0);
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!(a == NIM_NIL)) goto LA7;
		result = ((NI) -1);
		goto BeforeRet;
	}
	LA7: ;
	{
		if (!(b == NIM_NIL)) goto LA11;
		result = ((NI) 1);
		goto BeforeRet;
	}
	LA11: ;
	LOC13 = 0;
	LOC13 = strcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)));
	result = ((NI) (LOC13));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, equalmem_7488)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = memcmp(a, b, ((size_t) (size)));
	result = (LOC1 == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC11 = equalmem_7488(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, copymem_7478)(void* dest, void* source, NI size) {
	void* LOC1;
	LOC1 = 0;
	LOC1 = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copymem_7478(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, ordinalvaltostring_353052)(Tnode293798* a) {
	NimStringDesc* result;
	NI64 x;
	Ttype293836* t;
{	result = 0;
	x = getint_298220(a);
	t = skiptypes_297099((*a).typ, IL64(211106233624832));
	switch ((*t).kind) {
	case ((NU8) 2):
	{
		result = nimCharToStr(((NIM_CHAR) ((NI)(((NI) (x)) & ((NI) 255)))));
	}
	break;
	case ((NU8) 14):
	{
		Tnode293798* n;
		NimStringDesc* LOC20;
		NimStringDesc* LOC21;
		n = (*t).n;
		{
			NI i_353072;
			NI HEX3Atmp_353105;
			NI LOC4;
			NI res_353108;
			i_353072 = 0;
			HEX3Atmp_353105 = 0;
			LOC4 = 0;
			LOC4 = sonslen_296351(n);
			HEX3Atmp_353105 = (NI)(LOC4 - ((NI) 1));
			res_353108 = ((NI) 0);
			{
				while (1) {
					Tsym293830* field;
					if (!(res_353108 <= HEX3Atmp_353105)) goto LA6;
					i_353072 = res_353108;
					{
						if (!!(((*(*n).kindU.S6.sons->data[i_353072]).kind == ((NU8) 3)))) goto LA9;
						internalerror_197100((*a).info, ((NimStringDesc*) &TMP3499));
					}
					LA9: ;
					field = (*(*n).kindU.S6.sons->data[i_353072]).kindU.S4.sym;
					{
						if (!(((NI64) ((*field).position)) == x)) goto LA13;
						{
							if (!((*field).ast == NIM_NIL)) goto LA17;
							result = copyString((*(*field).name).s);
							goto BeforeRet;
						}
						goto LA15;
						LA17: ;
						{
							result = copyString((*(*field).ast).kindU.S3.strval);
							goto BeforeRet;
						}
						LA15: ;
					}
					LA13: ;
					res_353108 += ((NI) 1);
				} LA6: ;
			}
		}
		LOC20 = 0;
		LOC21 = 0;
		LOC21 = nimInt64ToStr(x);
		LOC20 = rawNewString(LOC21->Sup.len + 29);
appendString(LOC20, ((NimStringDesc*) &TMP3500));
appendString(LOC20, LOC21);
		internalerror_197100((*a).info, LOC20);
	}
	break;
	default:
	{
		result = nimInt64ToStr(x);
	}
	break;
	}
	}BeforeRet: ;
	return result;
}

N_NIMCALL(Tnode293798*, evalop_353005)(NU16 m, Tnode293798* n, Tnode293798* a, Tnode293798* b, Tnode293798* c) {
	Tnode293798* result;
	result = 0;
	result = NIM_NIL;
	switch (m) {
	case ((NU16) 28):
	{
		NI64 LOC2;
		LOC2 = 0;
		LOC2 = getordvalue_321118(a);
		result = newintnodet_353016(LOC2, n);
	}
	break;
	case ((NU16) 42):
	{
		NI64 LOC4;
		LOC4 = 0;
		LOC4 = getint_298220(a);
		result = newintnodet_353016(LOC4, n);
	}
	break;
	case ((NU16) 96):
	case ((NU16) 97):
	{
		NI64 LOC6;
		LOC6 = 0;
		LOC6 = getint_298220(a);
		result = newintnodet_353016(-(LOC6), n);
	}
	break;
	case ((NU16) 103):
	{
		NF LOC8;
		LOC8 = 0;
		LOC8 = getfloat_298225(a);
		result = newfloatnodet_353020(-(LOC8), n);
	}
	break;
	case ((NU16) 99):
	{
		NI64 LOC10;
		LOC10 = 0;
		LOC10 = getint_298220(a);
		result = newintnodet_353016((NI64)(IL64(1) - LOC10), n);
	}
	break;
	case ((NU16) 41):
	{
		NI64 LOC12;
		LOC12 = 0;
		LOC12 = cardset_340050(a);
		result = newintnodet_353016(LOC12, n);
	}
	break;
	case ((NU16) 101):
	{
		NI64 LOC14;
		LOC14 = 0;
		LOC14 = getint_298220(a);
		result = newintnodet_353016((NI64)((NU64) ~(LOC14)), n);
	}
	break;
	case ((NU16) 35):
	{
		NI64 LOC16;
		LOC16 = 0;
		LOC16 = lengthord_321007((*a).typ);
		result = newintnodet_353016(LOC16, n);
	}
	break;
	case ((NU16) 36):
	case ((NU16) 33):
	case ((NU16) 38):
	case ((NU16) 34):
	case ((NU16) 37):
	{
		{
			if (!((*a).kind == ((NU8) 23))) goto LA20;
			result = newintnodet_353016(IL64(0), n);
		}
		goto LA18;
		LA20: ;
		{
			if (!((*a).kind >= ((NU8) 20) && (*a).kind <= ((NU8) 22))) goto LA23;
			result = newintnodet_353016(((NI64) (((*a).kindU.S3.strval ? (*a).kindU.S3.strval->Sup.len : 0))), n);
		}
		goto LA18;
		LA23: ;
		{
			NI LOC26;
			LOC26 = 0;
			LOC26 = sonslen_296351(a);
			result = newintnodet_353016(((NI64) (LOC26)), n);
		}
		LA18: ;
	}
	break;
	case ((NU16) 100):
	case ((NU16) 102):
	{
		result = a;
	}
	break;
	case ((NU16) 114):
	case ((NU16) 115):
	{
		NI64 LOC29;
		LOC29 = 0;
		LOC29 = getint_298220(a);
		result = newfloatnodet_353020(((double) (((NI) (LOC29)))), n);
	}
	break;
	case ((NU16) 116):
	case ((NU16) 117):
	{
		NF LOC31;
		LOC31 = 0;
		LOC31 = getfloat_298225(a);
		result = newintnodet_353016(((NI64) (float64ToInt32(LOC31))), n);
	}
	break;
	case ((NU16) 104):
	{
		NF LOC33;
		LOC33 = 0;
		LOC33 = getfloat_298225(a);
		result = newfloatnodet_353020((LOC33 > 0? (LOC33) : -(LOC33)), n);
	}
	break;
	case ((NU16) 98):
	{
		{
			NI64 LOC37;
			LOC37 = 0;
			LOC37 = getint_298220(a);
			if (!(IL64(0) <= LOC37)) goto LA38;
			result = a;
		}
		goto LA35;
		LA38: ;
		{
			NI64 LOC41;
			LOC41 = 0;
			LOC41 = getint_298220(a);
			result = newintnodet_353016(-(LOC41), n);
		}
		LA35: ;
	}
	break;
	case ((NU16) 105):
	case ((NU16) 106):
	case ((NU16) 107):
	case ((NU16) 108):
	case ((NU16) 109):
	case ((NU16) 110):
	{
		NI64 LOC43;
		NI64 LOC44;
		LOC43 = 0;
		LOC43 = getint_298220(a);
		LOC44 = 0;
		LOC44 = getsize_321124((*a).typ);
		result = newintnodet_353016((NI64)(LOC43 & (NI64)((NI64)((NU64)(IL64(1)) << (NU64)((NI64)(LOC44 * IL64(8)))) - IL64(1))), n);
	}
	break;
	case ((NU16) 111):
	{
		NI64 LOC46;
		LOC46 = 0;
		LOC46 = getint_298220(a);
		result = newintnodet_353016(((NI64) ((NI64)(LOC46 & IL64(255)))), n);
	}
	break;
	case ((NU16) 112):
	{
		NI64 LOC48;
		LOC48 = 0;
		LOC48 = getint_298220(a);
		result = newintnodet_353016(((NI64) ((NI64)(LOC48 & IL64(65535)))), n);
	}
	break;
	case ((NU16) 113):
	{
		NI64 LOC50;
		LOC50 = 0;
		LOC50 = getint_298220(a);
		result = newintnodet_353016(((NI64) ((NI64)(LOC50 & IL64(4294967295)))), n);
	}
	break;
	case ((NU16) 25):
	{
		NI64 LOC52;
		NI64 LOC53;
		LOC52 = 0;
		LOC52 = getordvalue_321118(a);
		LOC53 = 0;
		LOC53 = HEX7CHEX2DHEX7C_352012(LOC52, IL64(1));
		result = newintnodet_353016(LOC53, n);
	}
	break;
	case ((NU16) 50):
	{
		NI64 LOC55;
		NI64 LOC56;
		NI64 LOC57;
		LOC55 = 0;
		LOC55 = getordvalue_321118(a);
		LOC56 = 0;
		LOC56 = getint_298220(b);
		LOC57 = 0;
		LOC57 = HEX7CHEX2BHEX7C_352007(LOC55, LOC56);
		result = newintnodet_353016(LOC57, n);
	}
	break;
	case ((NU16) 51):
	{
		NI64 LOC59;
		NI64 LOC60;
		NI64 LOC61;
		LOC59 = 0;
		LOC59 = getordvalue_321118(a);
		LOC60 = 0;
		LOC60 = getint_298220(b);
		LOC61 = 0;
		LOC61 = HEX7CHEX2DHEX7C_352012(LOC59, LOC60);
		result = newintnodet_353016(LOC61, n);
	}
	break;
	case ((NU16) 45):
	{
		NI64 LOC63;
		NI64 LOC64;
		NI64 LOC65;
		LOC63 = 0;
		LOC63 = getint_298220(a);
		LOC64 = 0;
		LOC64 = getint_298220(b);
		LOC65 = 0;
		LOC65 = HEX7CHEX2BHEX7C_352007(LOC63, LOC64);
		result = newintnodet_353016(LOC65, n);
	}
	break;
	case ((NU16) 46):
	{
		NI64 LOC67;
		NI64 LOC68;
		NI64 LOC69;
		LOC67 = 0;
		LOC67 = getint_298220(a);
		LOC68 = 0;
		LOC68 = getint_298220(b);
		LOC69 = 0;
		LOC69 = HEX7CHEX2DHEX7C_352012(LOC67, LOC68);
		result = newintnodet_353016(LOC69, n);
	}
	break;
	case ((NU16) 47):
	{
		NI64 LOC71;
		NI64 LOC72;
		NI64 LOC73;
		LOC71 = 0;
		LOC71 = getint_298220(a);
		LOC72 = 0;
		LOC72 = getint_298220(b);
		LOC73 = 0;
		LOC73 = HEX7CHEX2AHEX7C_352031(LOC71, LOC72);
		result = newintnodet_353016(LOC73, n);
	}
	break;
	case ((NU16) 61):
	{
		{
			NI64 LOC77;
			NI64 LOC78;
			NI64 LOC81;
			LOC77 = 0;
			LOC77 = getint_298220(b);
			LOC78 = 0;
			LOC78 = getint_298220(a);
			if (!(LOC77 < LOC78)) goto LA79;
			LOC81 = 0;
			LOC81 = getint_298220(b);
			result = newintnodet_353016(LOC81, n);
		}
		goto LA75;
		LA79: ;
		{
			NI64 LOC83;
			LOC83 = 0;
			LOC83 = getint_298220(a);
			result = newintnodet_353016(LOC83, n);
		}
		LA75: ;
	}
	break;
	case ((NU16) 62):
	{
		{
			NI64 LOC87;
			NI64 LOC88;
			NI64 LOC91;
			LOC87 = 0;
			LOC87 = getint_298220(b);
			LOC88 = 0;
			LOC88 = getint_298220(a);
			if (!(LOC87 < LOC88)) goto LA89;
			LOC91 = 0;
			LOC91 = getint_298220(a);
			result = newintnodet_353016(LOC91, n);
		}
		goto LA85;
		LA89: ;
		{
			NI64 LOC93;
			LOC93 = 0;
			LOC93 = getint_298220(b);
			result = newintnodet_353016(LOC93, n);
		}
		LA85: ;
	}
	break;
	case ((NU16) 57):
	{
		Ttype293836* LOC95;
		LOC95 = 0;
		LOC95 = skiptypes_297099((*n).typ, IL64(211106233624832));
		switch ((*LOC95).kind) {
		case ((NU8) 32):
		{
			NI64 LOC97;
			NI64 LOC98;
			LOC97 = 0;
			LOC97 = getint_298220(a);
			LOC98 = 0;
			LOC98 = getint_298220(b);
			result = newintnodet_353016(((NI64) ((NI8)((NU8)(((NI8) (LOC97))) << (NU8)(((NI8) (LOC98)))))), n);
		}
		break;
		case ((NU8) 33):
		{
			NI64 LOC100;
			NI64 LOC101;
			LOC100 = 0;
			LOC100 = getint_298220(a);
			LOC101 = 0;
			LOC101 = getint_298220(b);
			result = newintnodet_353016(((NI64) ((NI16)((NU16)(((NI16) (LOC100))) << (NU16)(((NI16) (LOC101)))))), n);
		}
		break;
		case ((NU8) 34):
		{
			NI64 LOC103;
			NI64 LOC104;
			LOC103 = 0;
			LOC103 = getint_298220(a);
			LOC104 = 0;
			LOC104 = getint_298220(b);
			result = newintnodet_353016(((NI64) ((NI32)((NU32)(((NI32) (LOC103))) << (NU32)(((NI32) (LOC104)))))), n);
		}
		break;
		case ((NU8) 35):
		case ((NU8) 31):
		case ((NU8) 40) ... ((NU8) 44):
		{
			NI64 LOC106;
			NI64 LOC107;
			LOC106 = 0;
			LOC106 = getint_298220(a);
			LOC107 = 0;
			LOC107 = getint_298220(b);
			result = newintnodet_353016((NI64)((NU64)(LOC106) << (NU64)(LOC107)), n);
		}
		break;
		default:
		{
			internalerror_197100((*n).info, ((NimStringDesc*) &TMP3492));
		}
		break;
		}
	}
	break;
	case ((NU16) 56):
	{
		Ttype293836* LOC110;
		LOC110 = 0;
		LOC110 = skiptypes_297099((*n).typ, IL64(211106233624832));
		switch ((*LOC110).kind) {
		case ((NU8) 32):
		{
			NI64 LOC112;
			NI64 LOC113;
			LOC112 = 0;
			LOC112 = getint_298220(a);
			LOC113 = 0;
			LOC113 = getint_298220(b);
			result = newintnodet_353016(((NI64) ((NI8)((NU8)(((NI8) (LOC112))) >> (NU8)(((NI8) (LOC113)))))), n);
		}
		break;
		case ((NU8) 33):
		{
			NI64 LOC115;
			NI64 LOC116;
			LOC115 = 0;
			LOC115 = getint_298220(a);
			LOC116 = 0;
			LOC116 = getint_298220(b);
			result = newintnodet_353016(((NI64) ((NI16)((NU16)(((NI16) (LOC115))) >> (NU16)(((NI16) (LOC116)))))), n);
		}
		break;
		case ((NU8) 34):
		{
			NI64 LOC118;
			NI64 LOC119;
			LOC118 = 0;
			LOC118 = getint_298220(a);
			LOC119 = 0;
			LOC119 = getint_298220(b);
			result = newintnodet_353016(((NI64) ((NI32)((NU32)(((NI32) (LOC118))) >> (NU32)(((NI32) (LOC119)))))), n);
		}
		break;
		case ((NU8) 35):
		case ((NU8) 31):
		case ((NU8) 40) ... ((NU8) 44):
		{
			NI64 LOC121;
			NI64 LOC122;
			LOC121 = 0;
			LOC121 = getint_298220(a);
			LOC122 = 0;
			LOC122 = getint_298220(b);
			result = newintnodet_353016((NI64)((NU64)(LOC121) >> (NU64)(LOC122)), n);
		}
		break;
		default:
		{
			internalerror_197100((*n).info, ((NimStringDesc*) &TMP3493));
		}
		break;
		}
	}
	break;
	case ((NU16) 48):
	{
		NI64 y;
		y = getint_298220(b);
		{
			NI64 LOC129;
			NI64 LOC130;
			if (!!((y == IL64(0)))) goto LA127;
			LOC129 = 0;
			LOC129 = getint_298220(a);
			LOC130 = 0;
			LOC130 = HEX7CdivHEX7C_352021(LOC129, y);
			result = newintnodet_353016(LOC130, n);
		}
		LA127: ;
	}
	break;
	case ((NU16) 49):
	{
		NI64 y;
		y = getint_298220(b);
		{
			NI64 LOC136;
			NI64 LOC137;
			if (!!((y == IL64(0)))) goto LA134;
			LOC136 = 0;
			LOC136 = getint_298220(a);
			LOC137 = 0;
			LOC137 = HEX7CmodHEX7C_352026(LOC136, y);
			result = newintnodet_353016(LOC137, n);
		}
		LA134: ;
	}
	break;
	case ((NU16) 52):
	{
		NF LOC139;
		NF LOC140;
		LOC139 = 0;
		LOC139 = getfloat_298225(a);
		LOC140 = 0;
		LOC140 = getfloat_298225(b);
		result = newfloatnodet_353020(((NF)(LOC139) + (NF)(LOC140)), n);
	}
	break;
	case ((NU16) 53):
	{
		NF LOC142;
		NF LOC143;
		LOC142 = 0;
		LOC142 = getfloat_298225(a);
		LOC143 = 0;
		LOC143 = getfloat_298225(b);
		result = newfloatnodet_353020(((NF)(LOC142) - (NF)(LOC143)), n);
	}
	break;
	case ((NU16) 54):
	{
		NF LOC145;
		NF LOC146;
		LOC145 = 0;
		LOC145 = getfloat_298225(a);
		LOC146 = 0;
		LOC146 = getfloat_298225(b);
		result = newfloatnodet_353020(((NF)(LOC145) * (NF)(LOC146)), n);
	}
	break;
	case ((NU16) 55):
	{
		{
			NF LOC150;
			LOC150 = 0;
			LOC150 = getfloat_298225(b);
			if (!(LOC150 == 0.0)) goto LA151;
			{
				NF LOC155;
				LOC155 = 0;
				LOC155 = getfloat_298225(a);
				if (!(LOC155 == 0.0)) goto LA156;
				result = newfloatnodet_353020(NAN, n);
			}
			goto LA153;
			LA156: ;
			{
				result = newfloatnodet_353020(INF, n);
			}
			LA153: ;
		}
		goto LA148;
		LA151: ;
		{
			NF LOC160;
			NF LOC161;
			LOC160 = 0;
			LOC160 = getfloat_298225(a);
			LOC161 = 0;
			LOC161 = getfloat_298225(b);
			result = newfloatnodet_353020(((NF)(LOC160) / (NF)(LOC161)), n);
		}
		LA148: ;
	}
	break;
	case ((NU16) 64):
	{
		{
			NF LOC165;
			NF LOC166;
			NF LOC169;
			LOC165 = 0;
			LOC165 = getfloat_298225(b);
			LOC166 = 0;
			LOC166 = getfloat_298225(a);
			if (!(LOC165 < LOC166)) goto LA167;
			LOC169 = 0;
			LOC169 = getfloat_298225(a);
			result = newfloatnodet_353020(LOC169, n);
		}
		goto LA163;
		LA167: ;
		{
			NF LOC171;
			LOC171 = 0;
			LOC171 = getfloat_298225(b);
			result = newfloatnodet_353020(LOC171, n);
		}
		LA163: ;
	}
	break;
	case ((NU16) 63):
	{
		{
			NF LOC175;
			NF LOC176;
			NF LOC179;
			LOC175 = 0;
			LOC175 = getfloat_298225(b);
			LOC176 = 0;
			LOC176 = getfloat_298225(a);
			if (!(LOC175 < LOC176)) goto LA177;
			LOC179 = 0;
			LOC179 = getfloat_298225(b);
			result = newfloatnodet_353020(LOC179, n);
		}
		goto LA173;
		LA177: ;
		{
			NF LOC181;
			LOC181 = 0;
			LOC181 = getfloat_298225(a);
			result = newfloatnodet_353020(LOC181, n);
		}
		LA173: ;
	}
	break;
	case ((NU16) 157):
	{
		result = newintnodet_353016(((NI64) (((*a).kind == ((NU8) 23)))), n);
	}
	break;
	case ((NU16) 72):
	case ((NU16) 88):
	case ((NU16) 82):
	case ((NU16) 85):
	{
		NI64 LOC184;
		NI64 LOC185;
		LOC184 = 0;
		LOC184 = getordvalue_321118(a);
		LOC185 = 0;
		LOC185 = getordvalue_321118(b);
		result = newintnodet_353016(((NI64) ((LOC184 < LOC185))), n);
	}
	break;
	case ((NU16) 71):
	case ((NU16) 87):
	case ((NU16) 81):
	case ((NU16) 84):
	{
		NI64 LOC187;
		NI64 LOC188;
		LOC187 = 0;
		LOC187 = getordvalue_321118(a);
		LOC188 = 0;
		LOC188 = getordvalue_321118(b);
		result = newintnodet_353016(((NI64) ((LOC187 <= LOC188))), n);
	}
	break;
	case ((NU16) 70):
	case ((NU16) 86):
	case ((NU16) 80):
	case ((NU16) 83):
	{
		NI64 LOC190;
		NI64 LOC191;
		LOC190 = 0;
		LOC190 = getordvalue_321118(a);
		LOC191 = 0;
		LOC191 = getordvalue_321118(b);
		result = newintnodet_353016(((NI64) ((LOC190 == LOC191))), n);
	}
	break;
	case ((NU16) 75):
	{
		NF LOC193;
		NF LOC194;
		LOC193 = 0;
		LOC193 = getfloat_298225(a);
		LOC194 = 0;
		LOC194 = getfloat_298225(b);
		result = newintnodet_353016(((NI64) ((LOC193 < LOC194))), n);
	}
	break;
	case ((NU16) 74):
	{
		NF LOC196;
		NF LOC197;
		LOC196 = 0;
		LOC196 = getfloat_298225(a);
		LOC197 = 0;
		LOC197 = getfloat_298225(b);
		result = newintnodet_353016(((NI64) ((LOC196 <= LOC197))), n);
	}
	break;
	case ((NU16) 73):
	{
		NF LOC199;
		NF LOC200;
		LOC199 = 0;
		LOC199 = getfloat_298225(a);
		LOC200 = 0;
		LOC200 = getfloat_298225(b);
		result = newintnodet_353016(((NI64) ((LOC199 == LOC200))), n);
	}
	break;
	case ((NU16) 130):
	{
		NimStringDesc* LOC202;
		NimStringDesc* LOC203;
		LOC202 = 0;
		LOC202 = getstr_298230(a);
		LOC203 = 0;
		LOC203 = getstr_298230(b);
		result = newintnodet_353016(((NI64) ((cmpStrings(LOC202, LOC203) < 0))), n);
	}
	break;
	case ((NU16) 129):
	{
		NimStringDesc* LOC205;
		NimStringDesc* LOC206;
		LOC205 = 0;
		LOC205 = getstr_298230(a);
		LOC206 = 0;
		LOC206 = getstr_298230(b);
		result = newintnodet_353016(((NI64) ((cmpStrings(LOC205, LOC206) <= 0))), n);
	}
	break;
	case ((NU16) 128):
	{
		NimStringDesc* LOC208;
		NimStringDesc* LOC209;
		LOC208 = 0;
		LOC208 = getstr_298230(a);
		LOC209 = 0;
		LOC209 = getstr_298230(b);
		result = newintnodet_353016(((NI64) (eqStrings(LOC208, LOC209))), n);
	}
	break;
	case ((NU16) 77):
	case ((NU16) 79):
	{
		NI64 LOC211;
		NI64 LOC212;
		LOC211 = 0;
		LOC211 = getordvalue_321118(a);
		LOC212 = 0;
		LOC212 = getordvalue_321118(b);
		result = newintnodet_353016(((NI64) (((NU64)(LOC211) < (NU64)(LOC212)))), n);
	}
	break;
	case ((NU16) 76):
	case ((NU16) 78):
	{
		NI64 LOC214;
		NI64 LOC215;
		LOC214 = 0;
		LOC214 = getordvalue_321118(a);
		LOC215 = 0;
		LOC215 = getordvalue_321118(b);
		result = newintnodet_353016(((NI64) (((NU64)(LOC214) <= (NU64)(LOC215)))), n);
	}
	break;
	case ((NU16) 58):
	case ((NU16) 126):
	{
		NI64 LOC217;
		NI64 LOC218;
		LOC217 = 0;
		LOC217 = getint_298220(a);
		LOC218 = 0;
		LOC218 = getint_298220(b);
		result = newintnodet_353016((NI64)(LOC217 & LOC218), n);
	}
	break;
	case ((NU16) 59):
	case ((NU16) 127):
	{
		NI64 LOC220;
		NI64 LOC221;
		LOC220 = 0;
		LOC220 = getint_298220(a);
		LOC221 = 0;
		LOC221 = getint_298220(b);
		result = newintnodet_353016((NI64)(LOC220 | LOC221), n);
	}
	break;
	case ((NU16) 60):
	case ((NU16) 93):
	{
		NI64 LOC223;
		NI64 LOC224;
		LOC223 = 0;
		LOC223 = getint_298220(a);
		LOC224 = 0;
		LOC224 = getint_298220(b);
		result = newintnodet_353016((NI64)(LOC223 ^ LOC224), n);
	}
	break;
	case ((NU16) 65):
	{
		NI64 LOC226;
		NI64 LOC227;
		LOC226 = 0;
		LOC226 = getint_298220(a);
		LOC227 = 0;
		LOC227 = getint_298220(b);
		result = newintnodet_353016((NI64)((NU64)(LOC226) + (NU64)(LOC227)), n);
	}
	break;
	case ((NU16) 66):
	{
		NI64 LOC229;
		NI64 LOC230;
		LOC229 = 0;
		LOC229 = getint_298220(a);
		LOC230 = 0;
		LOC230 = getint_298220(b);
		result = newintnodet_353016((NI64)((NU64)(LOC229) - (NU64)(LOC230)), n);
	}
	break;
	case ((NU16) 67):
	{
		NI64 LOC232;
		NI64 LOC233;
		LOC232 = 0;
		LOC232 = getint_298220(a);
		LOC233 = 0;
		LOC233 = getint_298220(b);
		result = newintnodet_353016((NI64)((NU64)(LOC232) * (NU64)(LOC233)), n);
	}
	break;
	case ((NU16) 69):
	{
		NI64 y;
		y = getint_298220(b);
		{
			NI64 LOC239;
			if (!!((y == IL64(0)))) goto LA237;
			LOC239 = 0;
			LOC239 = getint_298220(a);
			result = newintnodet_353016((NI64)((NU64)(LOC239) % (NU64)(y)), n);
		}
		LA237: ;
	}
	break;
	case ((NU16) 68):
	{
		NI64 y;
		y = getint_298220(b);
		{
			NI64 LOC245;
			if (!!((y == IL64(0)))) goto LA243;
			LOC245 = 0;
			LOC245 = getint_298220(a);
			result = newintnodet_353016((NI64)((NU64)(LOC245) / (NU64)(y)), n);
		}
		LA243: ;
	}
	break;
	case ((NU16) 132):
	{
		NIM_BOOL LOC247;
		LOC247 = 0;
		LOC247 = containssets_340042(a, b);
		result = newintnodet_353016(((NI64) (LOC247)), n);
	}
	break;
	case ((NU16) 131):
	{
		NIM_BOOL LOC249;
		LOC249 = 0;
		LOC249 = equalsets_340046(a, b);
		result = newintnodet_353016(((NI64) (LOC249)), n);
	}
	break;
	case ((NU16) 133):
	{
		NIM_BOOL LOC251;
		NIM_BOOL LOC253;
		LOC251 = 0;
		LOC251 = containssets_340042(a, b);
		if (!(LOC251)) goto LA252;
		LOC253 = 0;
		LOC253 = equalsets_340046(a, b);
		LOC251 = !(LOC253);
		LA252: ;
		result = newintnodet_353016(((NI64) (LOC251)), n);
	}
	break;
	case ((NU16) 134):
	{
		result = intersectsets_340034(a, b);
		(*result).info = (*n).info;
	}
	break;
	case ((NU16) 135):
	{
		result = unionsets_340026(a, b);
		(*result).info = (*n).info;
	}
	break;
	case ((NU16) 136):
	{
		result = diffsets_340030(a, b);
		(*result).info = (*n).info;
	}
	break;
	case ((NU16) 137):
	{
		result = symdiffsets_340038(a, b);
		(*result).info = (*n).info;
	}
	break;
	case ((NU16) 138):
	{
		NimStringDesc* LOC259;
		NimStringDesc* LOC260;
		NimStringDesc* LOC261;
		LOC259 = 0;
		LOC260 = 0;
		LOC260 = getstrorchar_298235(a);
		LOC261 = 0;
		LOC261 = getstrorchar_298235(b);
		LOC259 = rawNewString(LOC260->Sup.len + LOC261->Sup.len + 0);
appendString(LOC259, LOC260);
appendString(LOC259, LOC261);
		result = newstrnodet_353024(LOC259, n);
	}
	break;
	case ((NU16) 148):
	{
		NIM_BOOL LOC263;
		LOC263 = 0;
		LOC263 = inset_340010(a, b);
		result = newintnodet_353016(((NI64) (LOC263)), n);
	}
	break;
	case ((NU16) 149):
	{
	}
	break;
	case ((NU16) 120):
	case ((NU16) 121):
	{
		NI64 LOC266;
		NimStringDesc* LOC267;
		LOC266 = 0;
		LOC266 = getordvalue_321118(a);
		LOC267 = 0;
		LOC267 = nimInt64ToStr(LOC266);
		result = newstrnodet_353024(LOC267, n);
	}
	break;
	case ((NU16) 119):
	{
		{
			NI64 LOC271;
			LOC271 = 0;
			LOC271 = getordvalue_321118(a);
			if (!(LOC271 == IL64(0))) goto LA272;
			result = newstrnodet_353024(((NimStringDesc*) &TMP3496), n);
		}
		goto LA269;
		LA272: ;
		{
			result = newstrnodet_353024(((NimStringDesc*) &TMP3497), n);
		}
		LA269: ;
	}
	break;
	case ((NU16) 159):
	{
		NimStringDesc* LOC276;
		NI64 LOC277;
		NimStringDesc* LOC278;
		LOC276 = 0;
		LOC276 = getstr_298230(a);
		LOC277 = 0;
		LOC277 = getordvalue_321118(b);
		LOC278 = 0;
		LOC278 = copyStr(LOC276, ((NI) (LOC277)));
		result = newstrnodet_353024(LOC278, n);
	}
	break;
	case ((NU16) 160):
	{
		NimStringDesc* LOC280;
		NI64 LOC281;
		NI64 LOC282;
		NimStringDesc* LOC283;
		LOC280 = 0;
		LOC280 = getstr_298230(a);
		LOC281 = 0;
		LOC281 = getordvalue_321118(b);
		LOC282 = 0;
		LOC282 = getordvalue_321118(c);
		LOC283 = 0;
		LOC283 = copyStrLast(LOC280, ((NI) (LOC281)), ((NI) (LOC282)));
		result = newstrnodet_353024(LOC283, n);
	}
	break;
	case ((NU16) 122):
	{
		NF LOC285;
		NimStringDesc* LOC286;
		LOC285 = 0;
		LOC285 = getfloat_298225(a);
		LOC286 = 0;
		LOC286 = nimFloatToStr(LOC285);
		result = newstrnodet_353024(LOC286, n);
	}
	break;
	case ((NU16) 123):
	case ((NU16) 118):
	{
		{
			NimStringDesc* s;
			if (!((*a).kind == ((NU8) 41))) goto LA290;
			s = copyString(((NimStringDesc*) &TMP3498));
			{
				Tnode293798* b_353817;
				Tnodeseq293792* HEX3Atmp_353851;
				NI i_353854;
				NI L_353856;
				b_353817 = 0;
				HEX3Atmp_353851 = 0;
				HEX3Atmp_353851 = (*a).kindU.S6.sons;
				i_353854 = ((NI) 0);
				L_353856 = (HEX3Atmp_353851 ? HEX3Atmp_353851->Sup.len : 0);
				{
					while (1) {
						NimStringDesc* LOC295;
						if (!(i_353854 < L_353856)) goto LA294;
						b_353817 = HEX3Atmp_353851->data[i_353854];
						LOC295 = 0;
						LOC295 = getstrorchar_298235(b_353817);
						s = resizeString(s, LOC295->Sup.len + 0);
appendString(s, LOC295);
						i_353854 += ((NI) 1);
					} LA294: ;
				}
			}
			result = newstrnodet_353024(s, n);
		}
		goto LA288;
		LA290: ;
		{
			NimStringDesc* LOC297;
			LOC297 = 0;
			LOC297 = getstrorchar_298235(a);
			result = newstrnodet_353024(LOC297, n);
		}
		LA288: ;
	}
	break;
	case ((NU16) 124):
	{
		result = a;
	}
	break;
	case ((NU16) 125):
	{
		NimStringDesc* LOC300;
		LOC300 = 0;
		LOC300 = ordinalvaltostring_353052(a);
		result = newstrnodet_353024(LOC300, n);
	}
	break;
	case ((NU16) 158):
	{
		result = copytree_297822(a);
		asgnRefNoCycle((void**) (&(*result).typ), (*n).typ);
	}
	break;
	case ((NU16) 221):
	{
		NimStringDesc* LOC303;
		NIM_BOOL LOC304;
		LOC303 = 0;
		LOC303 = getstr_298230(a);
		LOC304 = 0;
		LOC304 = testcompileoption_281708(LOC303, (*n).info);
		result = newintnodet_353016(((NI64) (LOC304)), n);
	}
	break;
	case ((NU16) 222):
	{
		NimStringDesc* LOC306;
		NimStringDesc* LOC307;
		NIM_BOOL LOC308;
		LOC306 = 0;
		LOC306 = getstr_298230(a);
		LOC307 = 0;
		LOC307 = getstr_298230(b);
		LOC308 = 0;
		LOC308 = testcompileoptionarg_281523(LOC306, LOC307, (*n).info);
		result = newintnodet_353016(((NI64) (LOC308)), n);
	}
	break;
	case ((NU16) 95):
	{
		NIM_BOOL LOC310;
		LOC310 = 0;
		LOC310 = exprstructuralequivalent_319311(a, b, NIM_TRUE);
		result = newintnodet_353016(((NI64) (LOC310)), n);
	}
	break;
	default:
	{
	}
	break;
	}
	return result;
}

N_NIMCALL(Tnode293798*, magiccall_353962)(Tsym293830* m, Tnode293798* n) {
	Tnode293798* result;
	Tsym293830* s;
	Tnode293798* a;
	Tnode293798* b;
	Tnode293798* c;
{	result = 0;
	{
		NI LOC3;
		LOC3 = 0;
		LOC3 = sonslen_296351(n);
		if (!(LOC3 <= ((NI) 1))) goto LA4;
		goto BeforeRet;
	}
	LA4: ;
	s = (*(*n).kindU.S6.sons->data[((NI) 0)]).kindU.S4.sym;
	a = getconstexpr_353001(m, (*n).kindU.S6.sons->data[((NI) 1)]);
	b = 0;
	c = 0;
	{
		if (!(a == NIM_NIL)) goto LA8;
		goto BeforeRet;
	}
	LA8: ;
	{
		NI LOC12;
		LOC12 = 0;
		LOC12 = sonslen_296351(n);
		if (!(((NI) 2) < LOC12)) goto LA13;
		b = getconstexpr_353001(m, (*n).kindU.S6.sons->data[((NI) 2)]);
		{
			if (!(b == NIM_NIL)) goto LA17;
			goto BeforeRet;
		}
		LA17: ;
		{
			NI LOC21;
			LOC21 = 0;
			LOC21 = sonslen_296351(n);
			if (!(((NI) 3) < LOC21)) goto LA22;
			c = getconstexpr_353001(m, (*n).kindU.S6.sons->data[((NI) 3)]);
			{
				if (!(c == NIM_NIL)) goto LA26;
				goto BeforeRet;
			}
			LA26: ;
		}
		LA22: ;
	}
	LA13: ;
	result = evalop_353005((*s).magic, n, a, b, c);
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell47305* c;
	c = usrtocell_51440(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_52601(c);
	}
	LA3: ;
}

N_NIMCALL(Tnode293798*, foldconstrstr_354455)(Tsym293830* m, Tnode293798* n) {
	Tnode293798* result;
	NimStringDesc* LOC1;
{	result = 0;
	result = newnodeit_295801(((NU8) 20), (*n).info, (*n).typ);
	LOC1 = 0;
	LOC1 = (*result).kindU.S3.strval; (*result).kindU.S3.strval = copyStringRC1(((NimStringDesc*) &TMP3498));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	{
		NI i_354472;
		NI HEX3Atmp_354489;
		NI LOC3;
		NI res_354492;
		i_354472 = 0;
		HEX3Atmp_354489 = 0;
		LOC3 = 0;
		LOC3 = sonslen_296351(n);
		HEX3Atmp_354489 = (NI)(LOC3 - ((NI) 1));
		res_354492 = ((NI) 1);
		{
			while (1) {
				Tnode293798* a;
				NimStringDesc* LOC10;
				if (!(res_354492 <= HEX3Atmp_354489)) goto LA5;
				i_354472 = res_354492;
				a = getconstexpr_353001(m, (*n).kindU.S6.sons->data[i_354472]);
				{
					if (!(a == NIM_NIL)) goto LA8;
					result = NIM_NIL;
					goto BeforeRet;
				}
				LA8: ;
				LOC10 = 0;
				LOC10 = getstrorchar_298235(a);
				(*result).kindU.S3.strval = resizeString((*result).kindU.S3.strval, LOC10->Sup.len + 0);
appendString((*result).kindU.S3.strval, LOC10);
				res_354492 += ((NI) 1);
			} LA5: ;
		}
	}
	}BeforeRet: ;
	return result;
}

N_NIMCALL(Tnode293798*, evalis_353470)(Tnode293798* n, Tnode293798* a) {
	Tnode293798* result;
	Ttype293836* t1;
	result = 0;
	{
		NIM_BOOL LOC3;
		NimStringDesc* LOC7;
		LOC3 = 0;
		LOC3 = ((*a).kind == ((NU8) 3));
		if (!(LOC3)) goto LA4;
		LOC3 = ((*(*a).kindU.S4.sym).kind == ((NU8) 7));
		LA4: ;
		if (!!(LOC3)) goto LA5;
		LOC7 = 0;
		LOC7 = HEX24_197185(TMP3501);
		internalerror_197113(LOC7);
	}
	LA5: ;
	{
		NIM_BOOL LOC10;
		NI LOC11;
		Tnode293798* LOC13;
		NimStringDesc* LOC16;
		LOC10 = 0;
		LOC11 = 0;
		LOC11 = sonslen_296351(n);
		LOC10 = (LOC11 == ((NI) 3));
		if (!(LOC10)) goto LA12;
		LOC13 = 0;
		LOC13 = HEX5BHEX5D_294238(n, ((NI) 2));
		LOC10 = ((*LOC13).kind >= ((NU8) 20) && (*LOC13).kind <= ((NU8) 22) || (*LOC13).kind == ((NU8) 4));
		LA12: ;
		if (!!(LOC10)) goto LA14;
		LOC16 = 0;
		LOC16 = HEX24_197185(TMP3503);
		internalerror_197113(LOC16);
	}
	LA14: ;
	t1 = (*(*a).kindU.S4.sym).typ;
	{
		Tnode293798* LOC19;
		Tnode293798* LOC22;
		NimStringDesc* LOC23;
		LOC19 = 0;
		LOC19 = HEX5BHEX5D_294238(n, ((NI) 2));
		if (!((*LOC19).kind >= ((NU8) 20) && (*LOC19).kind <= ((NU8) 22))) goto LA20;
		LOC22 = 0;
		LOC22 = HEX5BHEX5D_294238(n, ((NI) 2));
		LOC23 = 0;
		LOC23 = nsuNormalize((*LOC22).kindU.S3.strval);
		if (eqStrings(LOC23, ((NimStringDesc*) &TMP3504))) goto LA24;
		if (eqStrings(LOC23, ((NimStringDesc*) &TMP3505))) goto LA25;
		goto LA26;
		LA24: ;
		{
			Ttype293836* t;
			NIM_BOOL LOC29;
			NIM_BOOL LOC30;
			t = skiptypes_297099(t1, IL64(211106233624832));
			LOC29 = 0;
			LOC30 = 0;
			LOC30 = ((*t).kind == ((NU8) 25));
			if (!(LOC30)) goto LA31;
			LOC30 = ((*t).callconv == ((NU8) 8));
			LA31: ;
			LOC29 = LOC30;
			if (!(LOC29)) goto LA32;
			LOC29 = !((((*t).flags &(1U<<((NU)(((NU8) 14))&31U)))!=0));
			LA32: ;
			result = newintnode_294659(((NU8) 6), ((NI64) (LOC29)));
		}
		goto LA27;
		LA25: ;
		{
			Ttype293836* t;
			NIM_BOOL LOC34;
			NIM_BOOL LOC35;
			t = skiptypes_297099(t1, IL64(211106233624832));
			LOC34 = 0;
			LOC35 = 0;
			LOC35 = ((*t).kind == ((NU8) 25));
			if (!(LOC35)) goto LA36;
			LOC35 = ((*t).callconv == ((NU8) 8));
			LA36: ;
			LOC34 = LOC35;
			if (!(LOC34)) goto LA37;
			LOC34 = (((*t).flags &(1U<<((NU)(((NU8) 14))&31U)))!=0);
			LA37: ;
			result = newintnode_294659(((NU8) 6), ((NI64) (LOC34)));
		}
		goto LA27;
		LA26: ;
		{
		}
		LA27: ;
	}
	goto LA17;
	LA20: ;
	{
		Ttype293836* t2;
		Tnode293798* LOC40;
		NIM_BOOL match;
		LOC40 = 0;
		LOC40 = HEX5BHEX5D_294238(n, ((NI) 2));
		t2 = (*LOC40).typ;
		match = sametype_325432(t1, t2, 0);
		result = newintnode_294659(((NU8) 6), ((NI64) (match)));
	}
	LA17: ;
	asgnRefNoCycle((void**) (&(*result).typ), (*n).typ);
	return result;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	result = 0;
	result = currexception_18839;
	return result;
}

static N_INLINE(void, incref_53419)(Cell47305* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(void, decref_53001)(Cell47305* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_52601(c);
	}
	LA3: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		Cell47305* LOC5;
		if (!!((src == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = usrtocell_51440(src);
		incref_53419(LOC5);
	}
	LA3: ;
	{
		Cell47305* LOC10;
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		LOC10 = 0;
		LOC10 = usrtocell_51440((*dest));
		decref_53001(LOC10);
	}
	LA8: ;
	(*dest) = src;
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currexception_18839), NIM_NIL);
}

N_NIMCALL(void, rangecheck_354049)(Tnode293798* n, NI64 value) {
	{
		NIM_BOOL LOC3;
		NI64 LOC4;
		NI64 LOC6;
		NimStringDesc* LOC9;
		NimStringDesc* LOC10;
		NimStringDesc* LOC11;
		LOC3 = 0;
		LOC4 = 0;
		LOC4 = firstord_321001((*n).typ);
		LOC3 = (value < LOC4);
		if (LOC3) goto LA5;
		LOC6 = 0;
		LOC6 = lastord_321004((*n).typ);
		LOC3 = (LOC6 < value);
		LA5: ;
		if (!LOC3) goto LA7;
		LOC9 = 0;
		LOC10 = 0;
		LOC10 = nimInt64ToStr(value);
		LOC11 = 0;
		LOC11 = typetostring_321017((*n).typ, ((NU8) 0));
		LOC9 = rawNewString(LOC10->Sup.len + LOC11->Sup.len + 19);
appendString(LOC9, ((NimStringDesc*) &TMP3506));
appendString(LOC9, LOC10);
appendString(LOC9, ((NimStringDesc*) &TMP3507));
appendString(LOC9, LOC11);
		localerror_197080((*n).info, ((NU16) 4), LOC9);
	}
	LA7: ;
}

N_NIMCALL(Tnode293798*, foldconv_354053)(Tnode293798* n, Tnode293798* a, NIM_BOOL check) {
	Tnode293798* result;
	Ttype293836* LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = skiptypes_297099((*n).typ, IL64(211106233624832));
	switch ((*LOC1).kind) {
	case ((NU8) 31) ... ((NU8) 35):
	case ((NU8) 40) ... ((NU8) 44):
	{
		Ttype293836* LOC3;
		LOC3 = 0;
		LOC3 = skiptypes_297099((*a).typ, IL64(211106233624832));
		switch ((*LOC3).kind) {
		case ((NU8) 36) ... ((NU8) 38):
		{
			NF LOC5;
			LOC5 = 0;
			LOC5 = getfloat_298225(a);
			result = newintnodet_353016(((NI64) (((NI) (LOC5)))), n);
		}
		break;
		case ((NU8) 2):
		{
			NI64 LOC7;
			LOC7 = 0;
			LOC7 = getordvalue_321118(a);
			result = newintnodet_353016(LOC7, n);
		}
		break;
		default:
		{
			result = a;
			asgnRefNoCycle((void**) (&(*result).typ), (*n).typ);
		}
		break;
		}
		{
			NIM_BOOL LOC11;
			LOC11 = 0;
			LOC11 = check;
			if (!(LOC11)) goto LA12;
			LOC11 = ((*result).kind >= ((NU8) 5) && (*result).kind <= ((NU8) 15));
			LA12: ;
			if (!LOC11) goto LA13;
			rangecheck_354049(n, (*result).kindU.S1.intval);
		}
		LA13: ;
	}
	break;
	case ((NU8) 36) ... ((NU8) 38):
	{
		Ttype293836* LOC16;
		LOC16 = 0;
		LOC16 = skiptypes_297099((*a).typ, IL64(211106233624832));
		switch ((*LOC16).kind) {
		case ((NU8) 31) ... ((NU8) 35):
		case ((NU8) 14):
		case ((NU8) 1):
		case ((NU8) 2):
		{
			NI64 LOC18;
			LOC18 = 0;
			LOC18 = getordvalue_321118(a);
			result = newfloatnodet_353020(((double) (LOC18)), n);
		}
		break;
		default:
		{
			result = a;
			asgnRefNoCycle((void**) (&(*result).typ), (*n).typ);
		}
		break;
		}
	}
	break;
	case ((NU8) 27):
	case ((NU8) 48):
	case ((NU8) 25):
	{
	}
	break;
	default:
	{
		result = a;
		asgnRefNoCycle((void**) (&(*result).typ), (*n).typ);
	}
	break;
	}
	return result;
}

N_NIMCALL(Tnode293798*, foldarrayaccess_354098)(Tsym293830* m, Tnode293798* n) {
	Tnode293798* result;
	Tnode293798* x;
	Tnode293798* y;
	NI64 idx;
{	result = 0;
	x = getconstexpr_353001(m, (*n).kindU.S6.sons->data[((NI) 0)]);
	{
		NIM_BOOL LOC3;
		Ttype293836* LOC5;
		LOC3 = 0;
		LOC3 = (x == NIM_NIL);
		if (LOC3) goto LA4;
		LOC5 = 0;
		LOC5 = skiptypes_297099((*x).typ, 2048);
		LOC3 = ((*LOC5).kind == ((NU8) 8));
		LA4: ;
		if (!LOC3) goto LA6;
		goto BeforeRet;
	}
	LA6: ;
	y = getconstexpr_353001(m, (*n).kindU.S6.sons->data[((NI) 1)]);
	{
		if (!(y == NIM_NIL)) goto LA10;
		goto BeforeRet;
	}
	LA10: ;
	idx = getordvalue_321118(y);
	switch ((*x).kind) {
	case ((NU8) 37):
	{
		{
			NIM_BOOL LOC15;
			NI LOC17;
			LOC15 = 0;
			LOC15 = (IL64(0) <= idx);
			if (!(LOC15)) goto LA16;
			LOC17 = 0;
			LOC17 = sonslen_296351(x);
			LOC15 = (idx < ((NI64) (LOC17)));
			LA16: ;
			if (!LOC15) goto LA18;
			result = (*x).kindU.S6.sons->data[idx];
			{
				if (!((*result).kind == ((NU8) 34))) goto LA22;
				result = (*result).kindU.S6.sons->data[((NI) 1)];
			}
			LA22: ;
		}
		goto LA13;
		LA18: ;
		{
			localerror_197080((*n).info, ((NU16) 86), ((NimStringDesc*) &TMP3498));
		}
		LA13: ;
	}
	break;
	case ((NU8) 41):
	{
		NI64 LOC26;
		LOC26 = 0;
		LOC26 = firstord_321001((*x).typ);
		idx = (NI64)(idx - LOC26);
		{
			NIM_BOOL LOC29;
			NI LOC31;
			LOC29 = 0;
			LOC29 = (IL64(0) <= idx);
			if (!(LOC29)) goto LA30;
			LOC31 = 0;
			LOC31 = len_294062(x);
			LOC29 = (idx < ((NI64) (LOC31)));
			LA30: ;
			if (!LOC29) goto LA32;
			result = (*x).kindU.S6.sons->data[idx];
		}
		goto LA27;
		LA32: ;
		{
			localerror_197080((*n).info, ((NU16) 86), ((NimStringDesc*) &TMP3498));
		}
		LA27: ;
	}
	break;
	case ((NU8) 20) ... ((NU8) 22):
	{
		result = newnodeit_295801(((NU8) 5), (*x).info, (*n).typ);
		{
			NIM_BOOL LOC38;
			LOC38 = 0;
			LOC38 = (IL64(0) <= idx);
			if (!(LOC38)) goto LA39;
			LOC38 = (idx < ((NI64) (((*x).kindU.S3.strval ? (*x).kindU.S3.strval->Sup.len : 0))));
			LA39: ;
			if (!LOC38) goto LA40;
			(*result).kindU.S1.intval = ((NI64) (((NU8)((*x).kindU.S3.strval->data[idx]))));
		}
		goto LA36;
		LA40: ;
		{
			if (!(idx == ((NI64) (((*x).kindU.S3.strval ? (*x).kindU.S3.strval->Sup.len : 0))))) goto LA43;
		}
		goto LA36;
		LA43: ;
		{
			localerror_197080((*n).info, ((NU16) 86), ((NimStringDesc*) &TMP3498));
		}
		LA36: ;
	}
	break;
	default:
	{
	}
	break;
	}
	}BeforeRet: ;
	return result;
}

N_NIMCALL(Tnode293798*, foldfieldaccess_354167)(Tsym293830* m, Tnode293798* n) {
	Tnode293798* result;
	Tnode293798* x;
	Tsym293830* field;
{	result = 0;
	x = getconstexpr_353001(m, (*n).kindU.S6.sons->data[((NI) 0)]);
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (x == NIM_NIL);
		if (LOC3) goto LA4;
		LOC3 = !(((*x).kind == ((NU8) 38) || (*x).kind == ((NU8) 37)));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	field = (*(*n).kindU.S6.sons->data[((NI) 1)]).kindU.S4.sym;
	{
		NI i_354415;
		NI HEX3Atmp_354447;
		NI HEX3Atmp_354448;
		NI LOC8;
		NI res_354451;
		i_354415 = 0;
		HEX3Atmp_354447 = 0;
		HEX3Atmp_354448 = 0;
		HEX3Atmp_354447 = ((*x).kind == ((NU8) 38));
		LOC8 = 0;
		LOC8 = sonslen_296351(x);
		HEX3Atmp_354448 = (NI)(LOC8 - ((NI) 1));
		res_354451 = ((NI) (HEX3Atmp_354447));
		{
			while (1) {
				Tnode293798* it;
				if (!(res_354451 <= HEX3Atmp_354448)) goto LA10;
				i_354415 = res_354451;
				it = (*x).kindU.S6.sons->data[i_354415];
				{
					if (!!(((*it).kind == ((NU8) 34)))) goto LA13;
					result = (*x).kindU.S6.sons->data[(*field).position];
					{
						if (!((*result).kind == ((NU8) 34))) goto LA17;
						result = (*result).kindU.S6.sons->data[((NI) 1)];
					}
					LA17: ;
					goto BeforeRet;
				}
				LA13: ;
				{
					if (!((*(*(*(*it).kindU.S6.sons->data[((NI) 0)]).kindU.S4.sym).name).Sup.id == (*(*field).name).Sup.id)) goto LA21;
					result = (*(*x).kindU.S6.sons->data[i_354415]).kindU.S6.sons->data[((NI) 1)];
					goto BeforeRet;
				}
				LA21: ;
				res_354451 += ((NI) 1);
			} LA10: ;
		}
	}
	localerror_197080((*n).info, ((NU16) 214), (*(*field).name).s);
	}BeforeRet: ;
	return result;
}

N_NIMCALL(Tnode293798*, getconstexpr_353001)(Tsym293830* m, Tnode293798* n) {
	Tnode293798* volatile result;
{	result = 0;
	result = NIM_NIL;
	switch ((*n).kind) {
	case ((NU8) 3):
	{
		Tsym293830* s;
		s = (*n).kindU.S4.sym;
		switch ((*s).kind) {
		case ((NU8) 19):
		{
			result = newintnodet_353016(((NI64) ((*s).position)), n);
		}
		break;
		case ((NU8) 10):
		{
			switch ((*s).magic) {
			case ((NU16) 210):
			{
				result = newintnodet_353016(((NI64) ((((*m).flags &(1U<<((NU)(((NU8) 12))&31U)))!=0))), n);
			}
			break;
			case ((NU16) 211):
			{
				NimStringDesc* LOC6;
				LOC6 = 0;
				LOC6 = ntgetDateStr();
				result = newstrnodet_353024(LOC6, n);
			}
			break;
			case ((NU16) 212):
			{
				NimStringDesc* LOC8;
				LOC8 = 0;
				LOC8 = ntgetClockStr();
				result = newstrnodet_353024(LOC8, n);
			}
			break;
			case ((NU16) 214):
			{
				result = newintnodet_353016(((NI64) (Cpu_177477[(targetcpu_177608)- 1].Field2)), n);
			}
			break;
			case ((NU16) 215):
			{
				NimStringDesc* LOC11;
				LOC11 = 0;
				LOC11 = nsuToLowerAsciiStr(Os_177055[(targetos_177610)- 1].Field0);
				result = newstrnodet_353024(LOC11, n);
			}
			break;
			case ((NU16) 216):
			{
				NimStringDesc* LOC13;
				LOC13 = 0;
				LOC13 = nsuToLowerAsciiStr(Cpu_177477[(targetcpu_177608)- 1].Field0);
				result = newstrnodet_353024(LOC13, n);
			}
			break;
			case ((NU16) 217):
			{
				result = getapptype_354015(n);
			}
			break;
			case ((NU16) 218):
			{
				result = newfloatnodet_353020(NAN, n);
			}
			break;
			case ((NU16) 219):
			{
				result = newfloatnodet_353020(INF, n);
			}
			break;
			case ((NU16) 220):
			{
				result = newfloatnodet_353020(-INF, n);
			}
			break;
			case ((NU16) 262):
			{
				{
					NIM_BOOL LOC21;
					NimStringDesc* LOC24;
					NI LOC25;
					LOC21 = 0;
					LOC21 = isdefined_201141((*s).name);
					if (!LOC21) goto LA22;
					LOC24 = 0;
					LOC24 = lookupsymbol_201149((*s).name);
					LOC25 = 0;
					LOC25 = nsuParseInt(LOC24);
					result = newintnodet_353016(((NI64) (LOC25)), n);
				}
				LA22: ;
			}
			break;
			case ((NU16) 263):
			{
				{
					NIM_BOOL LOC29;
					NimStringDesc* LOC32;
					LOC29 = 0;
					LOC29 = isdefined_201141((*s).name);
					if (!LOC29) goto LA30;
					LOC32 = 0;
					LOC32 = lookupsymbol_201149((*s).name);
					result = newstrnodet_353024(LOC32, n);
				}
				LA30: ;
			}
			break;
			default:
			{
				result = copytree_297822((*s).ast);
			}
			break;
			}
		}
		break;
		case ((NU8) 12):
		case ((NU8) 13):
		{
			result = n;
		}
		break;
		case ((NU8) 7):
		{
			result = newsymnodetypedesc_354496(s, (*n).info);
		}
		break;
		case ((NU8) 4):
		{
			{
				if (!((*(*s).typ).kind == ((NU8) 59))) goto LA39;
				{
					if (!!(((*(*s).typ).n == NIM_NIL))) goto LA43;
					result = (*(*s).typ).n;
					asgnRefNoCycle((void**) (&(*result).typ), (*(*s).typ).sons->data[((NI) 0)]);
				}
				LA43: ;
			}
			goto LA37;
			LA39: ;
			{
				result = newsymnodetypedesc_354496(s, (*n).info);
			}
			LA37: ;
		}
		break;
		default:
		{
		}
		break;
		}
	}
	break;
	case ((NU8) 5) ... ((NU8) 23):
	{
		result = copynode_297528(n);
	}
	break;
	case ((NU8) 48):
	{
		result = getconstifexpr_353857(m, n);
	}
	break;
	case ((NU8) 27):
	case ((NU8) 29):
	case ((NU8) 30):
	case ((NU8) 31):
	case ((NU8) 26):
	case ((NU8) 28):
	case ((NU8) 32):
	{
		Tsym293830* s;
		TSafePoint TMP3488;
		{
			if (!!(((*(*n).kindU.S6.sons->data[((NI) 0)]).kind == ((NU8) 3)))) goto LA52;
			goto BeforeRet;
		}
		LA52: ;
		s = (*(*n).kindU.S6.sons->data[((NI) 0)]).kindU.S4.sym;
		{
			if (!!(((*s).kind == ((NU8) 12)))) goto LA56;
			goto BeforeRet;
		}
		LA56: ;
		pushSafePoint(&TMP3488);
		TMP3488.status = setjmp(TMP3488.context);
		if (TMP3488.status == 0) {
			switch ((*s).magic) {
			case ((NU16) 0):
			{
				popSafePoint();
				goto BeforeRet;
			}
			break;
			case ((NU16) 9):
			{
				Tnode293798* a;
				a = (*n).kindU.S6.sons->data[((NI) 1)];
				{
					NI64 LOC63;
					LOC63 = 0;
					LOC63 = computesize_321121((*a).typ);
					if (!(LOC63 < IL64(0))) goto LA64;
					localerror_197080((*a).info, ((NU16) 81), ((NimStringDesc*) &TMP3489));
					result = NIM_NIL;
				}
				goto LA61;
				LA64: ;
				{
					Ttype293836* LOC67;
					NI64 LOC70;
					LOC67 = 0;
					LOC67 = skiptypes_297099((*a).typ, IL64(211106232576256));
					if (!((IL64(1161083061026822) &((NU64)1<<((NU)((*LOC67).kind)&63U)))!=0)) goto LA68;
					LOC70 = 0;
					LOC70 = getsize_321124((*a).typ);
					result = newintnodet_353016(LOC70, n);
				}
				goto LA61;
				LA68: ;
				{
					result = NIM_NIL;
				}
				LA61: ;
			}
			break;
			case ((NU16) 7):
			{
				NI64 LOC73;
				LOC73 = 0;
				LOC73 = firstord_321001((*(*n).kindU.S6.sons->data[((NI) 1)]).typ);
				result = newintnodet_353016(LOC73, n);
			}
			break;
			case ((NU16) 8):
			{
				{
					Ttype293836* LOC77;
					Tnode293798* LOC80;
					Ttype293836* LOC81;
					NI64 LOC82;
					LOC77 = 0;
					LOC77 = skiptypes_297099((*(*n).kindU.S6.sons->data[((NI) 1)]).typ, IL64(211106240964864));
					if (!!(((IL64(281475933011968) &((NU64)1<<((NU)((*LOC77).kind)&63U)))!=0))) goto LA78;
					LOC80 = 0;
					LOC80 = HEX5BHEX5D_294238(n, ((NI) 1));
					LOC81 = 0;
					LOC81 = skiptypes_297099((*LOC80).typ, IL64(211106240964864));
					LOC82 = 0;
					LOC82 = lastord_321004(LOC81);
					result = newintnodet_353016(LOC82, n);
				}
				goto LA75;
				LA78: ;
				{
					Tnode293798* a;
					a = getarrayconstr_354072(m, (*n).kindU.S6.sons->data[((NI) 1)]);
					{
						NI LOC88;
						if (!((*a).kind == ((NU8) 41))) goto LA86;
						LOC88 = 0;
						LOC88 = sonslen_296351(a);
						result = newintnodet_353016(((NI64) ((NI)(LOC88 - ((NI) 1)))), n);
					}
					LA86: ;
				}
				LA75: ;
			}
			break;
			case ((NU16) 33):
			{
				Tnode293798* a;
				a = getarrayconstr_354072(m, (*n).kindU.S6.sons->data[((NI) 1)]);
				{
					NI LOC94;
					if (!((*a).kind == ((NU8) 41))) goto LA92;
					LOC94 = 0;
					LOC94 = sonslen_296351(a);
					result = newintnodet_353016(((NI64) (LOC94)), n);
				}
				goto LA90;
				LA92: ;
				{
					result = magiccall_353962(m, n);
				}
				LA90: ;
			}
			break;
			case ((NU16) 35):
			{
				NI64 LOC97;
				LOC97 = 0;
				LOC97 = lengthord_321007((*(*n).kindU.S6.sons->data[((NI) 1)]).typ);
				result = newintnodet_353016(LOC97, n);
			}
			break;
			case ((NU16) 154):
			{
				Tnode293798* LOC99;
				NimStringDesc* LOC100;
				LOC99 = 0;
				LOC99 = HEX5BHEX5D_294238(n, ((NI) 1));
				LOC100 = 0;
				LOC100 = rendertree_312044(LOC99, 4);
				result = newstrnodet_353024(LOC100, n);
			}
			break;
			case ((NU16) 138):
			{
				result = foldconstrstr_354455(m, n);
			}
			break;
			case ((NU16) 11):
			{
				Tnode293798* a;
				Tnode293798* LOC103;
				LOC103 = 0;
				LOC103 = HEX5BHEX5D_294238(n, ((NI) 1));
				a = getconstexpr_353001(m, LOC103);
				{
					NIM_BOOL LOC106;
					NIM_BOOL LOC107;
					LOC106 = 0;
					LOC107 = 0;
					LOC107 = !((a == NIM_NIL));
					if (!(LOC107)) goto LA108;
					LOC107 = ((*a).kind == ((NU8) 3));
					LA108: ;
					LOC106 = LOC107;
					if (!(LOC106)) goto LA109;
					LOC106 = ((*(*a).kindU.S4.sym).kind == ((NU8) 7));
					LA109: ;
					if (!LOC106) goto LA110;
					result = evalis_353470(n, a);
				}
				LA110: ;
			}
			break;
			default:
			{
				result = magiccall_353962(m, n);
			}
			break;
			}
			popSafePoint();
		}
		else {
			popSafePoint();
			if (isObj(getCurrentException()->Sup.m_type, (&NTI3640))) {
				TMP3488.status = 0;
				localerror_197080((*n).info, ((NU16) 80), ((NimStringDesc*) &TMP3498));
				popCurrentException();
			}
			else 			if (isObj(getCurrentException()->Sup.m_type, (&NTI3638))) {
				TMP3488.status = 0;
				localerror_197080((*n).info, ((NU16) 77), ((NimStringDesc*) &TMP3498));
				popCurrentException();
			}
		}
		if (TMP3488.status != 0) reraiseException();
	}
	break;
	case ((NU8) 63):
	{
		Tnode293798* a;
		a = getconstexpr_353001(m, (*n).kindU.S6.sons->data[((NI) 0)]);
		{
			if (!!((a == NIM_NIL))) goto LA119;
			result = n;
			asgnRefNoCycle((void**) (&(*n).kindU.S6.sons->data[((NI) 0)]), a);
		}
		LA119: ;
	}
	break;
	case ((NU8) 41):
	{
		result = copytree_297822(n);
		{
			NI i_354725;
			NI HEX3Atmp_355015;
			NI LOC123;
			NI res_355018;
			i_354725 = 0;
			HEX3Atmp_355015 = 0;
			LOC123 = 0;
			LOC123 = sonslen_296351(n);
			HEX3Atmp_355015 = (NI)(LOC123 - ((NI) 1));
			res_355018 = ((NI) 0);
			{
				while (1) {
					Tnode293798* a;
					if (!(res_355018 <= HEX3Atmp_355015)) goto LA125;
					i_354725 = res_355018;
					a = getconstexpr_353001(m, (*n).kindU.S6.sons->data[i_354725]);
					{
						if (!(a == NIM_NIL)) goto LA128;
						result = NIM_NIL;
						goto BeforeRet;
					}
					LA128: ;
					asgnRefNoCycle((void**) (&(*result).kindU.S6.sons->data[i_354725]), a);
					res_355018 += ((NI) 1);
				} LA125: ;
			}
		}
		(*result).flags |= ((NU16)1)<<((((NU8) 4))%(sizeof(NU16)*8));
	}
	break;
	case ((NU8) 44):
	{
		Tnode293798* a;
		Tnode293798* b;
		a = getconstexpr_353001(m, (*n).kindU.S6.sons->data[((NI) 0)]);
		{
			if (!(a == NIM_NIL)) goto LA133;
			goto BeforeRet;
		}
		LA133: ;
		b = getconstexpr_353001(m, (*n).kindU.S6.sons->data[((NI) 1)]);
		{
			if (!(b == NIM_NIL)) goto LA137;
			goto BeforeRet;
		}
		LA137: ;
		result = copynode_297528(n);
		addson_295807(result, a);
		addson_295807(result, b);
	}
	break;
	case ((NU8) 39):
	{
		result = copytree_297822(n);
		{
			NI i_354790;
			NI HEX3Atmp_355023;
			NI LOC141;
			NI res_355026;
			i_354790 = 0;
			HEX3Atmp_355023 = 0;
			LOC141 = 0;
			LOC141 = sonslen_296351(n);
			HEX3Atmp_355023 = (NI)(LOC141 - ((NI) 1));
			res_355026 = ((NI) 0);
			{
				while (1) {
					Tnode293798* a;
					if (!(res_355026 <= HEX3Atmp_355023)) goto LA143;
					i_354790 = res_355026;
					a = getconstexpr_353001(m, (*n).kindU.S6.sons->data[i_354790]);
					{
						if (!(a == NIM_NIL)) goto LA146;
						result = NIM_NIL;
						goto BeforeRet;
					}
					LA146: ;
					asgnRefNoCycle((void**) (&(*result).kindU.S6.sons->data[i_354790]), a);
					res_355026 += ((NI) 1);
				} LA143: ;
			}
		}
		(*result).flags |= ((NU16)1)<<((((NU8) 4))%(sizeof(NU16)*8));
	}
	break;
	case ((NU8) 38):
	{
		result = copytree_297822(n);
		{
			NI i_354827;
			NI HEX3Atmp_355031;
			NI LOC150;
			NI res_355034;
			i_354827 = 0;
			HEX3Atmp_355031 = 0;
			LOC150 = 0;
			LOC150 = sonslen_296351(n);
			HEX3Atmp_355031 = (NI)(LOC150 - ((NI) 1));
			res_355034 = ((NI) 1);
			{
				while (1) {
					Tnode293798* a;
					if (!(res_355034 <= HEX3Atmp_355031)) goto LA152;
					i_354827 = res_355034;
					a = getconstexpr_353001(m, (*(*n).kindU.S6.sons->data[i_354827]).kindU.S6.sons->data[((NI) 1)]);
					{
						if (!(a == NIM_NIL)) goto LA155;
						result = NIM_NIL;
						goto BeforeRet;
					}
					LA155: ;
					asgnRefNoCycle((void**) (&(*(*result).kindU.S6.sons->data[i_354827]).kindU.S6.sons->data[((NI) 1)]), a);
					res_355034 += ((NI) 1);
				} LA152: ;
			}
		}
		(*result).flags |= ((NU16)1)<<((((NU8) 4))%(sizeof(NU16)*8));
	}
	break;
	case ((NU8) 37):
	{
		result = copytree_297822(n);
		{
			NIM_BOOL LOC160;
			NI LOC161;
			LOC160 = 0;
			LOC161 = 0;
			LOC161 = sonslen_296351(n);
			LOC160 = (((NI) 0) < LOC161);
			if (!(LOC160)) goto LA162;
			LOC160 = ((*(*n).kindU.S6.sons->data[((NI) 0)]).kind == ((NU8) 34));
			LA162: ;
			if (!LOC160) goto LA163;
			{
				NI i_354876;
				NI HEX3Atmp_355039;
				NI LOC166;
				NI res_355042;
				i_354876 = 0;
				HEX3Atmp_355039 = 0;
				LOC166 = 0;
				LOC166 = sonslen_296351(n);
				HEX3Atmp_355039 = (NI)(LOC166 - ((NI) 1));
				res_355042 = ((NI) 0);
				{
					while (1) {
						Tnode293798* a;
						if (!(res_355042 <= HEX3Atmp_355039)) goto LA168;
						i_354876 = res_355042;
						a = getconstexpr_353001(m, (*(*n).kindU.S6.sons->data[i_354876]).kindU.S6.sons->data[((NI) 1)]);
						{
							if (!(a == NIM_NIL)) goto LA171;
							result = NIM_NIL;
							goto BeforeRet;
						}
						LA171: ;
						asgnRefNoCycle((void**) (&(*(*result).kindU.S6.sons->data[i_354876]).kindU.S6.sons->data[((NI) 1)]), a);
						res_355042 += ((NI) 1);
					} LA168: ;
				}
			}
		}
		goto LA158;
		LA163: ;
		{
			{
				NI i_354905;
				NI HEX3Atmp_355047;
				NI LOC175;
				NI res_355050;
				i_354905 = 0;
				HEX3Atmp_355047 = 0;
				LOC175 = 0;
				LOC175 = sonslen_296351(n);
				HEX3Atmp_355047 = (NI)(LOC175 - ((NI) 1));
				res_355050 = ((NI) 0);
				{
					while (1) {
						Tnode293798* a;
						if (!(res_355050 <= HEX3Atmp_355047)) goto LA177;
						i_354905 = res_355050;
						a = getconstexpr_353001(m, (*n).kindU.S6.sons->data[i_354905]);
						{
							if (!(a == NIM_NIL)) goto LA180;
							result = NIM_NIL;
							goto BeforeRet;
						}
						LA180: ;
						asgnRefNoCycle((void**) (&(*result).kindU.S6.sons->data[i_354905]), a);
						res_355050 += ((NI) 1);
					} LA177: ;
				}
			}
		}
		LA158: ;
		(*result).flags |= ((NU16)1)<<((((NU8) 4))%(sizeof(NU16)*8));
	}
	break;
	case ((NU8) 68):
	case ((NU8) 69):
	case ((NU8) 70):
	{
		Tnode293798* a;
		a = getconstexpr_353001(m, (*n).kindU.S6.sons->data[((NI) 0)]);
		{
			if (!(a == NIM_NIL)) goto LA185;
			goto BeforeRet;
		}
		LA185: ;
		{
			NIM_BOOL LOC189;
			LOC189 = 0;
			LOC189 = levalueconv_353012((*n).kindU.S6.sons->data[((NI) 1)], a);
			if (!(LOC189)) goto LA190;
			LOC189 = levalueconv_353012(a, (*n).kindU.S6.sons->data[((NI) 2)]);
			LA190: ;
			if (!LOC189) goto LA191;
			result = a;
			asgnRefNoCycle((void**) (&(*result).typ), (*n).typ);
		}
		goto LA187;
		LA191: ;
		{
			NimStringDesc* LOC194;
			TY194153 LOC195;
			NimStringDesc* LOC196;
			LOC194 = 0;
			LOC194 = msgkindtostring_193723(((NU16) 146));
			memset((void*)LOC195, 0, sizeof(LOC195));
			LOC195[0] = typetostring_321017((*(*n).kindU.S6.sons->data[((NI) 0)]).typ, ((NU8) 0));
			LOC195[1] = typetostring_321017((*n).typ, ((NU8) 0));
			LOC196 = 0;
			LOC196 = nsuFormatOpenArray(LOC194, LOC195, 2);
			localerror_197080((*n).info, ((NU16) 4), LOC196);
		}
		LA187: ;
	}
	break;
	case ((NU8) 71):
	case ((NU8) 72):
	{
		Tnode293798* a;
		a = getconstexpr_353001(m, (*n).kindU.S6.sons->data[((NI) 0)]);
		{
			if (!(a == NIM_NIL)) goto LA200;
			goto BeforeRet;
		}
		LA200: ;
		result = a;
		asgnRefNoCycle((void**) (&(*result).typ), (*n).typ);
	}
	break;
	case ((NU8) 58):
	case ((NU8) 59):
	case ((NU8) 60):
	{
		Tnode293798* a;
		a = getconstexpr_353001(m, (*n).kindU.S6.sons->data[((NI) 1)]);
		{
			if (!(a == NIM_NIL)) goto LA205;
			goto BeforeRet;
		}
		LA205: ;
		result = foldconv_354053(n, a, ((*n).kind == ((NU8) 58)));
	}
	break;
	case ((NU8) 61):
	{
		Tnode293798* a;
		a = getconstexpr_353001(m, (*n).kindU.S6.sons->data[((NI) 1)]);
		{
			if (!(a == NIM_NIL)) goto LA210;
			goto BeforeRet;
		}
		LA210: ;
		{
			if (!((IL64(1125900835880960) &((NU64)1<<((NU)((*(*n).typ).kind)&63U)))!=0)) goto LA214;
			result = a;
			asgnRefNoCycle((void**) (&(*result).typ), (*n).typ);
		}
		LA214: ;
	}
	break;
	case ((NU8) 42):
	{
		result = foldarrayaccess_354098(m, n);
	}
	break;
	case ((NU8) 45):
	{
		result = foldfieldaccess_354167(m, n);
	}
	break;
	default:
	{
	}
	break;
	}
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, isintrange_353136)(Ttype293836* t) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ((*t).kind == ((NU8) 20));
	if (!(LOC1)) goto LA2;
	LOC1 = ((IL64(15459734781952) &((NU64)1<<((NU)((*(*t).sons->data[((NI) 0)]).kind)&63U)))!=0);
	LA2: ;
	result = LOC1;
	return result;
}

N_NIMCALL(Ttype293836*, makerange_353203)(Ttype293836* typ, NI64 first, NI64 last) {
	Ttype293836* result;
	NI64 mina;
	NI64 maxa;
	Tnode293798* lowernode;
	result = 0;
	mina = ((first <= last) ? first : last);
	maxa = ((first >= last) ? first : last);
	lowernode = newintnode_294659(((NU8) 6), mina);
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((*typ).kind == ((NU8) 31));
		if (!(LOC3)) goto LA4;
		LOC3 = (mina == maxa);
		LA4: ;
		if (!LOC3) goto LA5;
		result = getintlittype_338627(lowernode);
	}
	goto LA1;
	LA5: ;
	{
		if (!((IL64(18691697672192) &((NU64)1<<((NU)((*typ).kind)&63U)))!=0)) goto LA8;
		result = typ;
	}
	goto LA1;
	LA8: ;
	{
		Tnode293798* n;
		Tnode293798* LOC11;
		Ttype293836* LOC12;
		n = newnode_294401(((NU8) 44));
		addson_295807(n, lowernode);
		LOC11 = 0;
		LOC11 = newintnode_294659(((NU8) 6), maxa);
		addson_295807(n, LOC11);
		result = newtype_296107(((NU8) 20), (*typ).owner);
		asgnRefNoCycle((void**) (&(*result).n), n);
		LOC12 = 0;
		LOC12 = skiptypes_297099(typ, 1048576);
		addsonskipintlit_338680(result, LOC12);
	}
	LA1: ;
	return result;
}

static N_INLINE(NIM_BOOL, isfloatrange_353112)(Ttype293836* t) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ((*t).kind == ((NU8) 20));
	if (!(LOC1)) goto LA2;
	LOC1 = ((IL64(1030792151040) &((NU64)1<<((NU)((*(*t).sons->data[((NI) 0)]).kind)&63U)))!=0);
	LA2: ;
	result = LOC1;
	return result;
}

N_NIMCALL(Ttype293836*, makerangef_353242)(Ttype293836* typ, NF first, NF last) {
	Ttype293836* result;
	Tnode293798* n;
	Tnode293798* LOC1;
	Tnode293798* LOC2;
	Ttype293836* LOC3;
	result = 0;
	n = newnode_294401(((NU8) 44));
	LOC1 = 0;
	LOC1 = newfloatnode_294671(((NU8) 16), ((first <= last) ? first : last));
	addson_295807(n, LOC1);
	LOC2 = 0;
	LOC2 = newfloatnode_294671(((NU8) 16), ((first >= last) ? first : last));
	addson_295807(n, LOC2);
	result = newtype_296107(((NU8) 20), (*typ).owner);
	asgnRefNoCycle((void**) (&(*result).n), n);
	LOC3 = 0;
	LOC3 = skiptypes_297099(typ, 1048576);
	addsonskipintlit_338680(result, LOC3);
	return result;
}

static N_INLINE(NIM_BOOL, isintlit_321222)(Ttype293836* t) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	result = 0;
	LOC1 = 0;
	LOC2 = 0;
	LOC2 = ((*t).kind == ((NU8) 31));
	if (!(LOC2)) goto LA3;
	LOC2 = !(((*t).n == NIM_NIL));
	LA3: ;
	LOC1 = LOC2;
	if (!(LOC1)) goto LA4;
	LOC1 = ((*(*t).n).kind == ((NU8) 6));
	LA4: ;
	result = LOC1;
	return result;
}

N_NIMCALL(NI64, pickminint_353169)(Tnode293798* n) {
	NI64 result;
	result = 0;
	{
		if (!((*n).kind >= ((NU8) 6) && (*n).kind <= ((NU8) 15))) goto LA3;
		result = (*n).kindU.S1.intval;
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		LOC6 = 0;
		LOC6 = isintlit_321222((*n).typ);
		if (!LOC6) goto LA7;
		result = (*(*(*n).typ).n).kindU.S1.intval;
	}
	goto LA1;
	LA7: ;
	{
		NIM_BOOL LOC10;
		LOC10 = 0;
		LOC10 = isintrange_353136((*n).typ);
		if (!LOC10) goto LA11;
		result = firstord_321001((*n).typ);
	}
	goto LA1;
	LA11: ;
	{
		internalerror_197100((*n).info, ((NimStringDesc*) &TMP3508));
	}
	LA1: ;
	return result;
}

N_NIMCALL(NI64, pickmaxint_353186)(Tnode293798* n) {
	NI64 result;
	result = 0;
	{
		if (!((*n).kind >= ((NU8) 6) && (*n).kind <= ((NU8) 15))) goto LA3;
		result = (*n).kindU.S1.intval;
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		LOC6 = 0;
		LOC6 = isintlit_321222((*n).typ);
		if (!LOC6) goto LA7;
		result = (*(*(*n).typ).n).kindU.S1.intval;
	}
	goto LA1;
	LA7: ;
	{
		NIM_BOOL LOC10;
		LOC10 = 0;
		LOC10 = isintrange_353136((*n).typ);
		if (!LOC10) goto LA11;
		result = lastord_321004((*n).typ);
	}
	goto LA1;
	LA11: ;
	{
		internalerror_197100((*n).info, ((NimStringDesc*) &TMP3509));
	}
	LA1: ;
	return result;
}

N_NIMCALL(NIM_BOOL, isintrangeorlit_353165)(Ttype293836* t) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = isintrange_353136(t);
	if (LOC1) goto LA2;
	LOC1 = isintlit_321222(t);
	LA2: ;
	result = LOC1;
	return result;
}

N_NIMCALL(Ttype293836*, pickintrange_353160)(Ttype293836* a, Ttype293836* b) {
	Ttype293836* result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = isintrange_353136(a);
		if (!LOC3) goto LA4;
		result = a;
	}
	goto LA1;
	LA4: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = isintrange_353136(b);
		if (!LOC7) goto LA8;
		result = b;
	}
	goto LA1;
	LA8: ;
	{
		result = a;
	}
	LA1: ;
	return result;
}

N_NIMCALL(Ttype293836*, getintervaltype_353262)(NU16 m, Tnode293798* n) {
	Ttype293836* result;
	result = 0;
	result = (*n).typ;
	switch (m) {
	case ((NU16) 96):
	case ((NU16) 97):
	{
		Ttype293836* a;
		a = (*(*n).kindU.S6.sons->data[((NI) 1)]).typ;
		{
			NIM_BOOL LOC4;
			NI64 LOC7;
			NI64 LOC8;
			NI64 LOC9;
			NI64 LOC10;
			LOC4 = 0;
			LOC4 = isintrange_353136(a);
			if (!LOC4) goto LA5;
			LOC7 = 0;
			LOC7 = lastord_321004(a);
			LOC8 = 0;
			LOC8 = HEX7CHEX2DHEX7C_352012(IL64(0), LOC7);
			LOC9 = 0;
			LOC9 = firstord_321001(a);
			LOC10 = 0;
			LOC10 = HEX7CHEX2DHEX7C_352012(IL64(0), LOC9);
			result = makerange_353203(a, LOC8, LOC10);
		}
		LA5: ;
	}
	break;
	case ((NU16) 103):
	{
		Ttype293836* a;
		a = (*(*n).kindU.S6.sons->data[((NI) 1)]).typ;
		{
			NIM_BOOL LOC14;
			NF LOC17;
			NF LOC18;
			LOC14 = 0;
			LOC14 = isfloatrange_353112(a);
			if (!LOC14) goto LA15;
			LOC17 = 0;
			LOC17 = getfloat_298225((*(*a).n).kindU.S6.sons->data[((NI) 1)]);
			LOC18 = 0;
			LOC18 = getfloat_298225((*(*a).n).kindU.S6.sons->data[((NI) 0)]);
			result = makerangef_353242(a, -(LOC17), -(LOC18));
		}
		LA15: ;
	}
	break;
	case ((NU16) 104):
	{
		Ttype293836* a;
		a = (*(*n).kindU.S6.sons->data[((NI) 1)]).typ;
		{
			NIM_BOOL LOC22;
			LOC22 = 0;
			LOC22 = isfloatrange_353112(a);
			if (!LOC22) goto LA23;
			{
				Tnode293798* LOC27;
				NF LOC30;
				LOC27 = 0;
				LOC27 = HEX5BHEX5D_294238((*a).n, ((NI) 0));
				if (!((*LOC27).kindU.S2.floatval <= 0.0)) goto LA28;
				LOC30 = 0;
				LOC30 = getfloat_298225((*(*a).n).kindU.S6.sons->data[((NI) 0)]);
				result = makerangef_353242(a, 0.0, (LOC30 > 0? (LOC30) : -(LOC30)));
			}
			goto LA25;
			LA28: ;
			{
				NF LOC32;
				NF LOC33;
				LOC32 = 0;
				LOC32 = getfloat_298225((*(*a).n).kindU.S6.sons->data[((NI) 1)]);
				LOC33 = 0;
				LOC33 = getfloat_298225((*(*a).n).kindU.S6.sons->data[((NI) 0)]);
				result = makerangef_353242(a, (LOC32 > 0? (LOC32) : -(LOC32)), (LOC33 > 0? (LOC33) : -(LOC33)));
			}
			LA25: ;
		}
		LA23: ;
	}
	break;
	case ((NU16) 98):
	{
		Ttype293836* a;
		a = (*(*n).kindU.S6.sons->data[((NI) 1)]).typ;
		{
			NIM_BOOL LOC37;
			LOC37 = 0;
			LOC37 = isintrange_353136(a);
			if (!LOC37) goto LA38;
			{
				Tnode293798* LOC42;
				NI64 LOC45;
				NI64 LOC46;
				LOC42 = 0;
				LOC42 = HEX5BHEX5D_294238((*a).n, ((NI) 0));
				if (!((*LOC42).kindU.S1.intval <= IL64(0))) goto LA43;
				LOC45 = 0;
				LOC45 = getint_298220((*(*a).n).kindU.S6.sons->data[((NI) 0)]);
				LOC46 = 0;
				LOC46 = HEX7CabsHEX7C_352017(LOC45);
				result = makerange_353203(a, IL64(0), LOC46);
			}
			goto LA40;
			LA43: ;
			{
				NI64 LOC48;
				NI64 LOC49;
				NI64 LOC50;
				NI64 LOC51;
				LOC48 = 0;
				LOC48 = getint_298220((*(*a).n).kindU.S6.sons->data[((NI) 1)]);
				LOC49 = 0;
				LOC49 = HEX7CabsHEX7C_352017(LOC48);
				LOC50 = 0;
				LOC50 = getint_298220((*(*a).n).kindU.S6.sons->data[((NI) 0)]);
				LOC51 = 0;
				LOC51 = HEX7CabsHEX7C_352017(LOC50);
				result = makerange_353203(a, LOC49, LOC51);
			}
			LA40: ;
		}
		LA38: ;
	}
	break;
	case ((NU16) 50):
	{
		Ttype293836* a;
		Ttype293836* b;
		a = (*(*n).kindU.S6.sons->data[((NI) 1)]).typ;
		b = (*(*n).kindU.S6.sons->data[((NI) 2)]).typ;
		{
			NIM_BOOL LOC55;
			NI64 LOC59;
			NI64 LOC60;
			NI64 LOC61;
			NI64 LOC62;
			NI64 LOC63;
			NI64 LOC64;
			LOC55 = 0;
			LOC55 = isintrange_353136(a);
			if (!(LOC55)) goto LA56;
			LOC55 = isintlit_321222(b);
			LA56: ;
			if (!LOC55) goto LA57;
			LOC59 = 0;
			LOC59 = pickminint_353169((*n).kindU.S6.sons->data[((NI) 1)]);
			LOC60 = 0;
			LOC60 = pickminint_353169((*n).kindU.S6.sons->data[((NI) 2)]);
			LOC61 = 0;
			LOC61 = HEX7CHEX2BHEX7C_352007(LOC59, LOC60);
			LOC62 = 0;
			LOC62 = pickmaxint_353186((*n).kindU.S6.sons->data[((NI) 1)]);
			LOC63 = 0;
			LOC63 = pickmaxint_353186((*n).kindU.S6.sons->data[((NI) 2)]);
			LOC64 = 0;
			LOC64 = HEX7CHEX2BHEX7C_352007(LOC62, LOC63);
			result = makerange_353203(a, LOC61, LOC64);
		}
		LA57: ;
	}
	break;
	case ((NU16) 51):
	{
		Ttype293836* a;
		Ttype293836* b;
		a = (*(*n).kindU.S6.sons->data[((NI) 1)]).typ;
		b = (*(*n).kindU.S6.sons->data[((NI) 2)]).typ;
		{
			NIM_BOOL LOC68;
			NI64 LOC72;
			NI64 LOC73;
			NI64 LOC74;
			NI64 LOC75;
			NI64 LOC76;
			NI64 LOC77;
			LOC68 = 0;
			LOC68 = isintrange_353136(a);
			if (!(LOC68)) goto LA69;
			LOC68 = isintlit_321222(b);
			LA69: ;
			if (!LOC68) goto LA70;
			LOC72 = 0;
			LOC72 = pickminint_353169((*n).kindU.S6.sons->data[((NI) 1)]);
			LOC73 = 0;
			LOC73 = pickminint_353169((*n).kindU.S6.sons->data[((NI) 2)]);
			LOC74 = 0;
			LOC74 = HEX7CHEX2DHEX7C_352012(LOC72, LOC73);
			LOC75 = 0;
			LOC75 = pickmaxint_353186((*n).kindU.S6.sons->data[((NI) 1)]);
			LOC76 = 0;
			LOC76 = pickmaxint_353186((*n).kindU.S6.sons->data[((NI) 2)]);
			LOC77 = 0;
			LOC77 = HEX7CHEX2DHEX7C_352012(LOC75, LOC76);
			result = makerange_353203(a, LOC74, LOC77);
		}
		LA70: ;
	}
	break;
	case ((NU16) 45):
	case ((NU16) 65):
	{
		Tnode293798* a_353323;
		Tnode293798* b_353325;
		a_353323 = (*n).kindU.S6.sons->data[((NI) 1)];
		b_353325 = (*n).kindU.S6.sons->data[((NI) 2)];
		{
			NIM_BOOL LOC81;
			Ttype293836* LOC85;
			NI64 LOC86;
			NI64 LOC87;
			NI64 LOC88;
			NI64 LOC89;
			NI64 LOC90;
			NI64 LOC91;
			LOC81 = 0;
			LOC81 = isintrangeorlit_353165((*a_353323).typ);
			if (!(LOC81)) goto LA82;
			LOC81 = isintrangeorlit_353165((*b_353325).typ);
			LA82: ;
			if (!LOC81) goto LA83;
			LOC85 = 0;
			LOC85 = pickintrange_353160((*a_353323).typ, (*b_353325).typ);
			LOC86 = 0;
			LOC86 = pickminint_353169(a_353323);
			LOC87 = 0;
			LOC87 = pickminint_353169(b_353325);
			LOC88 = 0;
			LOC88 = HEX7CHEX2BHEX7C_352007(LOC86, LOC87);
			LOC89 = 0;
			LOC89 = pickmaxint_353186(a_353323);
			LOC90 = 0;
			LOC90 = pickmaxint_353186(b_353325);
			LOC91 = 0;
			LOC91 = HEX7CHEX2BHEX7C_352007(LOC89, LOC90);
			result = makerange_353203(LOC85, LOC88, LOC91);
		}
		LA83: ;
	}
	break;
	case ((NU16) 47):
	case ((NU16) 67):
	{
		Tnode293798* a_353329;
		Tnode293798* b_353331;
		a_353329 = (*n).kindU.S6.sons->data[((NI) 1)];
		b_353331 = (*n).kindU.S6.sons->data[((NI) 2)];
		{
			NIM_BOOL LOC95;
			Ttype293836* LOC99;
			NI64 LOC100;
			NI64 LOC101;
			NI64 LOC102;
			NI64 LOC103;
			NI64 LOC104;
			NI64 LOC105;
			LOC95 = 0;
			LOC95 = isintrangeorlit_353165((*a_353329).typ);
			if (!(LOC95)) goto LA96;
			LOC95 = isintrangeorlit_353165((*b_353331).typ);
			LA96: ;
			if (!LOC95) goto LA97;
			LOC99 = 0;
			LOC99 = pickintrange_353160((*a_353329).typ, (*b_353331).typ);
			LOC100 = 0;
			LOC100 = pickminint_353169(a_353329);
			LOC101 = 0;
			LOC101 = pickminint_353169(b_353331);
			LOC102 = 0;
			LOC102 = HEX7CHEX2AHEX7C_352031(LOC100, LOC101);
			LOC103 = 0;
			LOC103 = pickmaxint_353186(a_353329);
			LOC104 = 0;
			LOC104 = pickmaxint_353186(b_353331);
			LOC105 = 0;
			LOC105 = HEX7CHEX2AHEX7C_352031(LOC103, LOC104);
			result = makerange_353203(LOC99, LOC102, LOC105);
		}
		LA97: ;
	}
	break;
	case ((NU16) 46):
	case ((NU16) 66):
	{
		Tnode293798* a_353335;
		Tnode293798* b_353337;
		a_353335 = (*n).kindU.S6.sons->data[((NI) 1)];
		b_353337 = (*n).kindU.S6.sons->data[((NI) 2)];
		{
			NIM_BOOL LOC109;
			NI64 LOC113;
			NI64 LOC114;
			NI64 LOC115;
			NI64 LOC116;
			NI64 LOC117;
			NI64 LOC118;
			LOC109 = 0;
			LOC109 = isintrange_353136((*a_353335).typ);
			if (!(LOC109)) goto LA110;
			LOC109 = ((*b_353337).kind >= ((NU8) 6) && (*b_353337).kind <= ((NU8) 15));
			LA110: ;
			if (!LOC109) goto LA111;
			LOC113 = 0;
			LOC113 = pickminint_353169(a_353335);
			LOC114 = 0;
			LOC114 = pickminint_353169(b_353337);
			LOC115 = 0;
			LOC115 = HEX7CHEX2DHEX7C_352012(LOC113, LOC114);
			LOC116 = 0;
			LOC116 = pickmaxint_353186(a_353335);
			LOC117 = 0;
			LOC117 = pickmaxint_353186(b_353337);
			LOC118 = 0;
			LOC118 = HEX7CHEX2DHEX7C_352012(LOC116, LOC117);
			result = makerange_353203((*a_353335).typ, LOC115, LOC118);
		}
		LA111: ;
	}
	break;
	case ((NU16) 58):
	{
		Tnode293798* a;
		Tnode293798* b;
		a = (*n).kindU.S6.sons->data[((NI) 1)];
		b = (*n).kindU.S6.sons->data[((NI) 2)];
		{
			Tnode293798* LOC124;
			if (!!(((*b).kind >= ((NU8) 6) && (*b).kind <= ((NU8) 15)))) goto LA122;
			LOC124 = 0;
			LOC124 = a;
			a = b;
			b = LOC124;
		}
		LA122: ;
		{
			NI64 x;
			if (!((*b).kind >= ((NU8) 6) && (*b).kind <= ((NU8) 15))) goto LA127;
			x = HEX7CHEX2BHEX7C_352007((*b).kindU.S1.intval, IL64(1));
			{
				NIM_BOOL LOC131;
				LOC131 = 0;
				LOC131 = ((NI64)(x & -(x)) == x);
				if (!(LOC131)) goto LA132;
				LOC131 = (IL64(0) <= x);
				LA132: ;
				if (!LOC131) goto LA133;
				result = makerange_353203((*a).typ, IL64(0), (*b).kindU.S1.intval);
			}
			LA133: ;
		}
		LA127: ;
	}
	break;
	case ((NU16) 69):
	{
		Tnode293798* a;
		Tnode293798* b;
		a = (*n).kindU.S6.sons->data[((NI) 1)];
		b = (*n).kindU.S6.sons->data[((NI) 2)];
		{
			if (!((*a).kind >= ((NU8) 6) && (*a).kind <= ((NU8) 15))) goto LA138;
			{
				if (!(IL64(0) <= (*b).kindU.S1.intval)) goto LA142;
				result = makerange_353203((*a).typ, IL64(0), (NI64)((*b).kindU.S1.intval - IL64(1)));
			}
			goto LA140;
			LA142: ;
			{
				result = makerange_353203((*a).typ, (NI64)((*b).kindU.S1.intval + IL64(1)), IL64(0));
			}
			LA140: ;
		}
		LA138: ;
	}
	break;
	case ((NU16) 49):
	{
		Tnode293798* a;
		Tnode293798* b;
		a = (*n).kindU.S6.sons->data[((NI) 1)];
		b = (*n).kindU.S6.sons->data[((NI) 2)];
		{
			if (!((*b).kind >= ((NU8) 6) && (*b).kind <= ((NU8) 15))) goto LA148;
			{
				if (!(IL64(0) <= (*b).kindU.S1.intval)) goto LA152;
				result = makerange_353203((*a).typ, -((NI64)((*b).kindU.S1.intval - IL64(1))), (NI64)((*b).kindU.S1.intval - IL64(1)));
			}
			goto LA150;
			LA152: ;
			{
				result = makerange_353203((*a).typ, (NI64)((*b).kindU.S1.intval + IL64(1)), -((NI64)((*b).kindU.S1.intval + IL64(1))));
			}
			LA150: ;
		}
		LA148: ;
	}
	break;
	case ((NU16) 48):
	case ((NU16) 68):
	{
		Tnode293798* a_353426;
		Tnode293798* b_353428;
		a_353426 = (*n).kindU.S6.sons->data[((NI) 1)];
		b_353428 = (*n).kindU.S6.sons->data[((NI) 2)];
		{
			NIM_BOOL LOC158;
			NI64 LOC162;
			NI64 LOC163;
			NI64 LOC164;
			NI64 LOC165;
			NI64 LOC166;
			NI64 LOC167;
			LOC158 = 0;
			LOC158 = isintrange_353136((*a_353426).typ);
			if (!(LOC158)) goto LA159;
			LOC158 = ((*b_353428).kind >= ((NU8) 6) && (*b_353428).kind <= ((NU8) 15));
			LA159: ;
			if (!LOC158) goto LA160;
			LOC162 = 0;
			LOC162 = pickminint_353169(a_353426);
			LOC163 = 0;
			LOC163 = pickminint_353169(b_353428);
			LOC164 = 0;
			LOC164 = HEX7CdivHEX7C_352021(LOC162, LOC163);
			LOC165 = 0;
			LOC165 = pickmaxint_353186(a_353426);
			LOC166 = 0;
			LOC166 = pickmaxint_353186(b_353428);
			LOC167 = 0;
			LOC167 = HEX7CdivHEX7C_352021(LOC165, LOC166);
			result = makerange_353203((*a_353426).typ, LOC164, LOC167);
		}
		LA160: ;
	}
	break;
	case ((NU16) 61):
	{
		Tnode293798* a_353443;
		Tnode293798* b_353445;
		a_353443 = (*n).kindU.S6.sons->data[((NI) 1)];
		b_353445 = (*n).kindU.S6.sons->data[((NI) 2)];
		{
			NIM_BOOL LOC171;
			Ttype293836* LOC175;
			NI64 LOC176;
			NI64 LOC177;
			NI64 LOC178;
			NI64 LOC179;
			LOC171 = 0;
			LOC171 = isintrangeorlit_353165((*a_353443).typ);
			if (!(LOC171)) goto LA172;
			LOC171 = isintrangeorlit_353165((*b_353445).typ);
			LA172: ;
			if (!LOC171) goto LA173;
			LOC175 = 0;
			LOC175 = pickintrange_353160((*a_353443).typ, (*b_353445).typ);
			LOC176 = 0;
			LOC176 = pickminint_353169(a_353443);
			LOC177 = 0;
			LOC177 = pickminint_353169(b_353445);
			LOC178 = 0;
			LOC178 = pickmaxint_353186(a_353443);
			LOC179 = 0;
			LOC179 = pickmaxint_353186(b_353445);
			result = makerange_353203(LOC175, ((LOC176 <= LOC177) ? LOC176 : LOC177), ((LOC178 <= LOC179) ? LOC178 : LOC179));
		}
		LA173: ;
	}
	break;
	case ((NU16) 62):
	{
		Tnode293798* a_353457;
		Tnode293798* b_353459;
		a_353457 = (*n).kindU.S6.sons->data[((NI) 1)];
		b_353459 = (*n).kindU.S6.sons->data[((NI) 2)];
		{
			NIM_BOOL LOC183;
			Ttype293836* LOC187;
			NI64 LOC188;
			NI64 LOC189;
			NI64 LOC190;
			NI64 LOC191;
			LOC183 = 0;
			LOC183 = isintrangeorlit_353165((*a_353457).typ);
			if (!(LOC183)) goto LA184;
			LOC183 = isintrangeorlit_353165((*b_353459).typ);
			LA184: ;
			if (!LOC183) goto LA185;
			LOC187 = 0;
			LOC187 = pickintrange_353160((*a_353457).typ, (*b_353459).typ);
			LOC188 = 0;
			LOC188 = pickminint_353169(a_353457);
			LOC189 = 0;
			LOC189 = pickminint_353169(b_353459);
			LOC190 = 0;
			LOC190 = pickmaxint_353186(a_353457);
			LOC191 = 0;
			LOC191 = pickmaxint_353186(b_353459);
			result = makerange_353203(LOC187, ((LOC188 >= LOC189) ? LOC188 : LOC189), ((LOC190 >= LOC191) ? LOC190 : LOC191));
		}
		LA185: ;
	}
	break;
	default:
	{
	}
	break;
	}
	return result;
}
NIM_EXTERNC N_NOINLINE(void, compiler_semfoldInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, compiler_semfoldDatInit000)(void) {
}

